import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const advancedRayTracing: DetailedLectureTutorial = {
  pdf: "21adv-rt.pdf",
  pageCount: 34,
  estimatedTime: "约 4-5 小时（含面积光、环境光、薄透镜与时间采样练习）",
  question: "为什么基础光线追踪总显得过分锐利，以及怎样把光源、材质、镜头和时间都写成可验证的随机积分？",
  opening: [
    "基础光追通常为每个像素、点光源、镜面反射和时刻各取一个确定样本，因此轮廓、阴影、倒影、焦点和运动都出现不自然的硬边。本讲把这些现象视为同一个问题：真实成像在若干维度上做积分，单样本只是把积分退化成一个点。",
    "课件先用图片与相邻示意图找出软阴影、粗糙反射、景深和运动模糊的物理原因，再以面积光源和环境光为例完整推导 f/p。最后把同一模式落实为四类光线采样。阅读时不要把 jitter 理解成随便抖动；每次随机化都必须说明采样域、PDF、权重和哪些场景状态随样本变化。",
  ],
  outcomes: [
    "从基础光追的一样本假设解释硬轮廓、硬阴影、锐利倒影、无限景深和冻结运动",
    "说明面积光如何产生本影与半影，粗糙 BRDF 如何产生反射方向分布",
    "构造薄透镜相机光线，使同一像素的孔径样本都穿过同一焦平面点",
    "把时间加入 Ray 与场景求交，按快门分布产生运动模糊",
    "在光源面积域推导 Lambert 与任意 BRDF 的直接照明估计量",
    "在入射方向域推导半球均匀、余弦、BRDF 与环境亮度采样",
    "识别课件代码、PDF 与说明文字不一致，并用数据流而不是标签判断策略",
  ],
  runningExample: {
    title: "贯穿例子：一本书、矩形灯与薄透镜相机",
    description: "书立在粗糙桌面上，矩形灯形成软阴影，桌面产生宽反射；相机聚焦书名，背景虚化，曝光期间书轻微移动。每种效果只新增一个采样维度，并保留对应 PDF 与样本权重。",
    code: "pixel sample = (u,v)\nlight sample = y ~ p_A(y)\nBRDF sample = wi ~ p_ω(wi)\nlens sample = a ~ p_lens(a)\ntime sample = t ~ p_shutter(t)\ncolor = average(pathContribution / jointPdf)",
  },
  chapters: [
    {
      id: "one-sample-problem",
      title: "基础光追的问题不是不准确，而是把所有积分都压成一个点",
      pages: "1-4",
      purpose: "用经典光追图像和五类不连续现象建立分布式采样的动机。",
      beats: [
        b(1, "标题页编号有误，但物理页属于 Lecture 21", "PDF 标题写 Advanced Ray Tracing，中央却误写 CS 4620 Lecture 24。", "页脚、课程日程和文件名都表明这是 2018 秋季 Lecture 21；中央 Lecture 24 是沿用旧课件造成的编号错误。本教程按物理页与实际课程顺序记录，不悄悄改动原图。", ["标题 Advanced Ray Tracing", "中央 Lecture 24 与页脚 Lecture 21 冲突", "PDF 共 34 个物理页"]),
        b(2, "基础光追：每一种决策只取一个样本", "标题页展开为 basic ray tracer 的四类单样本规则。", ["每像素一条视线、每个点光源一条阴影线、每次交点一条反射线和可能一条折射线。它们能给出确定、清晰的结果，却都把本应在像素面积、光源面积、方向分布或时间区间上的积分退化为单点。", "advanced 不意味着抛弃 ray tracing，而是在相同求交框架中让每条路径携带更多随机维度，再平均成像。"], ["one sample for everything", "反射/折射仍沿递归路径", "每个确定样本背后都对应一个潜在积分域"], { textbook: book("教材第 4 章", "4.1 与 4.5 基础光追、阴影和镜面反射", "/book/4/", "教材给出视线、阴影线和递归镜面线的基础架构，本讲是在这些接口上扩展采样维度。") }),
        b(3, "经典基础光追图像：几何正确，视觉却像硬质模型", "文字规则换成 Glassner 1989 的反射/折射测试场景。", "图像能展示遮挡、阴影、透明和镜像，证明基础算法在几何上有效；但所有边界异常锐利，材质都像抛光塑料或玻璃，视野从前到后同样清楚。下一页会把这种总体观感拆成可修复的具体假设。", ["物体轮廓有台阶", "阴影边缘同样硬", "反射没有粗糙宽度", "整个场景处于同一焦点"]),
        b(4, "五种不连续：每一种都暴露了被遗漏的积分", "单张图变成 sharp silhouette、shadow、reflection、focus、time 的问题清单。", ["轮廓台阶来自每像素单点采样；硬阴影来自点光源；镜面倒影来自 delta 反射；无限景深来自点孔径；冻结运动来自单一时刻。它们不是同一个物理现象，却能用同一种数值思想处理：在相应域内采多个样本并按 PDF 加权平均。", "本讲重点处理后四项；像素轮廓抗锯齿会在 Lecture 23 单独展开。"], ["silhouette→pixel area", "shadow→light area", "reflection→direction", "focus→aperture", "motion→time"], { pause: "为清单中五个效果分别写出需要积分的变量与单位/测度。" }),
      ],
      checkpoint: "选基础图中的一个像素，列出它若要同时支持软阴影、粗糙反射、景深和运动模糊所需的随机变量；说明哪些变量属于相机、材质、光源和场景。",
    },
    {
      id: "effects-and-causes",
      title: "先看结果，再用相邻示意图定位应该随机化的变量",
      pages: "5-17",
      purpose: "逐组比较软阴影、光泽反射、景深和运动模糊的结果页与原因页。",
      beats: [
        b(5, "软阴影结果：半影宽度携带光源尺寸与距离信息", "问题清单切到书本与地面的软阴影照片。", "书的接触处阴影较硬，离地更远处过渡更宽，因为遮挡物在不同光源点看来位置不同。软阴影不是对硬阴影做模糊滤镜；正确半影随几何关系变化，并保留完全遮挡的本影。", ["书底附近过渡较窄", "远离接触处半影变宽", "地毯纹理仍穿过亮区与半影"]),
        b(6, "点光源为何只有二值可见性", "结果照片换成单一点光源、遮挡物与一条 shadow ray。", "对固定着色点 x，点光源只有一个位置 y。连接 x→y 的线要么被挡、要么可见，因此 visibility 只有 0 或 1，阴影边界必然硬。增加很多同位置阴影线不会产生软阴影。", ["single light ray", "light visible/occluded 两种状态", "点光源没有面积可部分遮挡"]),
        b(7, "面积光为何出现部分可见的半影", "点光源扩展成矩形发光面，图中出现多条 shadow rays。", "面积光上不同 y 对同一 x 可能有不同可见性。完全可见是亮区、完全遮挡是本影、只有部分光源可见就是半影；Monte Carlo 随机采样光源面积，用可见样本比例估计积分。", ["area light 上有多个采样点", "半影处部分射线通过", "光源越大通常半影越宽"], { formula: "visibility(x,y)∈{0,1}，soft shadow 来自 ∫_light visibility(x,y)…dA_y" }),
        b(8, "光泽反射结果：倒影是方向瓣的卷积，而非屏幕模糊", "软阴影示意换成书在粗糙桌面上的宽倒影。", "桌面仍能辨认书的颜色和竖直结构，但倒影随距离和粗糙度扩散。它来自每个表面点对一簇反射方向积分；后处理模糊无法正确处理遮挡、法线变化或不同粗糙度。", ["倒影中央较强、两侧渐弱", "背景也参与反射", "粗糙表面本身几何仍清晰"]),
        b(9, "光滑面：宏观法线确定唯一镜面方向", "结果页切到 smooth surface 与 single reflected ray。", "理想光滑表面让反射分布成为 delta，给定入射/观察关系只有一个方向有贡献，所以反射图像锐利。确定性反射线适合 delta 材质，不应通过在方向附近任意抖动来伪造粗糙度。", ["single reflected ray", "smooth surface、single normal", "锐利来自方向分布退化为一点"]),
        b(10, "粗糙面：微法线分布产生反射方向锥", "相同几何改成 rough surface、many normals 与 cone of reflected rays。", "宏观像素覆盖许多不同微面法线，符合 BRDF 的一簇方向都有概率。要生成无偏样本，应从 BRDF/BSDF 的方向 PDF 抽样并除以该 PDF；仅给镜面方向加均匀偏移通常既不匹配 Phong/GGX，也可能离开半球。", ["cone 代表方向分布，不是实体圆锥", "many normals 对应粗糙微结构", "粗糙度改变 PDF 宽度"], { textbook: book("教材第 14 章", "14.9 微表面材质", "/book/14/", "教材用 GGX 微面法线统计解释粗糙镜面；采样必须与所评估的 BRDF 及其 PDF 一致。") }),
        b(11, "景深结果：焦平面不是一段固定模糊半径", "粗糙反射换成书页照片，只有一条横向区域清晰。", "处在焦平面附近的文字汇聚到同一像素，因此清楚；前后离焦点在传感器上形成 circle of confusion。模糊大小由孔径、焦距、对焦距离和物距共同决定。", ["中部公式最清晰", "前景与后景同时失焦", "景深是三维距离相关而非二维统一 blur"]),
        b(12, "真实/薄透镜的核心：同一物点经不同镜头位置汇聚", "结果照片换成 lens、image plane、object point 与 ideal image point。", "课件只画粗略透镜模型：来自物点的一束光经透镜后在像侧一点汇聚。光追常不模拟多片玻璃，而用 thin-lens 近似保存关键关系：孔径上的不同起点应指向同一焦平面点。", ["lens 有有限宽度", "多条光线在 ideal image point 相交", "焦距与对焦距离不是同一参数"], { textbook: book("教材第 14 章", "14.5.3 薄透镜与散焦模糊", "/book/14/", "教材给出薄透镜的三条性质和 1/a+1/b=1/f，并把镜头半径与焦点位置分开。") }),
        b(13, "点孔径：所有主光线共用原点，所以处处锐利", "透镜示意退化为 pinhole camera，多个物点各只有一条光线。", "针孔把孔径积分压成相机中心一个点。每个可见物点都唯一映射到图像位置，不会产生散焦，因此 basic ray tracer 具有不真实的无限景深。针孔更小不会让计算图更清楚，只会在真实相机中减少进光量。", ["single eye point", "single rays", "always-sharp focus"]),
        b(14, "有限孔径：只在焦平面相交，其他深度形成光斑", "针孔扩展为 finite aperture、cones of rays，并标出 in/out of focus 物点。", "对焦平面上的物点，来自孔径各处的射线落在同一像素；其他深度的物点落点分散。反向追踪时先找针孔主光线与焦平面的交点 q，再在镜头圆盘抽取起点 a，生成 normalize(q-a)。", ["many object points 只有一处处于焦点", "aperture samples 改变 ray origin", "所有同像素样本共享 focus point"], { formula: "q = intersect(pinholeRay, focusPlane)；a~p_lens；ray=(a, normalize(q-a))" }),
        b(15, "运动模糊结果：曝光记录的是一段时间，不是一个姿态", "景深示意换成台球运动序列合成的照片。", "静止球边缘清晰，运动球沿轨迹扩展；透明叠影来自曝光期间不同时间的辐亮度平均。运动模糊能表达速度和方向，但它不是把最终物体遮罩沿速度向量简单拉伸。", ["不同球的速度产生不同拖影", "高光和阴影也随时刻移动", "曝光时间决定轨迹覆盖长度"]),
        b(16, "单一时间样本：每条光线只看见一个冻结姿态", "结果照片换成 moving object 在不同时间的位置与单一 image point。", "basic renderer 在统一时刻 t₀ 求交，等价于零宽快门或闪光灯，运动物体仍完全锐利。若每个像素都用相同但随机的一帧，只会得到随机冻结画面；需要在同一最终像素内平均多个时间样本。", ["single image point", "object positions at different times", "当前射线只命中一个时间状态"]),
        b(17, "制作级图像把所有维度同时使用", "原因示意突然换成《怪兽大学》全页成片，没有正文标题。", "这页是生产质量标尺：背景景深、角色接触软阴影、材质粗糙反射和可能的运动线索共同出现。它不是新公式，而是在推导前提醒这些效果必须共存；联合采样维度增加后，分层、相关性和样本预算变得重要。", ["前景主角最清晰", "背景人物和建筑渐虚", "脚下阴影帮助接地", "多材质具有不同反射宽度"], { pause: "为这张图选三个区域，分别指出最可能由光源面积、镜头孔径、材质方向分布或时间积分产生的视觉证据。" }),
      ],
      checkpoint: "分别画出点光/面积光、针孔/有限孔径、光滑/粗糙面和瞬时/有限快门的成对路径图；每对只允许改变一个变量。",
    },
    {
      id: "area-light-domain",
      title: "第一种直接照明积分：在光源表面选择点",
      pages: "18-24",
      purpose: "从随机阴影线推导面积域几何项、均匀面积 PDF 和任意 BRDF 代码。",
      beats: [
        b(18, "创建软阴影：每条 shadow ray 选不同光源点", "生产图像切回实现步骤和扇形阴影线。", ["对面积光，每次从发光面采样 y，再从着色点 x 发射有限区间阴影线。课件建议从 unit square uniform 开始，再映射到矩形等光源参数域；映射后必须知道面积 PDF。", "多样本时贡献要取平均。若每像素只取一个随机 y，单帧是有噪但无偏的软阴影；跨像素使用结构良好的分层样本可减少成团噪声。"], ["different point on the light", "shadow ray 的 tmax 是 |y-x|", "uniform in square 只是标准域起点"], { textbook: book("教材第 13 章", "13.4 挑选随机点", "/book/13/", "教材说明如何把单位正方形样本变换到圆盘或其他域，并强调变换后密度与 Jacobian。") }),
        b(19, "Lambert 面积光：点源→小面元→求和→面积分", "操作步骤展开为四级公式，积分变量明确为光源点 y。", ["小面元 dA_y 的贡献包含接收面余弦 cosθᵣ、发光面余弦 cosθₛ、距离平方 1/|x-y|² 和可见性。课件公式未显式写 visibility，后面的 shadow 测试负责乘上 0/1。", "kd 在课件中被当作常量 Lambert BRDF；若你的材质参数 ρ 表示半球反射率，应使用 fᵣ=ρ/π，避免少除一个 π。"], ["两个 cosine 分别属于接收面与光源面", "距离是 x 到 y", "dA(y) 表明 PDF 单位为 1/m²"], { formula: "L_o=∫_S L_e(y) f_r · V(x,y) · |n_x·ω| |n_y·(-ω)| / |x-y|² dA_y" }),
        b(20, "均匀采样面积光：p_A=1/A，样本贡献乘光源面积 A", "Lambert 面积分改写为 f(y)、p(y)、g=f/p。", ["若在总面积 A 上均匀选 y，则 p_A(y)=1/A，单样本贡献 g=A·f(y)。A 不是额外亮度调节，而是除以面积密度的结果；漏乘会使相同 radiance 的大灯不比小灯更亮。", "发光面背向 x 时 cosθₛ≤0，应贡献 0；两侧发光材质需明确 separate emission 规则。"], ["PDF 相对于 dA", "g 中保留两个余弦和距离平方", "可见性仍由阴影线决定"], { formula: "y~UniformArea(S): p_A(y)=1/A，g(y)=L_e A f_r G(x,y)V(x,y)" }),
        b(21, "Lambert 伪代码：采样点和 PDF 必须成对返回", "公式页换成 shade(x,k_d,N) 程序。", ["light.sample(x) 返回 y 与实际 p_y；阴影可见时计算 L、接收余弦、光源余弦、距离平方并除以 p_y。把采样与 PDF 放在同一接口可避免灯形状改变后调用方仍误用 1/A。", "课件的 for light in lights 每盏灯只取一个样本，适合说明估计量；若每灯 N 个样本，应累加后除以 N。还要 clamp 两个余弦，并为 shadow ray 设置 epsilon 与到灯距离上界。"], ["y,p_y 同时返回", "dot(-L,light.normal) 是发光面余弦", "distSqr 与 /p_y 都不可省略"], { formula: "contribution = Le·(ρ/π)·V·max(0,nx·L)·max(0,ny·(-L))/(r² p_A(y))" }),
        b(22, "任意 BRDF 的面积积分：只替换材质项，几何项不变", "Lambert kd 推导改成 fᵣ(v,w)，并定义 w(y)。", "视线方向 v 固定，光源点 y 决定入射方向 w=(y-x)/|y-x|。BRDF 评估 fᵣ(v,w)，而两余弦/距离平方仍把光源面积测度转换到着色点的方向影响。", ["n_x 属于接收表面", "n_y 属于光源表面", "w(y) 从 x 指向 y"], { formula: "ω(y)=(y-x)/||y-x||" }),
        b(23, "任意 BRDF + 均匀面积 PDF：仍是同一个 f/p 模板", "第 22 页四级推导收束为一般 f(y)、p=1/A 与 g。", "与第 20 页唯一实质变化是 kd 被 fᵣ(v,w(y)) 取代。若 BRDF 很尖而面积光很大，均匀面积采样可能把许多样本花在不会进入高光瓣的位置；它仍无偏，但方差可能很高。", ["p_A 仍为 1/A", "g 保留 BRDF", "样本域仍是 light surface，不是 hemisphere"]),
        b(24, "一般 BRDF 伪代码：代码变化只在 brdf.eval", "Lambert 程序加入 V 与 brdf 参数，并计算 f_r。", ["程序结构验证了光源与材质可以解耦：light.sample 负责 y,p_A；brdf.eval 负责 v,w 的散射值；visibility 和几何项由 integrator 组合。", "工程上最好让代码显式命名 pdfArea，防止后续与 solid-angle PDF 混用。面积与方向 PDF 可用 p_ω=p_A·r²/|n_y·(-ω)| 转换，但不能直接替代。"], ["新增 V 与 f_r", "其它几何因子与第 21 页相同", "p_y 是面积密度"], { formula: "p_ω(ω)=p_A(y)·||x-y||²/|n_y·(-ω)|", pause: "用单位检查 p_A(1/m²) 经公式转换后为何成为 p_ω(1/sr)。" }),
      ],
      checkpoint: "实现矩形面积光采样器，数值验证 p_A=1/A；在同一 x,y 上分别用面积域估计量和换算后的方向域 PDF 算贡献，结果应一致。",
    },
    {
      id: "direction-domain",
      title: "第二种直接照明积分：在入射半球选择方向",
      pages: "25-30",
      purpose: "从 Lambert 环境光推到任意 BRDF，并比较余弦、BRDF 和环境亮度的重要性采样。",
      beats: [
        b(25, "Lambert 环境积分：把远处光源表示成 Li(ω)", "面积域推导重启为 directional source→small solid angle→sum→hemisphere integral。", ["当光来自无限远环境，位置 y 被方向 ω 取代，测度变成立体角 dω，距离平方和光源面余弦被吸收到入射辐亮度 Li(ω) 中。有限方向小片 Ω_i 的求和在极限下成为半球积分。", "这与面积域不是两个不同物理定律，而是同一直接照明的两种参数化。"], ["积分域 S²⁺", "只剩接收余弦 ω·n", "Li 可以来自 HDR environment map"], { formula: "L_o=∫_{S²⁺}L_i(ω)f_r(ω,v)(ω·n)dω" }),
        b(26, "Lambert 的两种方向 PDF：均匀保留余弦，余弦采样抵消余弦", "环境积分并列 p=1/(2π) 与 p=cosθ/π。", ["半球均匀给 g=2πLi kd cosθ；余弦比例给 g=πLi kd。后者将接近地平线的小贡献方向抽得更少，使样本权重更平坦。若 kd 已定义为 ρ/π，则余弦采样贡献化为 ρLi。", "两式都无偏；better 指较低方差的常见情况，不是所有环境和材质下绝对更好。"], ["2π 是半球立体角", "π 是 ∫cosθdω", "PDF 为零处 cosine 也为零"], { textbook: book("教材第 13 章", "13.3-13.4 重要性采样与半球变换", "/book/13/", "教材推导 f/p、1/√N 收敛并给出 cosⁿθ 半球方向生成；n=1 对应余弦采样。") }),
        b(27, "两段 Lambert 代码：不要只改采样器，还要同步改权重", "公式变成 uniform hemisphere 与 cosine hemisphere 两列伪代码。", ["左列 sample_hemisphere 后乘 dot(w,N)·2π；右列 sample_cos_hemisphere 后只乘 π。若换了采样器却保留旧权重，结果会偏亮或偏暗，而不是仅仅噪声不同。", "课件每次调用只展示一个样本；实际像素平均 N 个方向。采样函数应返回 PDF，让通用 integrator 计算 f/p，比把 2π、π 散落在材质代码中更安全。"], ["左列显式 cosine×2π", "右列 cosine 已被 PDF 抵消", "两列都要做 shadow/environment visibility"]),
        b(28, "任意 BRDF 的方向积分：kd 换成 fᵣ(v,ω)", "Lambert 四级公式改成 arbitrary BRDF，积分结构不变。", "被积函数现在同时受环境亮度 Li、BRDF 高光瓣和余弦影响。只匹配其中一个因子的 PDF 可能仍有很大方差；这正是下一页并列两种重要性策略的原因。", ["v 固定、ω 变化", "三个变化因子 Li·fᵣ·cosθ", "积分域仍是正半球"]),
        b(29, "BRDF 采样与环境采样：分别抵消被积函数的一个峰", "任意 BRDF 积分下面加入两种 PDF 和化简后的 g。", ["若 p∝fᵣ，窄高光方向更常被采到，权重中主要剩 Li·cosθ；若 p∝Li，明亮环境方向更常被采到，权重中主要剩 fᵣ·cosθ。二者都需要各自归一化常数或能直接返回归一化 PDF 的采样器。", "亮小光源与窄镜面瓣若不重合，两种单独策略可能各有灾难性样本。现代实现通常用 multiple importance sampling 合并两者。"], ["上行匹配 BRDF", "下行匹配 environment brightness", "余弦项在两种权重中都仍存在"], { formula: "g(ω)=L_i(ω)f_r(v,ω)(n·ω)/p(ω)" }),
        b(30, "课件第 30 页标签左右写反：以 sample() 调用为准", "公式换成 environment.sample 与 brdf.sample 两列伪代码。", ["左侧代码明确调用 environment.sample(N)，所以它是按 lighting environment 采样；右侧调用 brdf.sample(N)，所以它是按 BRDF 采样。原课件底部却分别标成 sampling by BRDF 与 sampling by lighting environment，标签互换。", "两列其余估计量相同：都重新评估 L_env、f_r、cosine 并除以各自 p_w。判断算法时追踪随机变量由谁生成、PDF 属于谁，不能只信标题。若混用一边生成的方向和另一边 PDF，会产生偏差。"], ["左：environment.sample", "右：brdf.sample", "底部两标签与代码相反", "p_w 必须是实际生成策略的方向密度"], { pause: "在原图上给两列重新标注，并写一个单元测试：采样器返回 strategyId，PDF 求值必须来自同一 strategyId。" }),
      ],
      checkpoint: "对一个有小太阳的 HDR 环境和光泽球，分别描述纯 BRDF、纯环境、余弦与 MIS 的噪声位置；证明生成 PDF 与求值 PDF 不一致会破坏无偏性。",
    },
    {
      id: "distributed-rays",
      title: "把积分落实为光线：方向、孔径和时间各有自己的采样器",
      pages: "31-34",
      purpose: "把前面的积分思想转成光泽反射、景深、运动模糊和生产图像的实现检查表。",
      beats: [
        b(31, "光泽反射：jitter 必须匹配 BRDF，而不是任意偏移", "环境重要性代码换成镜面方向附近的一束随机反射线。", ["对 Phong 可推导与 cosⁿα 成比例的方向采样；对微表面模型通常先采微面法线，再反射得到 ωᵢ，并做 Jacobian/PDF 转换。抖动宏观法线也能构造方向，但必须保证分布、半球与 BRDF 评估一致。", "每条反射线返回的 radiance 要乘 fᵣ cosθ/p。只平均返回颜色而忽略权重，通常只在专门构造的抵消情况下成立。"], ["random offset 只是直觉", "Phong exactly 需要匹配数学分布", "jitter normal 会改变方向 PDF"], { formula: "sample contribution = L_i(ω_i)f_r(ω_i,ω_o)|n·ω_i|/p(ω_i)" }),
        b(32, "景深：随机起点在孔径上，方向始终指向焦平面点", "反射方向锥换成相机孔径和 focus plane 路径图。", ["先用像素样本生成针孔主光线，与焦平面求交得到 q；再在镜头圆盘均匀抽取 a，光线从 a 指向 q。焦平面上的点对所有 a 保持同一投影，其他深度则分散。", "圆盘均匀不能令半径 r 均匀，应取 r=R√ξ；否则样本过度集中在中心，虽然若使用相应 PDF 仍可无偏，却会改变 bokeh 与方差。真实镜头还可能有多边形孔径和 vignetting。"], ["ray origin 随 aperture sample 变化", "focus plane point 不变", "镜头圆盘是二维面积采样域"], { formula: "r=R√ξ₁，φ=2πξ₂，a=e+r(cosφ·u+sinφ·v)" }),
        b(33, "运动模糊：Ray.time 必须贯穿相机、求交、材质与光源", "镜头变量换成有限 shutter interval 与多个 object positions。", ["为每个路径样本从快门区间采时间 t；所有沿该路径的对象变换、相机姿态、灯光和纹理动画都在同一 t 求值。若每次反弹重新采时间，单条路径会穿越不一致的世界状态。", "均匀快门只是最简单模型；rolling shutter 或自定义 shutter curve 需要相应时间 PDF 和权重。场景加速结构也要支持 motion bounds 或按时间插值。"], ["finite shutter times", "time 是 system-wide ray state", "object position depends on the sampled time"], { formula: "t~p_shutter(t)；Ray={origin,direction,time=t}", textbook: book("教材第 14 章", "14.5.3 运动和散焦模糊", "/book/14/", "教材说明薄透镜和随机快门时间，并以 c(time)=g+time(h-g) 给出运动球求交的最小例子。") }),
        b(34, "《蓝雨伞》：分布式采样最终服务于统一的摄影语言", "实现图结束，最后一页用 Pixar 短片的雨夜镜头收束。", ["画面把大面积城市光源、高光/粗糙反射、雨滴运动、景深光斑和复杂遮挡结合在同一积分器中。课件把它作为‘这些想法能达到什么效果’的案例，而不是某个单一算法的结果。", "2013 短片与页上 Tumblr 链接属于课程年代背景；学习重点是识别每种视觉特征对应的采样维度，并理解联合路径空间的方差管理。"], ["背景圆形/多边形 bokeh 暗示有限孔径", "湿表面有宽窄不同的反射", "雨与车辆带来时间变化", "遮挡丰富的城市灯光需要直接照明采样"], { pause: "为画面列一张 integrator 配置表：camera、light、BSDF、time、pixel filter 各采用什么采样域与 PDF。" }),
      ],
      checkpoint: "扩展 Ray 结构加入 time，并实现 thin-lens generateRay；验证孔径半径为 0 时退化为针孔、快门宽度为 0 时退化为冻结帧、粗糙度为 0 时走 delta 镜面分支。",
    },
  ],
  synthesis: [
    "诊断层：硬轮廓、硬阴影、锐利倒影、无限景深和冻结运动分别暴露像素、光源、方向、孔径和时间的单样本假设。",
    "几何层：面积光积分包含接收余弦、发光面余弦、距离平方和可见性；软阴影来自光源部分可见，不是后处理模糊。",
    "测度层：直接照明既可在光源面积 dA 上积分，也可在入射立体角 dω 上积分；两类 PDF 通过几何 Jacobian 转换。",
    "材质层：粗糙反射是 BRDF 方向分布；jitter 必须匹配实际 PDF，并以 fᵣcosθ/p 加权。",
    "相机层：有限孔径让 ray origin 分布在镜头上而共享焦平面点；圆盘均匀采样需要 r=R√ξ。",
    "时间层：快门区间上的 t 是整条路径共享的场景状态，运动物体、相机与灯光都必须在同一 t 求值。",
    "方差层：BRDF 与环境采样各匹配一个峰；MIS 能在复杂照明下避免单一策略的盲区。",
    "验证层：不要相信说明标签而忽略代码。第 30 页的左右标题互换，真实策略由 environment.sample / brdf.sample 和对应 PDF 决定。",
  ],
  finalPractice: "实现 DistributedRayLab：一个粗糙桌面、一本移动的书、矩形面积灯和薄透镜相机。提供 point/area light、mirror/glossy BRDF、pinhole/thin lens、instant/finite shutter 开关；每项可单独退化到基础光追。界面必须显示每条样本的 light point、direction、lens point、time、area/solid-angle PDF、visibility 和 f/p 权重。测试至少覆盖：面积 PDF 积分为 1、面积/方向 PDF 换算一致、两个余弦与 r² 单位正确、uniform 与 cosine 半球均值一致、environment.sample 与 brdf.sample 不得交换 PDF、r=R√ξ 的圆盘径向直方图、孔径 0 和快门 0 的退化性质，以及样本数四倍噪声约减半。最后完成本讲对应高级光追练习，分别提交软阴影、光泽反射、景深和运动模糊的正确/错误对照图。",
};
