import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const antialiasing: DetailedLectureTutorial = {
  pdf: "23antialiasing.pdf",
  pageCount: 52,
  estimatedTime: "约 5 小时（含覆盖率、像素滤波、纹理足迹与 MIP 练习）",
  question: "为什么增加像素或样本有时仍消不掉锯齿和摩尔纹，而真正的抗锯齿必须先回答像素究竟代表哪个面积的平均？",
  opening: [
    "锯齿不是单纯的分辨率不足，而是连续图像中的高频细节被点采样后伪装成了错误的低频结构。一旦采样完成，这些假结构无法靠事后模糊可靠地区分；正确顺序是先用像素滤波器限制带宽，再把滤波结果离散化。",
    "课件用一条有限宽度直线把 point、box 和 Gaussian 三种滤波讲清，再把同一积分放进光线追踪。后半转向更困难的纹理：图像空间中规则方形的像素，经透视和 UV 映射后在纹理空间变成大小、方向不断变化的足迹。MIP map 是对这类面积平均的快速但各向同性近似。",
  ],
  outcomes: [
    "区分连续图像、点样本、像素面积积分与重建后的显示图像",
    "从线段覆盖率解释台阶、宽度抖动和摩尔纹为何都是 aliasing",
    "写出归一化 box/Gaussian 像素滤波积分及其 supersampling 估计",
    "在光追中正确生成规则、分层或抖动的像素样本并平均 radiance",
    "解释 supersampling、MSAA 与纹理过滤分别重复了哪些计算",
    "用 UV 导数构造纹理空间 pixel footprint 的局部 Jacobian",
    "构建完整 MIP 金字塔，计算 LOD，并实现 bilinear/trilinear lookup",
    "识别 MIP 对拉长足迹的过度模糊，并说明各向异性过滤的改进方向",
  ],
  runningExample: {
    title: "贯穿例子：一条斜线、两个球和向远处延伸的网格纹理",
    description: "先把斜线当作连续的黑色矩形，比较中心点、5×5 box 和 Gaussian 覆盖；再给两个球的边缘发射子像素光线；最后用同一地面网格观察近处放大、远处缩小和掠射角足迹。",
    code: "pixelValue = sum_i image(x_i,y_i) * filter(x_i-pixelCenter)\n           / sum_i filter(x_i-pixelCenter)\nfootprint = J * unitPixel\nlod = log2(max(length(dUVdx), length(dUVdy)))\ncolor = trilinear(mip, uv, lod)",
  },
  chapters: [
    {
      id: "coverage-and-filtering",
      title: "先定义像素的面积意义：从二值点采样走向归一化滤波积分",
      pages: "1-20",
      purpose: "用有限宽度直线逐帧建立 aliasing、coverage、box 与 Gaussian filtering。",
      beats: [
        b(1, "抗锯齿：不是美化台阶，而是正确地丢弃不可解析细节", "标题页给出 Lecture 23。", "本讲研究连续信号变成像素网格时怎样避免产生不存在的结构。antialias 的目标不是保存所有高频，而是在目标采样率无法表示它们时，以受控平均替代错误频率。", ["Antialiasing", "CS4620 Lecture 23", "PDF 共 52 个物理页"]),
        b(2, "像素覆盖率连接两讲：抗锯齿负责丢细节，合成负责记住细节", "标题页展开 pixel coverage 的课程定位。", ["一个像素可能同时看到多个表面、颜色或透明层。抗锯齿问如何把像素内部变化压成一个值；下一讲 compositing 问不同图层各自的 coverage/opacity 怎样组合。", "二者都不能把像素误解为没有面积的点。"], ["unresolved detail", "antialiasing: carefully throw away", "compositing: account when combining"]),
        b(3, "Aliasing 的起点：点采样连续图像", "课程定位换成球体图与密集黑矩形两种连续过程。", ["光追程序和解析矩形集合都能在任意实数坐标求颜色，因此它们定义的是连续二维函数；最终像素只是这个函数的离散表示。", "下方密集斜线的真实高频远超像素网格，最容易暴露采样栅格与信号周期相互作用形成的摩尔纹。"], ["continuous image defined by ray tracing", "continuous image from rectangles", "point sampling 只在格点求值"], { textbook: book("教材第 10 章", "10.1.1 采样伪影和锯齿", "/book/10/", "教材用高频正弦被误认成低频正弦说明：样本一旦相同，就无法知道原信号是哪一个。") }),
        b(4, "抗锯齿的一般式：先与滤波器平均，再采样", "两个例子收束为 rasterization、ray tracing、texture mapping 三类来源。", ["像素值应是图像在邻域上的加权平均，而非中心点真值。滤波器 h 决定哪些位置影响像素以及权重。", "不同生成方式只改变如何计算积分：解析覆盖、发射多条光线，或在纹理空间近似足迹。"], ["average over an area", "weight by a filter", "source-specific implementation"], { formula: "I[p]=∫∫ I_c(x,y) h_p(x,y) dxdy，且 ∫∫h_p=1" }),
        b(5, "直线动画 1：先画中心线，但真实线段还没有宽度", "抽象公式换成像素网格和一条斜向中心线。", "课件说 line 定义为 rectangle；这一帧只画中心骨架，方便下一帧观察宽度如何从几何定义出现。灰点是像素中心，不是像素本身。", ["两端点定义方向", "黑线只是 centerline", "方格区域才是 pixel support"]),
        b(6, "直线动画 2：中心线膨胀为连续矩形", "中心线两侧新增半透明蓝色带。", "蓝带内连续图像为黑，外部为白，边界是不连续阶跃。它跨过许多像素面积，却不保证经过这些像素的中心。", ["新增有限 width", "inside/outside 是连续平面定义", "锋利边缘包含任意高频"]),
        b(7, "点采样动画 1：标出落在蓝带内的像素中心", "标题改为 Point sampling，蓝带上若干中心点变黑。", "规则是只问 I(center)：中心落在线内就整像素黑，否则整像素白。这里先显示决策点，让我们看到几何覆盖与二值选择之间的信息损失。", ["黑点是 selected centers", "只取一个位置", "像素部分覆盖尚未计入"]),
        b(8, "点采样动画 2：二值中心决策变成楼梯像素", "蓝色连续矩形消失，被黑色整格 staircase 取代。", ["同一行连续命中的中心形成长横段，跨到下一像素行时突然跳一级，所以出现锯齿；不同位置命中中心数变化，视觉线宽也忽粗忽细。", "楼梯不是原始几何的特征，而是采样格生成的新低频结构。"], ["all-or-nothing pixels", "长横阶梯", "宽度变化"], { pause: "移动直线小于半个像素，预测哪些中心会翻转；解释为什么图像会突然跳而非平滑移动。" }),
        b(9, "Point sampling in action：摩尔纹是更大尺度的错误结构", "局部楼梯换成同心/放射密线的整幅结果。", "线间距逐渐低于像素可解析尺度后，样本与图案相位拍频，产生原图不存在的扇形、环形暗带。锯齿和摩尔纹只是不同外观的同一欠采样问题。", ["中心黑区是极高频聚集", "弯曲暗带不是输入几何", "规律误差比随机噪声更显眼"]),
        b(10, "Aliasing 的诊断：锐边高频被折叠成台阶和宽度抖动", "演示图下方加入原因总结。", ["点采样快，但没有采样前低通。直线边缘的无限频谱越过 Nyquist，复制频谱发生重叠，结果中出现本不属于原信号的频率。", "提高分辨率把 Nyquist 推高，却不可能让理想锐边真正带限；需要滤波。"], ["stair steps", "variations in width", "introduced features"]),
        b(11, "为什么二值设备只能靠更高 dpi，而连续色调像素可以做覆盖平均", "局部原因换成输出设备差异。", "若每个像素只能黑/白，最终仍需用空间抖动模拟灰度，因此打印机常用 600+ dpi 把台阶缩小到不可见。屏幕能显示中间强度，就可让边缘像素直接编码部分覆盖。", ["all-or-nothing change 必有 step", "bitmap device", "continuous-tone device"]),
        b(12, "核心替换：不问中心是不是黑，而问整个像素有多少被覆盖", "文字差异换回斜线，像素显示连续灰度。", "覆盖 80% 的像素应接近黑，覆盖 16% 的像素应较浅。把 yes/no 变为面积比例后，直线平移时像素值连续变化，台阶的对比度显著降低。", ["灰度代表 coverage", "几何边缘仍锐利", "像素值随覆盖量连续"]),
        b(13, "Box filter：像素强度就是方形像素内的无权面积平均", "覆盖直觉写成 unweighted area averaging。", "对黑=1、白=0 的 indicator 函数，box filter 的结果恰是交叠面积/像素面积。一般彩色图像则是像素方形内颜色积分的平均。", ["square pixel area", "每个内部位置权重相等", "滤波器积分需为 1"], { formula: "C_p=(1/A_p)∫_{A_p} C(x,y) dA" }),
        b(14, "5×5 超采样：用命中子像素数估计 box coverage", "解析面积公式换成两个 25 点计数例子。", ["20/25 covered 给 80% gray，4/25 给 16% gray。每个子样本代表相等的小面积，平均正是规则求积对 box 积分的近似。", "simple/accurate 只在样本足够细时成立；细线、极小三角形或规则周期仍可能落在所有子样本之间。"], ["5×5=25 samples", "20/25 与 4/25", "误差来自有限样本而非公式"]),
        b(15, "Box filtering in action：摩尔纹减弱，但硬 support 仍会泄漏高频", "单条线计数换成整幅 box-filter 结果。", "与第 9 页相比，大尺度假条纹明显减少，但远处线群仍有残余结构。空间 box 的频域是 sinc，旁瓣会让部分高频泄漏；滤波与锐度之间仍需权衡。", ["中心过渡更平滑", "残余暗带仍可见", "不是简单 post-blur"]),
        b(16, "Weighted filtering：像素中心附近权重大，边缘权重平滑衰减", "box 结果转为 box 与 Gaussian 的滤波器选择。", ["Box 在 support 边界突然从常数跳到 0，像素刚接触几何时会较突然开启。Gaussian 用平滑权重减弱这种跳变。", "任何滤波器都必须归一化；截断 Gaussian 时应除以实际离散权重和，否则常量图像会变暗。"], ["near edge 与 near center 权重不同", "Gaussian 是常见平滑核", "unit integral"]),
        b(17, "加权超采样动画 1：先把 Gaussian 权重铺在像素邻域", "文字页换成斜线和一团由中心向外变弱的子样本网格。", "这一帧展示 filter support 与权重：中心深、外围浅。此时先考虑 h(x_i-p)，尚未用几何覆盖把白色样本剔除。滤波器可跨过单个像素边界，因此邻域样本也可能影响当前像素。", ["圆形/方形截断 support", "中心权重大", "所有候选 subpixels 先有 filter value"]),
        b(18, "加权超采样动画 2：只保留被斜线覆盖的权重", "上一页外围未覆盖样本变白，留下蓝带内的加权子样本。", "估计量现在把 coverage indicator 与 Gaussian 权重相乘，再除以所有采样权重之和。它近似的不是纯面积比例，而是被滤波器加权后的覆盖。", ["相邻页变化是 coverage mask", "covered samples 才贡献黑色", "分母仍需包含归一化权重"], { formula: "C_p≈Σ_i C(x_i)h(x_i-p) / Σ_i h(x_i-p)" }),
        b(19, "Gaussian filtering in action：规则假纹转为更平滑的灰度过渡", "局部加权示意换成完整放射线结果。", "Gaussian 的频谱也平滑衰减，因此比 box 更有效压制摩尔纹，但会牺牲更多真实高频和锐度。图像质量不是‘越模糊越正确’，而是在可接受 alias 与 blur 间选核宽。", ["假暗带进一步减少", "线群更早融合成灰", "中心仍无法解析单线"]),
        b(20, "三种滤波并列：point 最锐但假纹最多，Gaussian 最稳但最软", "三个先前结果裁片并排。", ["Point 保留局部黑白对比，却把高频折叠为粗大纹；box 通过像素面积平均改善，仍有 sinc 旁瓣；Gaussian 误差最平滑，但图案细节更早消失。", "这页不是宣告 Gaussian 永远最佳，而是建立 filter choice 的质量坐标：alias、blur、support cost。"], ["Point sampling", "Box filtering", "Gaussian filtering"], { textbook: book("教材第 10 章", "10.4.2 与 10.5.6", "/book/10/", "教材明确比较 box 的残余摩尔纹、Gaussian 的平滑和实用滤波器的有限 support/振铃权衡。") }),
      ],
      checkpoint: "实现可移动的斜矩形，分别用 center、5×5 box 和截断 Gaussian 计算像素；显示 coverage、权重和归一化分母，并让直线平移时绘制单个边缘像素的值曲线。",
    },
    {
      id: "ray-and-raster-sampling",
      title: "把像素积分落实为多条光线，并分清 supersampling 与 MSAA",
      pages: "21-28",
      purpose: "逐帧比较每像素 1/4/9 样本，写出两种坐标约定，并解释 MSAA 只重复 coverage/depth。",
      beats: [
        b(21, "光追抗锯齿动画 1：先放大单样本图的球轮廓", "滤波比较切换到两个球，右侧放大锯齿边缘。", "连续图像由 camera.getRay(x,y) 与 trace 定义；一像素一条中心光线把球/背景、阴影/地面边界变成二值决策，因此放大后出现台阶。", ["绿色球轮廓", "阴影边缘", "aliased image 放大框"]),
        b(22, "光追动画 2：在每个像素中心标出唯一射线样本", "右侧边缘图叠加像素格和一枚白点。", "每格白点决定整格颜色。一个边缘像素即使 90% 被球覆盖，只要中心落在背景就会完全取背景；这正是第 7–8 页 point sampling 的三维版本。", ["one sample per pixel", "样本在像素中心", "网格颜色等于该点 trace"]),
        b(23, "光追动画 3：每格增加 2×2 样本并平均", "每个像素从一个白点变成四个，左图标签改为 antialiased。", ["四条光线可能命中不同表面，平均后边缘像素得到中间颜色，轮廓和阴影都变平滑。这里规则 2×2 近似 box filter。", "四点仍可能与规则细节共振；生产中常用分层抖动，使每个子格恰有一个随机样本。"], ["four samples per pixel", "边缘格包含多种命中", "平均的是完整 radiance，不只是 coverage"]),
        b(24, "光追结果对比：1 spp 与 9 spp 的收益集中在不连续边缘", "局部 4 样本图换成两张完整 1/9 spp 图。", "9 spp 让球轮廓、接触阴影和倒影边缘更稳定；大块平坦内部几乎不变。自适应采样可利用这一点，把更多样本投入方差高的像素，但必须避免漏掉细小特征。", ["1 sample/pixel", "9 samples/pixel", "内部着色差异小、边界差异大"]),
        b(25, "超采样代码 1：整数像素中心附近用对称子像素偏移", "结果图换成 one sample 与 ns² samples 两列伪代码。", ["左列 getRay(ix,iy)；右列 dx,dy 在 -(ns-1)/2 到 +(ns-1)/2，并用 dx/ns 偏移，最后除 ns²。奇数 ns 时包含中心样本。", "循环顺序不影响均值，但相机必须接受连续 image coordinates；sum 类型要避免过早量化。"], ["ns×ns nested loop", "x=ix+dx/ns", "sum/(ns*ns)"]),
        b(26, "超采样代码 2：单位方形坐标要同时处理像素与子格的半格偏移", "坐标约定改为 [0,1]²，循环从 dx=0 到 ns-1。", ["像素中心是 (ix+0.5)/nx；子样本中心是 (ix+(dx+0.5)/ns)/nx。漏掉任一 0.5 会把样本放到边界并整体偏移半格。", "这页与上一页算法等价，只是 camera 接口坐标单位不同；不要混用两列公式。"], ["除以 nx/ny", "dx+0.5 表示子格中心", "与整数中心约定等价"], { formula: "x=(i+(k+1/2)/n_s)/n_x，y=(j+(l+1/2)/n_s)/n_y", textbook: book("教材第 13 章", "13.3 分层采样", "/book/13/", "教材说明把像素域分成子域后每格取样，通常比同数量独立随机点方差更低。") }),
        b(27, "Supersampling 与 multisampling：前者重复 shading，后者主要重复 coverage/depth", "光追伪代码切到 GPU 成本近似。", ["真 supersampling 为每个 sample 执行完整属性插值、纹理、shader 与 depth；MSAA 通常每像素/fragment 只算一次 shading，再给多个 coverage/depth sample 使用。", "因此 MSAA 很擅长几何轮廓，却不能解决 shader 内高频、程序纹理或一次纹理查找本身的 alias。"], ["one shading value per pixel/fragment", "many subpixel depth samples", "是近似而非同义词"]),
        b(28, "MSAA 图解：多 sample 独立通过深度，resolve 再平均颜色", "文字说明换成 single-sample 与 multisample 三角形覆盖。", "一个 fragment 携带多组 (color,depth) sample；覆盖和 depth test 逐 sample 决定哪些位置写入，最后 resolve 平均。课件说 shading per-fragment，具体 GPU 还可能在 centroid/sample frequency 执行 shader。", ["左侧锯齿覆盖", "右侧多个 sample 点", "final color 是 sample colors 平均"]),
      ],
      checkpoint: "渲染同一高对比三角形与棋盘纹理，比较 1×、4×MSAA、4×SSAA；分别统计 shader executions、depth samples，并解释为何 MSAA 修复轮廓却保留纹理摩尔纹。",
    },
    {
      id: "texture-footprints",
      title: "纹理抗锯齿的难点：规则像素经映射变成不规则、各向异性的足迹",
      pages: "29-36",
      purpose: "从近/远纹理现象走到 image→texture 变量替换、pixel footprint 与 Jacobian。",
      beats: [
        b(29, "MSAA 之后纹理仍会 alias：纹理通常每 fragment 只评估一次", "几何 coverage 转向透视网格的远处破碎图案。", "多个 coverage sample 若共用同一次 texture()，只解决三角形边缘，不会在一个三角形内部对纹理面积平均。透视让远处一个像素覆盖许多 texels，point lookup 必然欠采样。", ["远处网格变成断裂噪点", "几何轮廓不是问题来源", "texture frequency 随距离增加"]),
        b(30, "从 0 到无穷动画 1：靠近时一个 texel 覆盖许多像素", "抽象网格换成 Minecraft 近景方块。", "箭头所指近处雪块显示放大情形：像素足迹小于 texel。主要问题是怎样在 texel 之间重建连续纹理，双线性插值可减少方块感。", ["when you go close", "magnification", "一个 texel→多个 pixels"]),
        b(31, "从 0 到无穷动画 2：远离时一个像素覆盖许多 texels", "镜头退远，箭头指向远山纹理。", "这是 minification：若仍只查一个 texel，会随相机轻微移动在大量候选中跳动，产生闪烁和摩尔纹。需要对 footprint 覆盖的 texels 做面积平均。", ["when you go far", "minification", "many texels→one pixel"]),
        b(32, "Pixel filtering 对照：点查找产生碎片，面积平均产生稳定灰带", "近/远截图换成同一密线纹理的 point 与 area averaging。", "右上 point sampling 把细线变成不规则块；右下 area averaging 不再假装保留每根线，而是保留该区域平均能量。抗锯齿意味着有意识地丢掉不可显示细节。", ["point sampling 假结构", "area averaging 平滑", "平均亮度应近似守恒"]),
        b(33, "变量替换：滤波发生在图像空间，信号却存于纹理空间", "对照图换成 image/texture 两个域的文字分析。", ["图像空间每个像素 support 规则且等大；通过投影逆映射和 UV 函数后，每个像素在 texture space 覆盖不同形状与尺度。", "因此不能用固定数量邻近 texels 处理所有像素，需要估计每次 lookup 的 footprint。"], ["image space friendly", "texture space nonuniform", "integrate over texture coordinates"]),
        b(34, "Pixel footprints：同样大小的图像像素映成不同方向和长度的纹理区域", "文字分析换成地面网格两域箭头图。", "近处足迹小，远处足迹大；掠射区域足迹细长。精确 footprint 还可能弯曲，但在一个像素内通常用局部线性平行四边形近似。", ["image space 白色等大方块", "texture space 灰色足迹大小不同", "远处/斜视足迹拉长"]),
        b(35, "面积随距离变化：magnification、1:1、minification 是连续尺度", "足迹实例抽象为从小到大的平行四边形序列。", ["足迹小于一个 texel 时选重建滤波；约等于一个 texel 时直接查找；覆盖许多 texels 时必须低通。", "实际选择不是只看距离，而看 image→UV 导数；UV 缩放或表面倾斜也会改变 footprint。"], ["upsampling/magnification", "one-to-one", "downsampling/minification"]),
        b(36, "Jacobian：用两个 UV 导数向量近似像素平行四边形", "尺度序列换成 image space 单位基与 texture space 变形基。", ["dUVdx=(∂u/∂x,∂v/∂x) 是图像向右一个像素在纹理中的位移，dUVdy 同理。二者张成局部 footprint；长度决定尺度，夹角和长度比决定各向异性。", "课件图把 ψ(x) 附近的曲线映射线性化。J 只在映射平滑且像素足够小时可靠，跨三角形/UV seam 不能直接共享导数。"], ["(1,0)/(0,1) 两个图像基", "两列 Jacobian", "texture footprint 是平行四边形"], { formula: "J=[∂u/∂x  ∂u/∂y; ∂v/∂x  ∂v/∂y]，F≈{uv+Jδ | δ∈[-1/2,1/2]²}", textbook: book("教材第 11 章", "11.3.1 一个像素的足迹", "/book/11/", "教材从 ψ=φ∘π⁻¹ 定义完整映射，并说明 J 的两列何时形成正方形、斜长平行四边形。") }),
      ],
      checkpoint: "在 shader 或 CPU rasterizer 中可视化 |dUVdx|、|dUVdy|、两者夹角和 det(J)；旋转相机并改变 UV tiling，验证 footprint 由映射导数而非仅由深度决定。",
    },
    {
      id: "mipmap-mechanics",
      title: "MIP map：预先存好方形面积平均，用少量查找近似每个像素足迹",
      pages: "37-44",
      purpose: "逐步完成金字塔构建、LOD 导数公式、双线性/三线性插值和 1/3 内存推导。",
      beats: [
        b(37, "MIP 金字塔：同一纹理的多级预滤波版本", "Jacobian 推导切到从原图逐级缩小的金字塔。", ["Level 0 是原纹理，level k 每边约缩小 2^k；高层 texel 代表底层更大方形区域的平均。运行时以一次/少量查找代替读取足迹内数千 texels。", "课件指出它只高效支持特定尺度的近圆/方形滤波，对拉长 footprint 会过度模糊。"], ["Multum in Parvo", "pre-filtered versions", "fast lookup / circular filters"]),
        b(38, "构建一级：每个高层 texel 汇总低层 2×2 区域", "完整金字塔换成紫色 2×2→单 texel 示意。", "每层都必须在降采样前低通。简单平均是 2×2 box；更好的 Gaussian/downsampling kernel 能减少构建时 alias。颜色纹理应在线性光空间平均，而不是直接平均 sRGB 编码值。", ["4 lower-level texels", "average 或 Gaussian", "递归生成直到 1×1"]),
        b(39, "选择 LOD：找 footprint 最大边约等于一个该层 texel的级别", "构建过程换成 dUVdx/dUVdy 与 level 选择清单。", ["先把 UV 导数换算到 level-0 texel 单位，例如 d=(du·W,dv·H)。用两列向量较长者估算方形宽度 D，再令 level≈log₂D。", "最大边策略保守抑制 alias，却把细长 footprint 的短轴也按长轴模糊。"], ["largest side", "x/y derivatives", "one-to-one at selected level"], { formula: "D=max(||(W du/dx,H dv/dx)||,||(W du/dy,H dv/dy)||)，λ=log₂D" }),
        b(40, "课件 LOD 公式：四个导数合成尺度，但 log 的底数应明确为 2", "清单收束为 max-component 与整体范数两种公式。", ["图上第一式取四个导数绝对值的最大值，第二式取四项平方和开根号；它们都是 footprint 尺度近似。MIP 每级缩小 2 倍，所以实现应使用 log₂，课件写 log 是简写。", "GPU 导数通常来自相邻 2×2 fragment quad；dynamic branching 导致邻居走不同路径时，隐式导数可能未定义。"], ["derivatives available in pixel shader", "max 与 sqrt-sum 两种近似", "dynamic branching 警告"]),
        b(41, "MIP 查找动画 1：先示意一个级别的单点或双线性邻居", "LOD 公式换成 Level i / i+1 和红绿样本点。", "绿色点是连续 UV 查询位置；紫红点表示用于插值的存储 texels。左图此帧只突出当前级别位置，右图显示另一尺度的候选，为跨层插值做准备。", ["Level i 与 i+1", "point sampling 仍比 level 0 好", "bilinear 需要同层四邻居"]),
        b(42, "MIP 查找动画 2：补齐 Level i 的四个双线性邻居", "左侧绿色查询周围新增四个紫红 texel；右侧保持。", ["先在 level floor(λ) 读四 texels 做 bilinear；同理在 ceil(λ) 做一次。仅在单层双线性会在 LOD 跨整数时突然切换，产生可见 mip band。", "图中右层已画四邻居，动画强调两层都需完成各自空间插值。"], ["相邻页新增左层四邻居", "每层 bilinear", "随后按 λ 小数部分混合"]),
        b(43, "MIP 内存图：每一级面积是上一级 1/4", "插值示意换成彩色方块拼出的几何级数。", "若 base 有 N texels，其余层总数 N/4+N/16+…=N/3，因此完整 mip chain 总计 4N/3，即比原纹理多 1/3，而不是多一倍。非方形纹理同样逐轴减半直到 1。", ["彩色层级面积递减", "总额外内存 1/3", "每层还可能有 row/block 对齐开销"], { formula: "N_total=N(1+1/4+1/16+…)=4N/3" }),
        b(44, "MIP 总结：预计算 + 1/3 内存，换取 bilinear/trilinear 常数次查找", "内存问题收束成三条结论。", ["Bilinear 是单层四 texel；trilinear 是相邻两层各 bilinear 后再按 LOD 混合，共八个 texel 贡献。现代硬件通常一次 texture lookup 完成这些过滤。", "它近似的是方形/各向同性 footprint；第 11 章进一步用各向异性过滤沿长轴做多次查询。"], ["multi-resolution pyramid", "pre-sampled", "bilinear or trilinear"], { textbook: book("教材第 11 章", "11.3.3-11.3.5 MipMapping 与各向异性过滤", "/book/11/", "教材补足 λ=log₂D、跨层插值、最长边过度模糊以及沿长轴多查找的改进。") }),
      ],
      checkpoint: "从高频棋盘生成线性光 MIP chain，验证每层尺寸和总 texel 数；实现 nearest-level、bilinear 与 trilinear，并用连续变化的 λ 检查是否出现 level 跳带。",
    },
    {
      id: "visual-audit",
      title: "最后八页不是重复图：它们用近/远两种足迹对照 point、参考积分与 MIP 近似",
      pages: "45-52",
      purpose: "逐对比较相同地面网格的 magnification/minification，识别 alias、过度模糊与各向异性误差。",
      beats: [
        b(45, "Point 对照 1：近处网格尚能被像素解析", "总结页换成 point sampled 地面近景。", "前景格线每段跨多个像素，单点查找大体保留结构；远端已开始密集，但此帧主要建立近距离基线。point sampling 的偶然成功只说明局部频率低于采样率。", ["前景格线连续", "地平线附近变密", "标题 Point sampling"]),
        b(46, "Point 对照 2：视图推远后规则网格碎成噪点和断线", "同一方法切换到更强 minification 的远景。", "相邻页变化是 footprint 尺度而非算法。远端许多 texels 落入一个像素，单一 texel 随相位跳变，形成不规则亮点和虚假方向纹。", ["远处断裂点阵", "线宽忽粗忽细", "相机移动时还会闪烁"]),
        b(47, "512× Gaussian 参考 1：近景保留清晰网格", "方法从 point 改为高成本 Gaussian supersampling，视角回到第 45 页。", "512× reference 用大量样本近似正确像素滤波，近处真实可解析的线仍锐利。这说明抗锯齿不等于无条件模糊；滤波宽度应随 footprint 改变。", ["近景与第45页构图对应", "可解析区域仍清楚", "reference 是质量基准而非实时方案"]),
        b(48, "512× Gaussian 参考 2：远景平滑合并为平均颜色", "相同参考方法切换到第 46 页远景。", "远处网格不再假装显示每根线，而是稳定融合为蓝灰色；真实低频透视趋势保留。它给下一组 MIP 结果提供目标，但 Gaussian 形状与 MIP 方形核并不完全相同。", ["远端无随机碎点", "平均亮度稳定", "近处到远处连续变软"]),
        b(49, "MIP 对照 1：近景与参考接近", "方法改成 mipmap，视角回到近景。", "当 footprint 近似方形且 LOD 较低，trilinear MIP 能以常数成本接近高样本参考。前景仍使用 base/低层，不会因存在 mip chain 自动模糊。", ["近景网格保持", "与第47页比较", "正确 LOD 是关键"]),
        b(50, "MIP 对照 2：远景消除 alias，但比参考更模糊", "MIP 方法切换到远景。", ["远处假噪声被抑制，证明预滤波有效；但掠射地面的 footprint 细长，按最长边选方形 MIP texel 会在短轴方向过度平均，因此整体比第 48 页更糊。", "这正是 anisotropic filtering 的动机：按短轴选层，再沿长轴多点采样。"], ["alias 少", "远处横向/纵向细节过度融合", "各向同性 MIP 局限"]),
        b(51, "Supersampling vs. MIP 对照 1：近景差异小，成本差异巨大", "标题改为两方法比较，显示高样本近景。", "第 51 页取参考/超采样近景；与第 49 页相比视觉相近，但前者每像素追踪/查纹理数百次，后者只需常数次 texture fetch。预计算是在用空间和近似换运行时间。", ["近景 reference", "可解析区二者接近", "成本不是图中可见但必须记录"]),
        b(52, "Supersampling vs. MIP 对照 2：远景揭示 MIP 的各向异性误差", "最后一页切换到 MIP 远景/模糊结果。", ["相邻页从高质量积分切到各向同性预滤波近似，远处明显更软。MIP 仍远好于第 46 页 point alias，但不是任意 footprint 的正确积分。", "整讲最终结论不是‘打开 mipmap 即完成抗锯齿’，而是：估计 footprint、选择与其匹配的低通支持域，再以预算允许的方式积分。"], ["与第48/50页三方比较", "无 alias 不等于最佳锐度", "anisotropy 决定后续改进"]),
      ],
      checkpoint: "用同一相机路径录制 point、512×参考、trilinear MIP 和各向异性过滤；逐帧计算与参考的误差，并同时记录 texture fetch 数，区分 alias error、blur error 与成本。",
    },
  ],
  synthesis: [
    "信号层：连续图像含有像素网格无法表示的高频；点采样把它折叠为错误低频，锯齿、摩尔纹和闪烁都是 alias。",
    "像素层：像素代表带权面积积分；box 是均匀覆盖，Gaussian 平滑衰减，归一化保证常量图像保持常量。",
    "数值层：supersampling 用有限样本估计积分；分层/抖动减少规则共振，误差和样本预算必须显式验证。",
    "光追层：子像素样本要运行完整 trace 并平均 radiance；MSAA 主要重复 coverage/depth，因此不能代替纹理和 shader 抗锯齿。",
    "映射层：图像方形像素通过 ψ=UV∘projection⁻¹ 映成纹理足迹，Jacobian 两列给出局部尺度、方向与各向异性。",
    "预滤波层：MIP 每级保存更大方形区域平均，完整链多 1/3 内存；λ≈log₂D 决定级别，trilinear 消除层间突变。",
    "局限层：MIP 用方形/各向同性核近似拉长 footprint，虽消除 alias 却可能过糊；各向异性过滤沿长轴多查找。",
    "验证层：必须在相同视图下并排 point、参考积分与近似，分别衡量假纹、模糊、时间和 fetch/sample 数。",
  ],
  finalPractice: "实现 AntialiasingLab：场景包含可移动斜矩形、两个光追球和透视地面棋盘。第一模块显示 point、5×5 box、Gaussian 的子样本与权重；第二模块支持 1/4/9 spp 规则、分层抖动并显示每条 ray 的命中；第三模块可视化 dUVdx/dUVdy、footprint、LOD 和被读取的 MIP texels。提供 point、bilinear、nearest-MIP、trilinear、选做 anisotropic 模式。测试至少覆盖：滤波权重和为 1、常量图像不变、半覆盖像素约 0.5、两种坐标约定样本位置一致、MIP 每层是正确预滤波、总 texel 数趋近 4/3、λ 每增加 1 尺度翻倍、trilinear 跨整数 LOD 连续、MSAA 不修复 fragment 内纹理 alias，以及相机近/远运动时与高样本参考的误差曲线。",
};
