import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const colorScience: DetailedLectureTutorial = {
  pdf: "25color.pdf",
  pageCount: 61,
  estimatedTime: "约 5 小时（含光谱积分、RGB/XYZ 变换与色域练习）",
  question: "光本来是波长上的连续能量分布，为什么屏幕只用三个数就能重现许多颜色；这三个数又为什么必须连同原色、白点和编码函数一起解释？",
  opening: [
    "颜色科学横跨三个层次：光谱是物理量，视锥响应是测量结果，颜色是观察者产生的感觉。把三者都叫作‘RGB’会造成最常见的误解。本讲从一个只有单一输出的探测器开始，先建立光谱与响应函数的内积，再把同一数学复制到三类视锥。",
    "三个视锥输出会丢失绝大部分光谱信息，但这种损失恰好使显示器成为可能：屏幕不必重造原光谱，只需产生相同三刺激响应的异谱同色光。随后我们用线性代数求 RGB 驱动值，再以 CIE XYZ、xy 色度、色域、HSV 与 Lab 分清不同坐标系解决的不同问题。",
    "课件页脚把本讲误标为 Lecture 24；课程安排和文件名 25color.pdf 表明它是 Lecture 25。教程保留原课件图像，同时在讲解中纠正这一编号。",
  ],
  outcomes: [
    "把光谱功率分布与探测器响应写成连续积分和离散点积",
    "解释 S/M/L 三刺激值为何不能反演原光谱，以及异谱同色为何成立",
    "区分 radiometric power、luminance、brightness/lightness 与 chromaticity",
    "从显示原色光谱和视觉响应矩阵推导目标光谱到 RGB 驱动值",
    "区分加色显示、减色印刷和表面反射的光谱乘法",
    "用 XYZ 与 xyY 分离亮度和色度，并在色度图上解释光谱轨迹、紫线和色域",
    "说明 sRGB、线性 RGB、XYZ、HSV、Luv 与 Lab 的用途和限制",
    "在颜色转换中明确原色、白点、传递函数、观察条件与超色域处理",
  ],
  runningExample: {
    title: "贯穿例子：把一个苹果的测量光谱重现在 sRGB 显示器上",
    description: "先用标准观察者函数把苹果光谱积分成 XYZ；再把 XYZ 变换到线性 sRGB，检查是否落在原色三角形内，必要时做色域映射；最后编码为 sRGB 数值。沿途保留原光谱，验证屏幕光谱只需视觉匹配而不必物理相同。",
    code: "XYZ = integrate(spd(lambda) * cieXYZ(lambda), lambda)\nlinearRGB = inverse(M_sRGB_to_XYZ) * XYZ\nmanagedRGB = gamutMap(linearRGB)\nsRGB = encodeSRGB(managedRGB)",
  },
  chapters: [
    {
      id: "light-and-detectors",
      title: "先从物理量出发：光谱如何变成探测器的一个数",
      pages: "1-10",
      purpose: "建立波长、光谱功率分布、响应函数和内积，为三刺激色度学准备统一数学。",
      beats: [
        b(1, "颜色科学：同一个词背后有物理、测量与感知三层", "标题页给出 Color Science；页脚误写 Lecture 24。", ["课程实际是 Lecture 25。它不从调色盘开始，而从光和探测器开始，因为 RGB 数值只有在知道它测量或驱动什么时才有意义。", "阅读时持续给量加标签：s(λ) 是光谱，S/M/L 或 XYZ 是三刺激响应，RGB 是某组原色坐标，sRGB 还包含非线性编码。"], ["Color Science", "25color.pdf 共 61 个物理页", "原课件页脚编号错误"]),
        b(2, "棱镜图不是装饰：白光包含可被空间分离的波长成分", "标题页换成棱镜把白光展开为彩带的照片。", "棱镜折射率随波长变化，所以不同波长走向不同方向。图像让我们先接受：一束看起来‘白’的光可以拥有复杂光谱；颜色感觉不是逐波长直接显示在光里。", ["white incident beam", "dispersed spectrum", "同一束光的不同波长成分"]),
        b(3, "光是电磁辐射，频率与波长是同一振荡的两种描述", "棱镜照片扩展为完整电磁谱。", ["在真空中 λ=c/f；可见光只是电磁谱很窄的一段。课程关注约 380–760 nm，具体边界随观察者和阈值而变，教材也常写到约 800 nm。", "波长标签描述光子/单色成分，不等同于完整颜色；大多数实际光是许多波长的集合。"], ["electromagnetic radiation", "frequency or wavelength", "visible band is small"], { textbook: book("教材第 18 章", "章首：光、光子与光谱", "/book/18/", "教材从光子能量与波长关系进入光谱渲染，并强调常用 RGB 是对完整光谱的降维替代。") }),
        b(4, "光谱功率分布 SPD：在每个窄波段里有多少功率", "电磁谱换成横轴波长、纵轴功率/纳米的曲线。", ["s(λ) 的单位可写 W/nm；在宽度 dλ 的窄带内，功率近似 s(λ)dλ，整段功率由积分得到。若只比较色度而不关心总体强度，可把曲线按相对单位归一化。", "SPD 是函数而非三个数。采样存储时还必须记录波长范围、步长和单位。"], ["spectral power distribution", "Watts per nanometer", "band area represents power"], { formula: "P_[λ₁,λ₂]=∫_{λ₁}^{λ₂}s(λ)dλ" }),
        b(5, "颜色是感觉，不是光自身携带的通用标签", "SPD 定义转为 What color is。", ["物理世界提供光谱刺激，颜色则是人类视觉系统对刺激的感觉。不同动物响应波段与受体不同，同一光谱不会产生通用的‘颜色名’。", "表面看起来有色，通常意味着照明、反射或发射随波长变化；灰色近似表示各可见波长按相似比例变化，但感知还受环境适应影响。"], ["380–760 nm approximate sensitivity", "human perception", "colored versus gray"], { textbook: book("教材第 18 章", "导言：没有观察者就没有颜色", "/book/18/", "教材明确把光传播的物理、材料相互作用与大脑产生颜色感觉分成不同层次。") }),
        b(6, "颜色科学的核心映射：从高维物理描述到低维感知响应", "概念页画出光谱曲线、箭头和问号。", "目标不是从波长查一张颜色表，而是建立给定观察条件下的模型 F:s(λ)→color response。课件先采用线性、三刺激的色度学模型；它能预测颜色匹配，却不是完整的颜色外观或认知模型。", ["Physical light description", "Perceptual sensation", "问号代表所需模型"]),
        b(7, "简单探测器：许多波长最终压成一个标量", "映射问题换成光子探测器的文字模型。", ["每个到达光子是否被检测有一个依赖波长的概率；所有成功事件累加成单一信号。输出只有大小，没有标签说明是哪一波长造成，因此不同光谱可以给同一读数。", "半导体相机像素与视网膜光色素都可用这一一阶模型，但真实器件还有噪声、饱和、非线性和空间/时间积分。"], ["scalar output", "wavelength-dependent detection probability", "source wavelengths are lost"]),
        b(8, "探测器图解：输入数量乘检测概率，再在波长上求面积", "上一页文字变成 n(λ)、p(λ) 和乘积阴影面积。", "每个波长的入射光子数 n(λ) 乘检测效率 p(λ)，得到该波段的期望检出数；对所有 λ 积分得到 X。图中蓝色面积就是信号，展示‘响应曲线选择光谱’的几何意义。", ["incident photons per wavelength n(λ)", "detection efficiency p(λ)", "area under product"], { formula: "X=∫n(λ)p(λ)dλ" }),
        b(9, "功率形式：光谱与响应函数的内积", "光子计数图被抽象为 s(λ)、r(λ) 的积分。", ["若输入用 SPD s(λ)，探测器以相容的功率响应 r(λ) 表示，则 X=∫s(λ)r(λ)dλ。单位取决于两函数定义与标定常数。", "同一公式之后会分别生成 S、M、L、Y、X、Z；变化的只是响应函数。"], ["input spectrum", "detector sensitivity", "measured signal"], { formula: "X=⟨r,s⟩=∫s(λ)r(λ)dλ" }),
        b(10, "离散实现：规则波长采样把积分变成点积", "连续积分加入 λᵢ、Δλ 与求和近似。", ["存储向量 sᵢ=s(λᵢ)、rᵢ=r(λᵢ) 后，X≈ΣsᵢrᵢΔλ。若所有数据共享固定 Δλ，它可并入响应权重；不同步长或非均匀波长则必须使用正确求积权。", "点积视角将使颜色匹配、矩阵变换和不可观测子空间自然出现。"], ["regular sample points", "Riemann sum", "clearly a dot product"], { formula: "X≈Σᵢs(λᵢ)r(λᵢ)Δλ", pause: "取 400、500、600 nm 三个样本，s=[2,5,3] W/nm，r=[0.1,0.8,0.4]，Δλ=100 nm，算探测器读数并检查单位。" }),
      ],
      checkpoint: "编写 SpectrumDetector：可编辑 SPD 与 response 曲线，同时显示乘积面积、连续数值积分和离散点积。改变 Δλ，验证采样足够密时二者收敛；再构造两条不同 SPD，使同一探测器读数相同。",
    },
    {
      id: "human-tristimulus-vision",
      title: "人眼把光谱投影成三个数：异谱同色、亮度与色度",
      pages: "11-28",
      purpose: "从不同动物与眼脑结构进入 S/M/L 响应，再解释投影丢失、metamers 和基本色度学概念。",
      beats: [
        b(11, "观察者决定可见世界：人和蜜蜂的波段不同", "探测器数学换成人类约 380–760 nm 与蜜蜂约 340–540 nm 的比较。", "课件用蜜蜂说明感知系统不是被动复制物理世界。蜜蜂看不到人类意义的红，却能感知紫外；因此颜色模型必须声明标准观察者，不能把人类 RGB 当作宇宙坐标。", ["human visible range", "bee ultraviolet sensitivity", "color is observer-dependent"]),
        b(12, "同一花朵的两种成像：可见光照片不是唯一真相", "文字比较变成 Human 与 Honey Bee 两幅花朵图。", ["右图是基于蜜蜂波段/响应的可视化映射，显示花瓣可能存在人眼不可见的对比。它不是蜜蜂主观颜色的直接照片，而是把其敏感差异重新编码给人看。", "任何 false-color 图都要说明传感通道怎样映到显示 RGB。"], ["same flowers", "different spectral sensitivities", "false-color interpretation"]),
        b(13, "人眼动画 1：光经角膜、晶状体投到视网膜", "动物比较切到眼球剖面和 gaze/optical center。", ["眼球光学在视网膜形成倒像；中央凹 fovea 附近视锥密集、视力最高。视神经离开处缺少感光细胞，形成盲点。", "这一帧先建立从物理光到传感器的位置路径，尚未进入神经解释。"], ["fovea", "blind spot", "gaze versus optical center"]),
        b(14, "人眼动画 2：新增虹膜近照，提醒瞳孔调节进入光量", "上一页眼球图右上角增加虹膜/瞳孔照片。", "相邻页变化是把剖面结构连接到可观察的瞳孔开口。虹膜改变通光孔径，影响进入眼内的光量与景深，却不直接按波长分解颜色；光谱选择主要来自视锥色素。", ["相邻页新增 iris/pupil insert", "aperture controls flux", "spectral integration happens at receptors"]),
        b(15, "大脑动画 1：先画眼、视神经与视觉皮层位置", "眼球剖面换成从脑底看到的视觉通路图。", "这页先给解剖底图：左右眼信号沿视神经进入脑内并投向后部视觉区域。颜色感觉不是在眼球图像上天然存在，而是神经信号后续处理的结果。", ["two eyes", "optic nerves", "posterior visual cortex"]),
        b(16, "大脑动画 2：新增蓝色通路，显示一侧视野的交叉投射", "解剖底图叠加蓝色视神经与右侧皮层区域。", "相邻页开始用颜色追踪一组信号。视交叉使每个大脑半球主要处理对侧视野，而不是简单对应同侧眼；图色是教学标记，不是神经本身的颜色。", ["相邻页新增 blue pathway", "optic chiasm", "right cortical destination"]),
        b(17, "大脑动画 3：再加入红色对侧通路", "蓝色通路保留，同时新增红色通路与另一侧皮层。", "两条路径并列强调双眼输入会按视野重新组织并进入两半球。色度学用三刺激近似早期颜色匹配，但完整视觉还包含空间、对比、适应和认知处理。", ["相邻页新增 red pathway", "bilateral processing", "eye is only first stage"]),
        b(18, "大脑动画 4：给整条链加上测量、信号和解释标签", "上一页两色通路旁新增三条说明箭头。", ["课件把 eye 称为 imperfect measuring instrument，中间是 signals，终点是 cognitive & visual interpretation。相邻动画最终明确：测量丢失与大脑解释同时塑造颜色感觉。", "后续色度学主要建模从光谱到匹配响应，不能预测所有上下文中的实际外观。"], ["相邻页新增 three labels", "imperfect measurement", "cognitive interpretation"]),
        b(19, "视网膜不是传感器朝向光的简单平面", "脑通路切到视网膜层、杆/锥细胞与显微照片。", ["光先穿过神经层和血管，再到感光细胞；视杆在弱光下敏感但不提供三色辨别，视锥在正常光照下负责色觉。", "空间分布也不均匀：中央凹高分辨率、周边视杆更多。这里我们只抽取光谱响应这一维。"], ["rods and cones", "inverted retinal layers", "photopigment absorbs photons"], { textbook: book("教材第 18 章", "18.1 色度学", "/book/18/", "教材把杆状体、三类视锥与颜色匹配实验联系起来，并说明色度学是标准观察者的统计近似。") }),
        b(20, "S/M/L 视锥：三条宽且重叠的响应曲线", "视网膜结构变成短、中、长波视锥灵敏度曲线。", ["S、M、L 按峰值相对波长命名，不应简单称蓝、绿、红传感器。每条曲线都覆盖宽波段，尤其 M/L 高度重叠。", "每类输出是整条光谱与响应曲线的积分；三种输出构成 tristimulus values，但不是三个窄波长读数。"], ["broadband sensitivity", "overlapping curves", "trichromatic visual system"]),
        b(21, "一条光谱如何生成 S、M、L：同一个内积做三次", "响应曲线被写成三条积分公式。", "S=∫rS(λ)s(λ)dλ，M、L 同理。离散实现可把三条响应向量堆成 3×n 矩阵，一次乘光谱向量得到三刺激响应。", ["three response functions", "same input spectrum", "three scalar outputs"], { formula: "[S,M,L]ᵀ=M_SML s" }),
        b(22, "色度学给出第一层答案：Physical s 投影成三刺激", "三公式重新放回第 6 页的物理→感知框架。", ["到这里问号被 S、M、L 三个点积取代：它回答‘两刺激是否颜色匹配’，并在 1930 年代标准化。", "它不等于完整感知颜色 sensation；观察条件、空间结构和适应会在后续视觉系统中继续改变外观。"], ["physical spectrum s", "S/M/L outputs", "basic standardized solution"]),
        b(23, "异谱同色：函数压成三数必然丢掉大量信息", "映射框架换成 basic fact 与 metamers 定义。", ["光谱采样可能有几十或几百维，三刺激只有三维；不同 s₁、s₂ 可满足 M_SML s₁=M_SML s₂。它们物理不同，却在给定观察条件下匹配，称 metamers/异谱同色。", "改变观察者、照明或引入不同相机响应后，原本匹配的两个物体可能不再匹配，这叫 metameric failure。"], ["function to three numbers", "information loss", "metamers"]),
        b(24, "伪几何解释 1：视觉是高维光谱向三维子空间的投影", "文字事实改写成投影与正交方向。", ["把每个离散光谱看成 n 维向量，三条响应函数张成至多三维的可见子空间；与三者都正交的差异 δ 满足 Mδ=0，因此完全不可检测。", "课件用 3D→2D 平面作类比；真实维度是 n→3，不要把图中的平面当真实 LMS 空间。"], ["dot product is projection", "null space", "3D-to-2D analogy"]),
        b(25, "伪几何解释 2：新增投影图，metamers 落到同一点", "上一页文字旁加入光谱点、视觉响应平面和垂直投影。", "相邻页图示两个不同光谱沿不可见方向分离，却投到同一个视觉响应点。显示器重现颜色正是利用这一点：生成可控原色子空间里的另一个点，只要投影相同即可。", ["相邻页新增 projection diagram", "two spectra, one response", "metameric equivalence class"]),
        b(26, "Luminance：按人眼明视觉效率加权的光度量", "投影概念转为 V(λ) luminous efficiency 曲线和光源效率。", ["Y=∫V(λ)s(λ)dλ 衡量给定辐射功率对标准观察者产生的明视觉亮度权重。绿色附近效率高，蓝红两端低，所以相同瓦数不等于相同流明。", "课件把 luminance 近似说成 everyday brightness；严格说 luminance 是可测光度量，brightness/lightness 是主观外观，受背景与适应影响。"], ["luminous efficiency V(λ)", "photometric weighting", "not raw radiometric power"]),
        b(27, "Luminance 数学：Y 仍是响应曲线与光谱的点积", "V(λ) 直觉变成 Y=rY·s，并说明它由 S/M/L 线性组合。", "因为视觉可用信息已是三刺激，任何在该模型内可预测的线性光度响应都必须落在 S/M/L 张成空间中。CIE XYZ 特意令 ȳ(λ)=V(λ)，使 Y 通道直接承载 luminance。", ["Y is another response", "Vλ", "linear combination of S/M/L"], { formula: "Y=∫V(λ)s(λ)dλ" }),
        b(28, "色度、主波长和纯度：把总体强度剥离后描述‘哪种颜色’", "Luminance 转为三个相关概念。", ["把光谱整体乘 k 会让三刺激值同比缩放，却不改归一化色度。dominant wavelength 用白点到色度点的射线与光谱轨迹交点近似 hue；purity 是从白点向光谱色移动的比例，关联 saturation。", "紫色等非光谱色没有普通 dominant wavelength，需要用 complementary wavelength 描述；这些量也不是完整感知外观。"], ["chromaticity ignores scale", "dominant wavelength", "purity"], { pause: "若某光谱整体乘 4，S/M/L、Y 和 chromaticity 分别怎样变化？为什么同一 xy 点仍可能从很暗到很亮？" }),
      ],
      checkpoint: "用离散 CIE/LMS 响应矩阵寻找零空间方向 δ，构造两条非负且不同的 SPD 使三刺激近似相同；分别画出光谱、S/M/L 和 Y，并说明条件变化为何可能打破异谱同色。",
    },
    {
      id: "color-reproduction",
      title: "显示器不复制光谱，只复制视觉响应：加色、矩阵求解与减色",
      pages: "29-43",
      purpose: "从 RGB 原色光谱进入颜色重现矩阵，再对照表面反射和 CMY 减色。",
      beats: [
        b(29, "颜色重现目标：让屏幕苹果成为原苹果的 metamer", "色度概念换成真实苹果→显示器苹果和未知 RGB。", ["给定目标光谱 s，‘match’指标准观察者响应相同，而不是屏幕发出相同 SPD。显示器只能产生三条原色光谱的非负组合。", "若所需线性 RGB 有负分量或超过设备最大值，目标超出 gamut；仅增加位深不能让物理原色三角形变大。"], ["source spectrum s", "monitor-producible spectrum", "R,G,B unknown"]),
        b(30, "加色：重叠光束的 SPD 与三刺激直接相加", "苹果匹配问题切到红绿蓝投影重叠照片。", "光在同一位置叠加时功率光谱相加；三刺激积分是线性的，所以响应也相加。红+绿常匹配黄色，三色适当相加匹配白色，但具体结果取决于原色光谱与强度。", ["additive primaries", "overlap regions", "white center is a metamer"]),
        b(31, "LCD 原色：背光经过三种滤色片形成宽窄不一的 SPD", "加色照片换成实际 LCD 三原色发射曲线。", "LCD 原色由背光光谱乘彩色滤片透射率决定，可能有多个峰和串扰。‘R=1’不是 700 nm 单色光，而是一条设备特定 SPD。", ["backlight and filters", "measured primary spectra", "device dependence"]),
        b(32, "LED 原色：三类发光器件的本征峰仍不是理想 delta", "LCD 曲线换成较窄的 LED 蓝绿红峰。", "LED 原色通常更窄，可扩大某些色域，但峰宽与位置仍由材料决定。不同显示器即使收到同一数字 RGB，也可能产生不同光谱和 XYZ；色彩管理必须知道设备表征。", ["native emission curves", "three LED types", "narrower does not mean universal RGB"]),
        b(33, "空间积分：分开的子像素在观看距离上被眼睛合成", "光谱曲线换成 B/G/R 三子像素及其投影到同一响应的图。", ["显示器原色并非在物理上总在同一点混光；子像素空间相邻，眼睛的光学模糊和感受野在正常距离把它们积分。", "近距离可看见彩色条纹，因此空间分辨率与色度学近似相互作用；ClearType 等技术正利用子像素结构。"], ["spatially separated primaries", "visual integration", "same viewing pixel"]),
        b(34, "重述目标：找显示器可产生且与 s 匹配的光谱", "原色实例收束回 color reproduction 定义。", "第 29 页提出问题，第 30–33 页说明设备能产生什么；现在准备把‘相同视觉响应’写成矩阵方程。必须使用线性原色强度，不能把非线性 sRGB 码值直接代入光谱线性组合。", ["display a metamer", "monitor subspace", "linear-light signals"]),
        b(35, "几何图：原色张成的光谱平面投影到视觉响应空间", "文字目标变成高维光谱与两个子空间的伪几何图。", ["显示光谱受限于 span{r,g,b}；眼睛响应受限于三条 response。我们要在显示子空间中找 sa，使其视觉投影与目标 s 相同。", "若解需要负系数，交点只存在于原色线性张成而不在非负锥内，所以设备实际不可产生。"], ["span of monitor primaries", "span of eye responses", "matching projections"]),
        b(36, "矩阵推导 1：先把光谱投影成视觉向量 V", "几何图变成 S/M/L 响应矩阵。", "把 n 波长样本的光谱写成列向量 s，把 rS、rM、rL 写成矩阵 M_SML 的三行，则 V=M_SML s。课件矩阵中的行点积就是第 21 页三次积分的离散形式。", ["response functions as matrix rows", "spectrum column vector", "V=[S,M,L]ᵀ"], { formula: "V=M_SML s" }),
        b(37, "矩阵推导 2：显示器把 RGB 驱动 C 展开成光谱 sa", "视觉投影矩阵旁新增显示原色矩阵。", "把 R、G、B 三条 n 维原色 SPD 放成 M_RGB 的列；线性驱动 C=[R,G,B]ᵀ 产生 sa=M_RGB C。这里的 R/G/B 符号既可指原色光谱又可指系数，代码中应区分 primarySPD 与 channelValue。", ["primary spectra are matrix columns", "linear combination", "sa=M_RGB C"], { formula: "s_a=M_RGB C" }),
        b(38, "矩阵推导 3：把显示产生和眼睛观察串成一个 3×3 映射", "前两步复合为 V=M_SML M_RGB C。", "M_SML 是 3×n，M_RGB 是 n×3，乘积 K=M_SMLM_RGB 为 3×3：它直接把显示线性 RGB 变成视觉三刺激。设备校准的核心就是测量或建立这个矩阵。", ["feed C to display", "display produces sa", "eye produces V"], { formula: "V=K C，K=M_SMLM_RGB" }),
        b(39, "矩阵推导 4：令目标和显示响应相等，求 RGB", "复合关系加入匹配等式和逆矩阵。", ["目标响应 M_SML s 必须等于 K C，所以 C=K⁻¹M_SML s（K 可逆时）。这就是给定目标光谱求显示驱动的 color matching matrix。", "数值解还没保证 0≤C≤1；负值或超 1 表示超色域，需改变原色、降低强度、裁剪或做感知色域映射。"], ["matching equation", "inverse 3×3 matrix", "range check after solving"], { formula: "C=(M_SMLM_RGB)⁻¹M_SMLs", textbook: book("教材第 18 章", "18.2.1 构建矩阵变换", "/book/18/", "教材从原色色度和白点构建 RGB↔XYZ 的 3×3 矩阵，并提醒 sRGB 还需单独处理非线性传递函数。") }),
        b(40, "颜色匹配函数：无需知道真实视锥曲线也能实验测量坐标", "矩阵求解换成单色测试光与三原色匹配实验及 r̄ḡb̄ 曲线。", ["逐波长调节三原色，使左侧混合与右侧单色测试场匹配，记录的权重就是该原色组的 color matching functions。某些波长需要负红权重，实验上把红光加到测试侧。", "负值不是负光真实存在，而是所选物理原色无法用非负混合覆盖全部可见颜色；这推动了 XYZ 虚原色。"], ["split-field experiment", "negative matching weight", "functions depend on chosen primaries"]),
        b(41, "减色：颜料和滤片从入射白光中吸收波段", "加色匹配切换到青、品红、黄色透明片重叠。", "减色混合不是 RGB 数值相减。透过多个滤片时谱透射率相乘，越叠越少；理想 C/M/Y 分别主要吸收 R/G/B，叠加趋向黑。", ["subtractive filters", "cyan/magenta/yellow", "multiplicative transmittance"]),
        b(42, "彩色表面：输出 SPD 是照明光谱与反射率逐波长相乘", "透明片照片换成两组 illuminant × object reflectance = reflected color 曲线。", ["同一物体反射率 ρ(λ) 在不同照明 e(λ) 下产生 s(λ)=e(λ)ρ(λ)。因此‘物体 RGB’不是固定发射颜色；若照明缺少某波段，表面无法反射出它。", "这也是跨光源 metameric failure 与白平衡/色适应问题的物理根源。"], ["illuminant spectrum", "surface reflectance", "pointwise spectral product"], { formula: "s_reflected(λ)=e(λ)ρ(λ)" }),
        b(43, "CMY 印刷是近似模型，真实油墨要靠测量和校准", "光谱乘法收束为减色用途与 C≈1-R 等近似。", ["照片、幻灯片和印刷通过吸收白光构造反射/透射 SPD。理想近似 C=1-R、M=1-G、Y=1-B；实际油墨曲线重叠、纸张散射，并常加 K 黑墨，所以需 ICC profile、网点和经验查表。", "加色的线性叠光与减色的多层吸收有不同代数，不能混用同一个 RGB 混合公式。"], ["C,M,Y primaries", "approximately complements of RGB", "empirical calibration"], { pause: "若白光 e=[1,1,1]，表面 ρ=[0.8,0.4,0.1]，另一盏灯 e₂=[0.1,0.2,1]，分别算反射 SPD；为什么同一表面会显著变色？" }),
      ],
      checkpoint: "给定离散 S/M/L 响应和三条显示原色 SPD，构建 K=M_SMLM_RGB；把目标 SPD 转成 C，检查残差与通道范围。再用两个照明乘同一反射率，展示物理 SPD、XYZ 与显示结果如何变化。",
    },
    {
      id: "xyz-chromaticity-and-gamut",
      title: "标准坐标不是任意三个数：sRGB、XYZ、xy 色度与设备色域",
      pages: "44-52",
      purpose: "从设备相关 RGB 进入 CIE XYZ，再用归一化色度图解释可见颜色、原色三角形和超色域。",
      beats: [
        b(44, "色彩空间回答‘哪三个数’，也必须回答它们怎样变成光", "减色流程转为 color spaces 定义和 monitor RGB 的局限。", ["三个数只有连同原色色度、白点、传递函数和单位/范围才定义颜色。裸 RGB 设备相关：不同原色、gamma、增益会把同一数值变成不同 XYZ。", "一个三原色显示器的非负可达集合有限，所以还会漏掉鲜艳色；坐标范围大不等于设备色域大。"], ["three numbers need a definition", "device dependent", "limited gamut"]),
        b(45, "sRGB：把一种特定 RGB 约定成交换标准", "设备相关问题转向 standardized RGB。", ["sRGB 指定 BT.709 原色、D65 白点和分段传递函数，使文件数值有可移植含义；色彩管理设备通过校准/profile 尽量模拟它。", "sRGB 文件码值不是线性光 RGB。做光照、合成和矩阵运算前先解码；完成后再编码。标准化也没有消除有限色域。"], ["interchange space", "calibrated simulation", "gamut still limited"], { textbook: book("教材第 18 章", "18.2.1-18.2.2 sRGB 与设备 RGB", "/book/18/", "教材给出 sRGB 的 RGB↔XYZ 矩阵、D65 白点和分段非线性，并解释已知空间之间可借 XYZ 转换。") }),
        b(46, "CIE XYZ：用虚原色换取所有可见刺激的非负三刺激", "sRGB 转向 universal color space XYZ。", ["XYZ 是标准观察者颜色匹配坐标。虚原色不是可造的灯，而是一组数学基；其匹配函数设计为非负，并令 ȳ=V(λ)，所以 Y 单独表示 luminance。", "‘任何刺激有非负 XYZ’不表示任意非负 XYZ 都是物理可实现颜色；XYZ 空间仍包含不可实现区域。"], ["CIE standardized", "imaginary primaries", "Y carries luminance"]),
        b(47, "XYZ 匹配函数：直接对光谱做三次积分", "概念页换成 x̄、ȳ、z̄ 曲线与 X/Y/Z 公式。", "给定 SPD s(λ)，X=k∫x̄s、Y=k∫ȳs、Z=k∫z̄s。k 由绝对/相对光度标定决定；比较色度时常归一化。曲线是 CIE 标准观察者，不是某一人的精确视锥曲线。", ["x̄(λ), ȳ(λ), z̄(λ)", "all nonnegative", "Y curve equals luminous efficiency"], { formula: "[X,Y,Z]ᵀ=k∫[x̄(λ),ȳ(λ),z̄(λ)]ᵀs(λ)dλ" }),
        b(48, "XYZ 是所有标准色彩空间之间的设备无关桥梁", "公式页收束为三条标准化意义。", ["任何人类三刺激基都与 S/M/L 通过可逆线性变换相关；标准定义的是匹配函数和观察条件。已知 RGB 空间通常先线性化，再用 3×3 矩阵转 XYZ。", "跨不同白点时还需要 chromatic adaptation；仅做矩阵而忽略 D65/D50 会产生系统性色偏。"], ["linear combinations of S/M/L", "standardized functions", "other spaces defined via XYZ"]),
        b(49, "xyY：归一化 X+Y+Z，把尺度与比例拆开", "XYZ 三刺激转成 x、y、z 公式。", ["令 T=X+Y+Z，x=X/T、y=Y/T、z=Z/T，所以 x+y+z=1，只需保存 x、y；再保留 Y 恢复亮度，形成 xyY。若 T=0（绝对黑），色度未定义。", "小写 y 是色度比例，大写 Y 才是 luminance；二者不能混写。"], ["normalize by sum", "z is redundant", "coordinates (x,y,Y)"], { formula: "x=X/T，y=Y/T，z=Z/T，T=X+Y+Z" }),
        b(50, "CIE xy 色度图：单色光形成光谱轨迹，两端由紫线连接", "归一化公式变成马蹄形 spectral locus。", ["每个单色 λ 的 XYZ 归一化为轨迹上一点；马蹄内部是可由可见 SPD 加性组合形成的色度。底部 purple line 不是单色光，而是长波红与短波紫的混合。", "图中的填色只是显示器可呈现的近似示意；屏幕无法画出其自身色域之外的真实色度。"], ["spectral locus", "wavelength labels", "purple line is nonspectral"]),
        b(51, "色域：三原色的非负加色只能覆盖色度三角形", "色度图加入典型/光谱 RGB 原色和三角形说明。", ["两原色混合落在线段上，三原色非负凸组合落在三角形内；三角外目标需要负通道，因此该设备不能直接产生。更纯的 spectral primaries 可扩张三角形，却仍无法用三点覆盖弯曲的全部可见域。", "打印机的可达集合更复杂、依赖亮度与介质，不能只用一个加色三角形完整描述。"], ["primary chromaticities", "convex triangle", "monitors/printers cannot produce all visible colors"]),
        b(52, "彩色色度图：用真实外观近似帮助定位，但不要从屏幕颜色读数", "线框 gamut 图换成常见彩色 CIE 图。", ["它适合直观观察白点、光谱轨迹和多个标准色域的位置关系。靠近边界通常更高纯度，向白点移动更不饱和。", "由于整张图最终仍通过你的显示器 sRGB/P3 显示，超色域区域已被替换；坐标与边界可信，填色不是真实参考。"], ["white region", "hue directions", "display-clipped illustration"], { pause: "给两个 xy 原色点和一个混合权重，证明结果落在线段上；再说明为什么把图像位深从 8 提到 16 bit 不会让三角形变大。" }),
      ],
      checkpoint: "实现 ColorSpace Explorer：输入 SPD 得 XYZ/xyY，绘制光谱轨迹、D65 和 sRGB 三角形；将 XYZ 转线性 sRGB，标记负值/超 1 通道，并比较 clipping、缩放饱和度和感知色域映射。",
    },
    {
      id: "perceptual-color-coordinates",
      title: "更符合使用习惯的坐标：色相、对立通道、HSV 与 Lab",
      pages: "53-61",
      purpose: "从艺术家的 tint/shade/tone 进入感知维度和 afterimage，再区分 RGB 派生选择器与近似感知均匀空间。",
      beats: [
        b(53, "艺术家的组织法：纯色加白、黑或灰形成 tint、shade、tone", "色度图转成白—纯色—黑的二维关系图。", ["tint 是与白混合，shade 是与黑混合，tone 是降低鲜艳度的灰混合；这些词把‘同一种色相’的明暗和饱和变化组织在一起。", "颜料混合在物理上是减色且非线性，图只是感知/创作关系，不应直接当 RGB 线性插值定律。"], ["tints", "shades", "tones and grays"]),
        b(54, "三个感知维度：hue、saturation、lightness/value", "艺术家关系图换成三项定义与色度学对应。", ["Hue 回答哪一类颜色，常与主波长相关；saturation 回答离中性有多远，关联 purity；lightness/value 回答相对明暗，关联但不等同 luminance。", "这些对应只是近似。相同 XYZ 在不同背景与适应状态下可能有不同外观，颜色外观模型还需观察条件。"], ["hue", "saturation", "lightness or value"]),
        b(55, "在色度平面上，色相像方向，饱和度像离白点距离", "三项定义配上 xy 图和从白点出发的极坐标类比。", ["固定 Y 后，从参考白点出发的方向近似 hue，距离近似 saturation；Y 单独承担 luminance/lightness 轴。", "CIE xy 不感知均匀：相同几何距离在不同区域不代表相同可见色差，因此这只是直觉图，不是精确 H/S 度量。"], ["white as origin", "angle-like hue", "radius-like saturation"]),
        b(56, "对立颜色理论：早期神经编码重组为明暗、红绿、黄蓝", "色度几何换成 opponent axes 的文字证据。", ["视觉系统把锥体信号重组为近似 white–black、red–green、yellow–blue 通道。对立轴解释了为何可感到黄红或蓝绿，却没有同时强烈的‘红绿色’或‘黄蓝色’。", "对立通道不是说红光与绿光不能物理叠加；叠加可产生黄色 metamer，陈述的是感知坐标的组织。"], ["white–black", "red–green", "yellow–blue"]),
        b(57, "余像实验动画 1：盯住中心黑点，让四块颜色适应", "文字证据换成黄、红、绿、蓝四块和中央注视点。", ["保持目光约 20–30 秒，尽量不移动，然后切到下一页灰底。各局部视锥/对立通道对持续刺激适应，刺激移除后暂时产生互补方向的 afterimage。", "这是交互实验页：若只是快速滚过不会看到效果；避免长时间强光或不适。"], ["fixation dot", "four saturated fields", "prepare complementary afterimage"]),
        b(58, "余像实验动画 2：课件变成空白灰场，让视觉系统补出互补色", "上一页所有色块与黑点消失，只剩均匀浅灰。", ["相邻页故意几乎空白，不是缺图。保持注视原中心位置，通常会短暂看到黄↔蓝、红↔青绿方向的互补余像。", "余像证明颜色外观取决于先前刺激和适应状态；同一个灰色物理像素在不同历史后可产生不同感觉。"], ["intentional blank gray field", "complementary afterimage", "temporal adaptation"]),
        b(59, "RGB 作为三维空间：有限通道范围形成一个立方体", "余像实验结束，换成 RGB cube。", ["若每个线性或编码通道归一化到 [0,1]，所有数值三元组组成单位立方体；黑白在主对角线，三原色/二次色在角点。", "立方体几何取决于 RGB 定义和编码；sRGB 码值中的直线不一定是线性光混合，也不一定是感知均匀路径。"], ["RGB cube", "neutral diagonal", "gamut in coordinate space"]),
        b(60, "HSV：把 RGB 立方体重参数化成适合选色的角度、半径与高度", "RGB cube 展开为 HSV 六角锥/分层图。", ["Hue 0–360° 绕最大通道区域旋转，S 0–1 从灰轴向外，V=max(R,G,B)。每个水平切片是 RGB 子立方体的表面，因此 HSV 与特定 RGB 一一换算，不增加色域或物理信息。", "V 不是 luminance，HSV 距离也不代表可见色差；它适合 UI 选色，不适合光照计算、颜色管理或质量测量。"], ["hue angle", "saturation", "value equals max channel"], { textbook: book("教材第 19 章", "19.2.2 色彩与 HSV", "/book/19/", "教材从亮度、饱和度、色相的主观维度解释 HSV，并强调它只是 RGB 的重参数化，未捕获颜色恒常和上下文。") }),
        b(61, "Luv 与 Lab：用非线性和参考白近似感知均匀", "HSV 结尾转向 CIE 标准的 L*u*v*、L*a*b*。", ["目标是坐标中的相等差值更接近相等可见差异。L* 表示感知明度，Lab 的 a* 近似红↔绿、b* 近似黄↔蓝；非线性响应和参考白是关键。", "均匀只是近似，简单 ΔE*ab 在大色差/不同区域并不完美；实际还可用 CIEDE2000。Lab 转换必须声明参考白，sRGB→Lab 流程是解码→线性 RGB→XYZ→必要的白点适应→Lab。"], ["perceptually uniform goal", "Luv and Lab", "gamma-like nonlinear component"], { textbook: book("教材第 18 章", "18.2.4 CIE 1976 L*a*b*", "/book/18/", "教材给出参考白、L*/a*/b* 对立通道与 ΔE*ab，并把 Lab 定位为近似感知均匀的色差空间。"), formula: "ΔE*ab=√[(ΔL*)²+(Δa*)²+(Δb*)²]", pause: "列出把一个 sRGB 字节颜色转换为 Lab 的完整步骤，并指出哪一步需要 D65/D50 白点信息。" }),
      ],
      checkpoint: "制作 Color Picker Audit：同一组颜色同时显示 sRGB、线性 RGB、HSV、XYZ、xyY 与 Lab；沿 HSV 等步长和 Lab 等 ΔE 路径采样，比较可见差异。加入第 57–58 页余像引导并明确它是适应演示。",
    },
  ],
  synthesis: [
    "物理层：SPD s(λ) 描述每个波长的功率；颜色不是 SPD 的同义词，而是观察者对光谱刺激的感觉。",
    "测量层：探测器读数是 ∫sr；规则采样后成为点积。三类视锥把同一光谱投影成 S/M/L 三刺激。",
    "信息层：n 维光谱压成三数必然有零空间；不同 SPD 可产生相同响应成为异谱同色，这让三原色重现成为可能，也让光谱无法由 RGB 恢复。",
    "光度层：luminance 用 V(λ) 对 SPD 加权，是标准观察者的物理光度量；brightness/lightness 是受环境影响的主观外观。",
    "设备层：显示器以原色 SPD 的线性组合产生 metamer；RGB→视觉响应是 3×3 矩阵，求逆后还必须检查非负范围与色域。",
    "材料层：表面反射 SPD=e(λ)ρ(λ)，减色滤片/颜料按波长吸收并近似相乘，不等于加色 RGB。",
    "标准层：XYZ 是设备无关桥梁，Y 承担 luminance；xyY 用归一化分离色度和亮度，光谱轨迹与紫线界定可见色度。",
    "色域层：加色三原色只能覆盖色度三角形；超色域是物理原色限制，不能靠更高位深解决，只能改变设备或映射目标。",
    "坐标层：sRGB 是带传递函数的交换编码，HSV 是 RGB 选择器重参数化，Lab/Luv 近似感知均匀；任务不同，不能互相替代。",
    "感知层：对立通道、余像和颜色适应说明外观依赖观察历史与环境；色度学预测匹配，不是完整颜色外观模型。",
  ],
  finalPractice: "实现 ColorScienceLab：允许绘制 SPD、探测器/视锥/XYZ 响应并数值积分；显示 S/M/L、XYZ、xyY、线性 sRGB、编码 sRGB、HSV 和 Lab。载入三条显示原色 SPD 后构建颜色匹配矩阵，对目标光谱求 RGB，标出负通道和超 1 通道并提供三种色域处理。加入 illuminant×reflectance、metamer 搜索、CIE xy 图、原色三角形、D65 白点和 afterimage 实验。测试至少覆盖：积分与离散点积一致、整体缩放不改 xy、异谱 SPD 的 XYZ 匹配、RGB↔XYZ 矩阵往返、sRGB 编解码、黑色 T=0 色度未定义、三原色凸组合落在三角形、超色域不能由位深修复、HSV 的 V 不等于 Y，以及 Lab 转换使用正确参考白。",
};
