import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const compositing: DetailedLectureTutorial = {
  pdf: "24compositing.pdf",
  pageCount: 38,
  estimatedTime: "约 3.5 小时（含遮罩、预乘 Alpha 与 Porter–Duff 推导练习）",
  question: "一个像素里同时有前景、背景和部分覆盖时，怎样保存颜色与 Alpha，才能让多层图像无论先合成哪两层都得到相同结果？",
  opening: [
    "上一讲把像素看作有面积的滤波区域；这一讲继续追问：若这个区域只被前景覆盖一部分，剩余部分应该怎样与背景结合？答案不是简单保存一张黑白剪影，而是让每个像素携带颜色和覆盖信息，并定义可重复组合的代数。",
    "课件从电影特效和淡入淡出进入二值遮罩，再用头发边缘说明连续 Alpha 的必要性。真正的转折发生在多层合成：直通颜色不便于分组，而预乘 Alpha 把颜色和覆盖贡献绑定，令 over 同时对颜色和 Alpha 使用同一结构，并自然获得结合律。",
    "阅读公式时默认 RGB 是线性光值。sRGB 等非线性码值应先解码；完成滤波与合成后再编码。否则 50% 混合会在物理亮度上偏暗。",
  ],
  outcomes: [
    "区分 crossfade、二值 mask、coverage alpha 与材料 opacity",
    "写出直通与预乘两种 RGBA 表示及安全互换条件",
    "推导 A over B 的颜色和 Alpha，并说明 over 结合但不交换",
    "逐行验证三层预乘合成的颜色与 Alpha 结合律",
    "解释独立覆盖假设，以及正/负相关为何产生前景过多或过少",
    "用 Porter–Duff 的源/目标因子描述 over、in、out、atop、xor 等操作",
    "在正确线性颜色空间中实现、测试和排查透明边缘色带",
  ],
  runningExample: {
    title: "贯穿例子：把带细发丝的人像放到建筑前，再叠一层字幕",
    description: "先用二值遮罩观察锯齿，再把每个边缘像素解释为覆盖比例；随后分别以直通和预乘 RGBA 合成人像、建筑与字幕，验证不同括号顺序，并用相关覆盖反例检查模型边界。",
    code: "// 线性光、预乘 RGBA\nout.rgb = A.rgb + (1 - A.a) * B.rgb\nout.a   = A.a   + (1 - A.a) * B.a\n// 仅在 out.a > 0 时：straight.rgb = out.rgb / out.a",
  },
  chapters: [
    {
      id: "from-crossfade-to-mask",
      title: "先把两幅图混起来：crossfade 为什么还不是合成",
      pages: "1-10",
      purpose: "从像素覆盖的课程衔接、电影特效和全局淡入淡出，走到需要逐像素遮罩的问题。",
      beats: [
        b(1, "图像合成：把多个来源解释为同一个像素", "标题页给出 Lecture 24。", "Compositing 不是把文件叠在一起，而是为输出像素决定各输入层贡献多少。后面的每个公式都在回答两个问题：贡献权重从哪里来，以及合成结果能否继续作为一层参与下一次合成。", ["Compositing", "CS4620 Lecture 24", "PDF 共 38 个物理页"]),
        b(2, "像素覆盖连接抗锯齿与合成", "标题页加入 Pixel coverage 的课程定位。", ["抗锯齿在单幅连续图像内部平均不可解析细节；合成则保留各层的覆盖/透明信息，等到与其他层结合时再决定最终颜色。", "二者共享同一个像素面积模型：边界像素既不是纯前景，也不是纯背景。"], ["antialiasing: carefully throw away", "compositing: account when combining", "unresolved detail"]),
        b(3, "电影特效的真实动机：镜头由许多来源建成", "抽象课程定位换成 Titanic 的实拍、模型、海面与最终镜头拼图。", ["绿幕人物、缩尺模型、数字海水、烟雾和调色可能来自不同拍摄或渲染流程。每一层除 RGB 外还要携带‘此处属于我多少’的信息。", "合成系统必须允许艺术家反复重排和分组图层，因此结合律会从数学性质变成生产需求。"], ["Digital Domain / Titanic", "多个素材来源", "最终结果隐藏了层边界"]),
        b(4, "Crossfade 动画 1：t=0 时只看见 B", "电影案例切到 A、B 和混合结果，并写出全局线性插值。", ["公式 C=tA+(1-t)B 对整幅图使用同一个 t。t=0 时 A 权重为 0，结果等于 B；它适合镜头转场，却无法让一个像素选前景、另一个像素选背景。", "A、B、C 的 RGB 必须先处在线性光空间；直接平均 sRGB 字节会让中间帧偏暗。"], ["t=0", "C=tA+(1-t)B", "同一个 t 用于所有像素"], { formula: "C=tA+(1-t)B，0≤t≤1", textbook: book("教材第 3 章", "3.2.2 Gamma 与 3.4 Alpha 合成", "/book/3/", "教材同时提供线性光计算前提和覆盖率混合公式；两者结合才能得到正确的数值与外观。") }),
        b(5, "Crossfade 动画 2：t=0.3，A 开始全局显现", "上一页只改变 t，从 0 增至 0.3。", "相邻页不是新的算法：A 的每个像素统一获得 30% 权重，B 获得 70%。物体边界没有独立遮罩，所以两幅完整画面都像半透明幽灵一样存在。", ["t=0.3", "A 全图同步变亮", "B 全图同步变淡"]),
        b(6, "Crossfade 动画 3：t=0.6，主导图像交换", "t 从 0.3 增至 0.6。", "当 t 穿过 0.5，A 的贡献超过 B；每个通道仍按同一个凸组合计算。检查 t 与 1-t 权重和为 1，常量亮度才不会因混合本身任意增减。", ["t=0.6", "A 权重 60%", "权重和始终为 1"]),
        b(7, "Crossfade 动画 4：t=0.8，B 只留下微弱痕迹", "t 从 0.6 增至 0.8。", "B 仍贡献 20%，因此不会突然消失。crossfade 的连续性来自 t 连续变化；但它只有一个全局自由度，仍不能表达人物内部 α=1、外部 α=0、发丝边缘介于两者之间。", ["t=0.8", "B 仍有 20%", "无法表达空间变化"]),
        b(8, "Crossfade 动画 5：t=1，结果完全等于 A", "序列最终把 t 推到 1。", "此时 B 权重为 0。第 4→8 页完整展示的是时间插值，而不是空间遮罩；把标量 t 换成每像素 α(x,y)，才进入真正的前景/背景合成。", ["t=1", "C=A", "从 temporal blend 过渡到 per-pixel alpha"], { pause: "若希望只保留 A 中的人物、其余显示 B，为什么任何单一 t 都做不到？画出你希望的 α(x,y) 分布。" }),
        b(9, "前景与背景来自不同拍摄阶段", "淡入淡出序列换成 foreground/background production。", ["前景演员在便于分离的环境中拍摄，背景可来自实景、模型或渲染。任务不是让两幅图同时半透明，而是沿人物轮廓逐像素选择或混合。", "这种选择信息可以由色键、分割、深度、几何覆盖或人工 rotoscope 产生；课件先把它抽象成 mask。"], ["foreground", "background", "production pipeline"]),
        b(10, "位置相关的混合权重：遮罩成为第三个输入", "同一生产问题强调每个位置要分别决定前景或背景。", "现在权重不再是时间标量 t，而是二维函数 αA(x,y)。输出每个像素都读取前景 A、背景 B 和遮罩 αA；下一页先从只有 0/1 的最简单遮罩开始。", ["use foreground here", "use background there", "需要 tag/mask"]),
      ],
      checkpoint: "在线性 RGB 中实现 t=0、0.3、0.6、0.8、1 的 crossfade，再改为可绘制的 α(x,y)；证明标量 t 只能做全局转场，而空间 Alpha 能独立控制人物内部、外部和边界。",
    },
    {
      id: "alpha-and-partial-coverage",
      title: "从二值剪影到连续 Alpha：边界像素到底保存什么",
      pages: "11-19",
      purpose: "用同一人像的逐帧叠加暴露二值遮罩锯齿，并建立 coverage Alpha 与直通颜色公式。",
      beats: [
        b(11, "二值遮罩动画 1：一个 bit 只能说前景或背景", "前景/背景示意变成女人原图和黑白剪影。", ["白色可代表取 A，黑色代表取 B；一位遮罩存储便宜、判断明确，却把每个像素强迫成 0 或 1。", "真实轮廓穿过像素面积时，头发、斜边和细小孔洞都需要中间覆盖率；二值化会把这些信息量化成锯齿。"], ["one bit per pixel", "hard silhouette", "jaggies"], { textbook: book("教材第 3 章", "3.4 Alpha 合成", "/book/3/", "教材从子像素覆盖和透明对象出发，把 Alpha 定义为前景覆盖像素的比例。") }),
        b(12, "二值遮罩动画 2：把硬剪影真正贴到建筑背景", "上一页右侧新增按黑白遮罩得到的合成结果。", "相邻页变化是应用 mask，而非改变 mask。人物内部复制前景，外部复制背景；边界仍是全有或全无，所以合成后轮廓台阶直接暴露在高对比背景上。", ["新增 building composite", "内部 A、外部 B", "硬边缘仍在"]),
        b(13, "二值遮罩动画 3：放大发丝边界，锯齿无法再隐藏", "合成图旁新增头发边缘放大框。", ["放大图把物理像素的台阶和丢失的细发丝显示出来。这不是背景图分辨率的问题，而是遮罩只保留一个 bit。", "后处理模糊硬 mask 会生成中间值，却未必等于真实几何覆盖；更可靠的 Alpha 应在抠像、渲染或高质量过滤阶段产生。"], ["相邻页新增 zoom", "hair edge staircase", "信息在二值化时已丢失"]),
        b(14, "部分覆盖：边界像素同时包含 A 与 B 的面积", "人像例子切到几何边界穿越像素网格的示意。", ["像素不是一个点。若前景覆盖其中 αA 的面积，剩余 1-αA 由背景可见；在线性光和均匀 box filter 下，像素平均自然成为两者的面积加权和。", "这里的 Alpha 首先是 coverage。材料的物理透射率也常被塞进同一个 α，但 coverage 与 opacity 是不同成因；简单 RGBA 会把它们压成一个有效权重。"], ["boundary pixel not strictly foreground/background", "α 是面积比例", "interpolate by coverage"], { formula: "c_E=α_Ac_A+(1-α_A)c_B" }),
        b(15, "Alpha compositing：把覆盖率作为第四个通道", "覆盖直觉被写成 Porter–Duff 1984 的 A over B 公式。", ["A over B 表示 A 在前、B 在后。若 B 是不透明远背景，输出 RGB 为 αA cA+(1-αA)cB；常见 8-bit RGBA 因四个通道各 8 位而占 32 bit。", "这里 cA 是未乘 Alpha 的 straight/unassociated 颜色。它描述‘若完全覆盖时 A 是什么颜色’，并不等于当前像素已经贡献的光。"], ["Porter and Duff 1984", "A over B", "32 bits per pixel"]),
        b(16, "反 Alpha 记号：把剩余可见比例写成 ā", "公式被压缩为 bar-alpha 记号。", "定义 āA=1-αA 后，cE=αA cA+āA cB。记号看似只少写几个字符，但后面三层展开会反复出现 āAāB，它直接表示同时没有被 A、B 覆盖的比例。", ["ā=1-α", "foreground contribution", "remaining background contribution"], { formula: "\u0305α_A=1-α_A，c_E=α_Ac_A+\u0305α_Ac_B" }),
        b(17, "连续 Alpha 动画 1：软遮罩记录发丝与边界覆盖", "硬剪影换成灰度 Alpha matte；人物 RGB 外部为黑。", ["白色 α≈1、黑色 α≈0、灰色介于两者。发丝周围的灰度不是装饰性模糊，而是亚像素覆盖/抠像置信度和半透明贡献的编码。", "右侧 RGB 外部近黑已呈现预乘数据常见外观，但此处先只把 Alpha 当连续 mask 阅读。"], ["soft grayscale matte", "hair has intermediate alpha", "RGB 与 Alpha 是配对数据"]),
        b(18, "连续 Alpha 动画 2：在建筑上得到柔和轮廓", "上一页新增软 Alpha 合成结果。", "相邻页只应用了连续遮罩。边缘像素按比例同时含人物和建筑，不再在 0/1 间跳变；发丝附近也保留细小、低 Alpha 的贡献。", ["新增 soft composite", "建筑透过低 Alpha 区", "边界过渡连续"]),
        b(19, "连续 Alpha 动画 3：放大验证平滑边缘，并警惕色边", "合成图旁新增同一区域放大框。", ["与第 13 页相比，轮廓由多级颜色渐变组成，台阶对比显著降低。若放大时出现黑/白光晕，通常是 straight 与 premultiplied 数据解释错、透明像素藏有任意 RGB，或在 sRGB 空间过滤。", "正确诊断要同时检查 Alpha、RGB 是否已预乘、滤波空间和背景假设，不能只‘再羽化一次’。"], ["相邻页新增 zoom", "smooth hair edge", "halo 是表示/过滤错误信号"], { pause: "取一个 α=0.25、前景线性红 cA=(1,0,0)、背景白 cB=(1,1,1) 的像素，算出 cE；再说明为什么 sRGB 字节直接混合不等价。" }),
      ],
      checkpoint: "用同一高对比斜边生成二值 mask 与 4×4 coverage Alpha，合成到黑、白、彩色三种背景；放大比较台阶，并显示每个边缘像素的 α、straight RGB 和最终线性 RGB。",
    },
    {
      id: "premultiplied-alpha",
      title: "多层合成迫使我们改变表示：从直通颜色到预乘颜色",
      pages: "20-28",
      purpose: "展开三层 over，推导合成 Alpha，指出直通表示的除法，再得到预乘 RGBA 的闭合公式。",
      beats: [
        b(20, "多层合成的工程要求：分组不能改变画面", "单次人像合成变成 n-layer composites 与结合律目标。", ["真实项目有许多层。缓存 B over C、把 A 单独留给后续，或先合成 A over B，都应得到相同像素：A over (B over C)=(A over B) over C。", "这要求合成结果拥有与输入相同、信息足够的 RGBA 表示。仅保存最终 RGB 会丢掉‘还剩多少背景可见’。"], ["real applications have n layers", "associativity", "composite must itself be compositable"]),
        b(21, "三层推导动画 1：先展开 A over (B over C)", "文字目标换成 A、B、C 三形状和颜色展开式。", ["先算 B over C，再让 A 覆盖它：cD=αA cA+āA[αB cB+āB cC]。展开后出现三项，分别对应 A、A 未覆盖处的 B、A/B 都未覆盖处的 C。", "这一页先给代数结果，后面三页用像素覆盖图给每个系数几何意义。"], ["αA cA", "āA αB cB", "āA āB cC"], { formula: "c_D=α_Ac_A+\u0305α_Aα_Bc_B+\u0305α_A\u0305α_Bc_C" }),
        b(22, "三层推导动画 2：新增像素格，把系数解释为面积", "上一页下方新增 A、B 边界穿过像素的网格。", "相邻页没有改公式，而是把 αA、αB 从抽象数变回覆盖面积。一个像素内可以分成被 A 覆盖、未被 A 但被 B 覆盖，以及二者都未覆盖的区域。", ["新增 pixel-grid coverage", "公式三项对应区域", "C 只在前两层都缺席时出现"]),
        b(23, "三层推导动画 3：新增区域图例，逐块对应 A、B、C", "网格旁新增着色区域和图例。", ["A 区直接贡献；B 只有落在 A 空隙中的部分贡献；C 只有落在 A 与 B 共同空隙中的部分贡献。", "若把 α 当面积概率，āAαB 与 āAāB 是乘法概率；这种乘法已经隐含 A、B 覆盖在子像素尺度独立，后面第 35 页会审查这个假设。"], ["相邻页新增 region legend", "A first, then B, then C", "面积乘法隐含独立性"]),
        b(24, "三层推导动画 4：突出 āAāB，得到合成层的 Alpha", "区域图强调既非 A 也非 B 的最后一块。", ["A over B 仍未覆盖的比例是 āAāB，所以它的 Alpha 满足 āE=āAāB，即 αE=1-āAāB=αA+āAαB。", "这是让 composite 继续参与下一次 over 所缺的第四通道。它与颜色不同：Alpha 表示总覆盖，不携带颜色。"], ["相邻页突出 neither A nor B", "composite complement multiplies", "derive output alpha"], { formula: "α_E=1-\u0305α_A\u0305α_B=α_A+(1-α_A)α_B" }),
        b(25, "直通 Alpha 的麻烦：输出颜色必须再除以输出 Alpha", "几何解释切回 associativity 代数，并尝试把 A over B 先分组。", ["若 cE 仍要保存为 straight color，就必须满足 αE cE=αA cA+āA αB cB，因此 cE=(αA cA+āA αB cB)/αE（αE>0）。不做归一化会把‘颜色’和‘已贡献颜色’混为一谈。", "αE=0 时 cE 没有可见意义，除法也未定义；透明像素的 straight RGB 可以是任意值，这会在插值和过滤时埋下色边。"], ["straight color grouping is awkward", "requires division", "α=0 is undefined for unpremultiply"], { formula: "c_E=(α_Ac_A+(1-α_A)α_Bc_B)/α_E，仅当 α_E>0" }),
        b(26, "改进：把 Alpha 先乘进颜色", "直通推导改写为 c′=αc，并简化 over。", ["定义 associated/premultiplied color c′=αc。前景已经携带自己的有效贡献，合成只需 c′E=c′A+āA c′B；输出 Alpha 使用完全相同结构。", "转换 straight→premult 永远可做；premult→straight 只在 α>0 时除法。完全透明的合法 premult RGB 必须为 0，这使插值、缩放和模糊不会把隐藏颜色漏进边缘。"], ["c′=αc", "no division in over", "transparent premult RGB is zero"], { formula: "c′=αc；c′_E=c′_A+(1-α_A)c′_B" }),
        b(27, "预乘 Alpha 的存储外观：RGB 与 Alpha 一起淡向零", "公式页换成女人的预乘 RGB 与灰度 Alpha。", ["在低 Alpha 发丝和透明外部，预乘 RGB 同步变暗；这不是丢失亮度，而是保存该层对像素已经贡献的线性光。合成到背景时剩余部分由背景项补上。", "不要把预乘 RGB 单独当普通照片显示，也不要重复乘 Alpha；前者看起来有黑边，后者会把边界权重平方。"], ["premultiplied color", "Alpha matte", "RGB outside is black by invariant"]),
        b(28, "预乘 RGBA 对 over 闭合：颜色与 Alpha 共用一条规则", "人像示意回到 A over B 的二元运算公式。", ["结果 (c′E,αE)=(c′A+āA c′B, αA+āA αB)。输入和输出类型相同，没有中间除法，所以 composite 可直接作为下一层输入。", "若 B 是不透明远背景，αB=1，则 αE=1；这解释了前半课件省略背景 Alpha 的特殊情况。over 有结合律，但 A over B 通常不等于 B over A，层次顺序仍然重要。"], ["premultiplied pair", "treat alpha like colors", "associative, not commutative"], { formula: "(c′_E,α_E)=(c′_A+(1-α_A)c′_B, α_A+(1-α_A)α_B)", pause: "给 A=(c′=(0.5,0,0), α=0.5)、B=(c′=(0,0,1), α=1)，算 A over B 和 B over A，验证不交换。" }),
      ],
      checkpoint: "实现 straight↔premult 转换和 A over B；随机生成一万组合法 premult RGBA，验证输出满足 0≤c′≤α（非负归一化颜色时）、α 范围正确、透明 RGB 为零，并展示错误地重复乘 Alpha 造成的黑边。",
    },
    {
      id: "associativity-proof",
      title: "逐帧完成结合律证明：为什么预乘 over 可以任意分组",
      pages: "29-34",
      purpose: "按课件动画顺序分别展开左右两种括号的颜色和 Alpha，再用仿射矩阵解释结构。",
      beats: [
        b(29, "结合律证明动画 1：先并列两种括号，不急着填答案", "公式页换成 A over (B over C) 与 (A over B) over C 两个相同结果图，推导区留白。", ["目标是证明每个像素的 premult RGB 和 Alpha 都相等。两幅示意图外观相同不能代替证明；接下来四页会依次补左颜色、右颜色、左 Alpha、右 Alpha。", "使用 āA=1-αA，并记住合成层的反 Alpha：over(A,B) 的 complement 是 āAāB。"], ["left/right grouping", "color rows blank", "alpha rows blank"]),
        b(30, "结合律证明动画 2：填入左分组的颜色展开", "左侧 color 行新增两步代数，右侧仍空。", "A over (B over C) 的颜色为 c′A+āA[c′B+āB c′C]，分配后得到 c′A+āA c′B+āAāB c′C。三层贡献按从前到后依次乘过所有前层的空余比例。", ["相邻页只新增 left color", "distribute āA", "three ordered contributions"], { formula: "c′_{A over (B over C)}=c′_A+\u0305α_Ac′_B+\u0305α_A\u0305α_Bc′_C" }),
        b(31, "结合律证明动画 3：填入右分组颜色，得到同一三项", "右侧 color 行新增 (A over B) 再 over C 的展开。", ["先合成 A、B 得 c′A+āA c′B；这层的剩余比例是 āAāB，所以 C 项为 āAāB c′C。展开与第 30 页逐项相同。", "这里正是预乘表示的优势：若保存 straight color，中间层还要除以 αAB，随后再次乘回，证明更绕且 α=0 要分支。"], ["相邻页新增 right color", "composite complement=āAāB", "color equality complete"]),
        b(32, "结合律证明动画 4：填入左分组 Alpha", "颜色两侧已完成，左侧 alpha 行新增展开。", "Alpha 像一个值为 1 的预乘通道参与同样的 over：αA+āA[αB+āBαC]=αA+āAαB+āAāBαC。每项表示这一层在更前层均未覆盖处新增的覆盖。", ["相邻页只新增 left alpha", "same recurrence as color", "ordered coverage terms"], { formula: "α_{A over (B over C)}=α_A+\u0305α_Aα_B+\u0305α_A\u0305α_Bα_C" }),
        b(33, "结合律证明动画 5：填入右分组 Alpha，证明完成", "最后补上右侧 alpha 行。", "先得 αAB=αA+āAαB，且 āAB=āAāB；再 over C 得 [αA+āAαB]+āAāBαC，与左侧完全相同。颜色和 Alpha 都相等，因此预乘 over 具有结合律。", ["相邻页新增 right alpha", "both rows match", "associativity proof final frame"], { pause: "不用看课件，独立从 over 二元式写出四层 A over B over C over D 的 c′ 展开，并指出 D 前面的系数。" }),
        b(34, "合成代数：over 是一个仿射变换的复合", "逐行展开被收束成 2×2 上三角矩阵/仿射形式。", ["一层 A 对后方颜色 x 的作用是 x↦c′A+āA x。把它写成齐次矩阵后，多层 over 就是矩阵乘法；矩阵乘法结合，因此 over 的结合律不再是偶然展开。", "顺序仍不能交换：两个仿射矩阵一般 AB≠BA。这个视角也适合把整段前景层预合成为单个 color/alpha 对。"], ["multiply/add affine transform", "matrix multiplication", "associative but ordered"], { formula: "T_A(x)=c′_A+\u0305α_Ax；T_A∘T_B∘T_C 的分组不改变结果" }),
      ],
      checkpoint: "为随机 A、B、C 计算两种括号的 premult RGB/Alpha，报告浮点误差；再故意用错误的 straight 公式或省略 αB，找出最小反例。最后把每层写成仿射矩阵，验证矩阵乘积与逐层 over 一致。",
    },
    {
      id: "coverage-assumptions-and-operators",
      title: "公式的边界：独立覆盖假设、相关性失败与 12 种 Porter–Duff 运算",
      pages: "35-38",
      purpose: "解释为何 Alpha 像颜色一样混合并非无条件真理，最后把 over 放进完整的二元合成代数。",
      beats: [
        b(35, "独立覆盖假设：为什么两层空隙比例可以直接相乘", "矩阵证明转向像素内 A/B 覆盖的概率表。", ["αAαB、αAāB、āAαB、āAāB 把像素面积分成四类，前提是 A 与 B 在子像素尺度的覆盖位置独立/不相关。于是交集面积等于边际面积乘积。", "单个 Alpha 只保存每层覆盖多少，不保存覆盖在哪里；若两层相关，仅凭 αA、αB 无法恢复真实交集，任何二元公式都缺少信息。"], ["independent coverage assumption", "four region probabilities", "marginals do not encode correlation"]),
        b(36, "何时近似成立：细碎交错覆盖；何时明显不成立：完全相关", "概率表换成三组子像素排列，标出 this / not this / or this。", ["若两层的微小覆盖像随机筛网般交错，面积乘积是合理近似。若两层边界完全重合（正相关）或互补咬合（负相关），同样的两个 Alpha 会产生完全不同的交集。", "提高 Alpha 位深不能解决这个信息缺失；需要更多样本、多通道 coverage、深度/几何信息或直接在更高分辨率合成后过滤。"], ["interleaved independent layout", "perfect positive correlation", "perfect negative correlation"]),
        b(37, "Alpha compositing 的失败案例：正相关前景过多，负相关前景过少", "抽象排列换成人像头发与蓝色形状的可见伪影。", ["正相关边界被独立公式当作额外互补覆盖，可能累积 too much foreground，轮廓变浓；负相关覆盖本应互补填满像素，却被相乘模型留下过多空隙，出现 too little foreground。", "这页不是说 Alpha 无用，而是标明模型粒度：在常规图层合成中高效稳定；在高度相关的几何边界、多重深度样本或复杂透明介质中可能需要更丰富表示。"], ["positive correlation", "too much foreground", "negative correlation", "too little foreground"]),
        b(38, "Porter–Duff 收束：over 只是 12 种合理二元选择之一", "失败案例切换到一般式和 12 个区域选择图标。", ["一般预乘形式 c′E=FA c′A+FB c′B；FA、FB 从 0、1、对方 Alpha 或对方反 Alpha 中按几何区域选择。除了 A over B，还有 B over A、in、out、atop、xor、源/目标和 clear。", "12 个经典操作来自对 A-only、B-only、A∩B 等区域的合理保留组合。实现时颜色和 Alpha 必须使用对应因子；明确源/目标顺序、预乘约定与线性空间，并用透明/不透明极端输入测试。"], ["c′E=FA c′A+FB c′B", "1×2×3×2=12 reasonable choices", "Porter–Duff table"], { formula: "c′_E=F_Ac′_A+F_Bc′_B；α_E=F_Aα_A+F_Bα_B", textbook: book("教材第 3 章", "3.4-3.4.1 Alpha 合成与图像存储", "/book/3/", "教材给出 RGBA、覆盖率混合和存储基础；本讲把它扩展成可结合的预乘表示与完整 Porter–Duff 运算。"), pause: "为 A over B、A in B、A out B、A xor B 分别写 FA、FB；再用 αA=0/1、αB=0/1 的四个角点检查几何含义。" }),
      ],
      checkpoint: "制作 Compositing Lab：用可编辑的 8×8 子像素 mask 构造独立、正相关和负相关覆盖，比较真实面积积分与单 Alpha 公式；再实现并可视化 12 个 Porter–Duff 操作，逐项验证源/目标交换后的对应关系。",
    },
  ],
  synthesis: [
    "像素层：边界像素是面积混合，不是前景/背景二选一；连续 Alpha 保存覆盖比例，二值 mask 会量化成锯齿。",
    "语义层：coverage、材料 opacity 和抠像置信度来源不同，普通 RGBA 把它们压成一个有效 Alpha，使用时要知道模型含义。",
    "颜色层：合成、插值和过滤应在线性光完成；sRGB 等显示编码只适合存储/传输和最终输出。",
    "表示层：straight color 保存未覆盖时的本色，premultiplied color 保存 c′=αc 的实际贡献；α=0 时只有后者有唯一合法 RGB=0。",
    "运算层：预乘 over 同时使用 c′E=c′A+āA c′B 与 αE=αA+āAαB，输出仍是同类型 RGBA。",
    "代数层：三层展开在两种括号下产生同样的有序贡献项，因此 over 结合；但前后顺序改变遮挡，所以不交换。",
    "假设层：āAāB 把边际覆盖相乘，隐含子像素独立性；强正/负相关时单 Alpha 无法编码真实交集。",
    "工具层：Porter–Duff 用源/目标因子选择各几何区域，over、in、out、atop、xor 等 12 种操作共享同一预乘框架。",
  ],
  finalPractice: "实现一个完整的 CompositingLab。载入三张带 Alpha 图层，允许切换 straight/premult 存储、线性/sRGB 运算、A over B 的左右括号顺序，并显示 RGB、Alpha、c′、背景剩余率。提供 t crossfade、binary/soft mask、12 个 Porter–Duff 运算和 8×8 子像素相关性编辑器。测试至少覆盖：t 五帧权重和为 1、半覆盖解析值、α=0 的安全处理、straight↔premult 往返、透明 premult RGB 为零、A over (B over C)≈(A over B) over C、A over B≠B over A、αB=1 时输出不透明、线性与 sRGB 混合差异，以及独立/正相关/负相关覆盖的真实交集误差。",
};
