import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const introduction: DetailedLectureTutorial = {
  pdf: "01intro.pdf",
  pageCount: 82,
  estimatedTime: "约 4.5 小时（含领域地图、案例拆解与学习路线设计）",
  question: "计算机图形学究竟研究什么；一张照片、一个字体、一部动画和一幅三维电影镜头为什么属于同一门学科？",
  opening: [
    "第一讲不是术语目录，而是在搭建整门课的坐标系。老师先把图形学分为 imaging、modeling、rendering、animation，再用大量几乎没有文字的案例训练你识别：数据是什么、操作是什么、结果为何需要计算。",
    "课件中的连续图片经常不是重复：黑白山景、全景拼接、抠像三帧、扫描到模型、牛奶和头发参数序列，都在用相邻页变化演示算法作用。另有五组页面在 PDF 中完全相同，说明原 Keynote 的视频没有被静态导出；教程会诚实说明能从冻结帧推断什么、不能还原什么。",
    "课程行政信息属于 2018 年历史记录；自学时保留它来理解七份作业、先修要求和项目节奏，但不把旧网址、TA 名单或迟交规则当作当前规定。",
  ],
  outcomes: [
    "用 imaging、modeling、rendering、animation 四类给实际案例分类",
    "区分图像、几何、材质、运动、相机和光照在图形系统中的职责",
    "从相邻案例帧推断拼接、抠像、体绘制、扫描、细分和参数控制",
    "解释二维/三维和输入/表示/生成并不是同一组分类轴",
    "把电影、游戏、CAD、VR/AR 和科研可视化拆成可学习的技术模块",
    "识别静态 PDF 丢失嵌入视频时的证据边界",
    "根据先修知识与七个项目制定可执行的自学顺序",
  ],
  runningExample: {
    title: "贯穿例子：拆解一帧有角色、雨水和相机运动的游戏画面",
    description: "Imaging 处理采集图像、纹理与后期；modeling 提供角色、城市和材质参数；animation 决定骨骼、布料与相机随时间的状态；rendering 根据几何、光、材质和相机生成像素。后文每遇到案例都把它放回这四栏，并标注输入与输出。",
    code: "scene = model(geometry, materials, lights, camera)\nstate_t = animate(scene, t)\nlinearImage = render(state_t)\nfinalImage = imageProcess(linearImage)",
  },
  chapters: [
    {
      id: "graphics-and-2d-imaging",
      title: "图形学的四块地图，以及二维成像如何把照片变成新图像",
      pages: "1-11",
      purpose: "定义领域并用颜色处理、全景拼接、遮罩与合成建立 imaging 的输入—输出直觉。",
      beats: [
        b(1, "课程从‘Introduction to Computer Graphics’开始", "标题页只给课程、教师与学期。", "这页限定对象：CS4620/5620 同堂，内容是创建、操作和使用视觉图像。先不要把 graphics 等同于某个 API；后续案例跨照片、字体、医学、电影、游戏和研究。", ["Lecture 1", "Prof. Steve Marschner", "Fall 2018"]),
        b(2, "定义中的三个动词：creating、manipulating、using", "标题页换成一句领域定义。", ["Creating 是从模型生成图像，manipulating 是把已有视觉数据变换成新数据，using 包含交互、表达和分析。", "定义同时容纳 computer vision 的部分边界，但本课主要关心表示和生成，而不是从图像自动识别世界。"], ["visual images", "in the computer", "不只 photorealistic rendering"]),
        b(3, "四象限地图：imaging、modeling、rendering、animation 都有 2D/3D", "一句定义展开成四类主题和例子。", ["Imaging 以图像/体数据为核心，modeling 定义形状与场景，rendering 把表示生成视觉结果，animation 让状态随时间变化。", "2D/3D 是空间维度；四类是任务。二维也需要 rendering，三维也有 imaging，不要把它们排成单一路线。"], ["四个主题", "每类都有 2D 与 3D", "同一项目常跨多类"]),
        b(4, "2D imaging 章节牌：接下来关注已有图像的处理", "主题总览切换到 2D imaging。", "这类任务的典型输入和输出都是二维像素数组，但操作可能依赖颜色、空间滤波、几何配准、遮罩或多图关系。", ["section divider", "image→image", "后续页以无公式案例建立动机"]),
        b(5, "成像案例 1：保留彩色山景作为基线", "章节牌换成 Alexandre Buisse 的彩色风景照。", "先记录原图的色相、局部对比和暖冷关系，下一页只改颜色表达。构图与几何不变能帮助我们把差异归因于 image processing。", ["snow and warm sunlight", "same spatial content", "color image baseline"]),
        b(6, "成像案例 2：同一山景变为黑白，颜色信息被重新投影", "上一页彩色照片变成黑白版本。", ["相邻页主要变化是颜色到亮度/色调的映射，不是重新建模山体。简单 RGB 平均通常不符合感知亮度，实际还会调局部对比和 tone curve。", "信息被丢弃后不能从单张灰度图唯一恢复原色。"], ["相同构图", "chromatic channels removed", "tonal contrast retained"], { textbook: book("教材第 3 章", "光栅图像、RGB 与 Gamma", "/book/3/", "教材解释像素通道、RGB 编码和非线性显示；它们是理解灰度转换与照片处理的数值基础。") }),
        b(7, "全景问题：不换广角镜头，能否得到更宽视场", "黑白处理切换到 Do I need a wide angle lens? 与一张湖景。", "老师在提出 imaging 的第二类任务：多幅窄视场照片能否配准并融合成全景。关键不是把单图横向拉伸，而是估计相机之间的几何关系。", ["wide field of view", "single-view baseline", "question prepares next page"]),
        b(8, "全景答案：多张重叠照片配准、投影并接缝融合", "单张湖景被拆成一扇重叠的竖幅照片。", ["相邻页揭示输入其实是一组照片。算法需检测/匹配特征，估计 homography 或相机旋转，重投影到共同曲面，再曝光补偿和 seam blending。", "视差较大或场景运动时，单一平面变换会失败。"], ["overlap between frames", "different orientations", "stitching pipeline"]),
        b(9, "抠像动画 1：先看待分离的前景人物", "全景组图换成黑底人物素材。", "这一帧建立 foreground A。头发和衣物边界使它成为比矩形裁剪更难的例子；下一页会显式给出 coverage/matte。", ["foreground plate", "fine hair boundary", "black display background is not necessarily alpha"]),
        b(10, "抠像动画 2：新增白色 Alpha matte", "人物照片换成白色剪影与灰色发丝边缘。", "相邻页把颜色与覆盖分开：白色近 α=1，黑色近 α=0，灰色是部分覆盖/不透明度。二值 mask 会造成锯齿，连续 Alpha 才能保留发丝。", ["新增 matte", "soft boundary", "per-pixel coverage"]),
        b(11, "抠像动画 3：用 matte 把人物放进新背景", "遮罩页新增/切换为人物与岩石背景的合成结果。", "最终像素按 Alpha 将前景与背景组合。若颜色已预乘，over 为 c′out=c′A+(1-αA)c′B；它说明 imaging 也需要严格的颜色表示与代数。", ["new background", "edge quality reveals matte quality", "three inputs: foreground, alpha, background"], { textbook: book("教材第 3 章", "3.4 Alpha 合成", "/book/3/", "教材用部分覆盖解释 Alpha；第 24 讲会进一步推导预乘表示与多层结合律。"), pause: "任选一张照片，写出全景拼接和抠像两条流程的输入、关键中间量、输出和一个失败条件。" }),
      ],
      checkpoint: "建立四栏课程地图，并实现两个最小 imaging 实验：线性光灰度转换、带软 Alpha 的 A over B。每个实验保留原输入和失败对照。",
    },
    {
      id: "2d-model-animation-render",
      title: "二维不等于简单：字体、动态图形、地图与艺术化渲染",
      pages: "12-24",
      purpose: "比较二维模型的可编辑表示、时间设计和从抽象数据生成最终像素的过程。",
      beats: [
        b(12, "2D modeling 章节牌：从像素转向可编辑结构", "抠像结果切换到 2D modeling。", "建模回答‘用什么参数描述对象’。二维模型可包含 Bézier 轮廓、字形、布局约束、图层、语义对象和 UI 状态，而不是固定像素。", ["section divider", "representation before rasterization", "editing and reuse"]),
        b(13, "字体设计：少量轮廓规则生成大量字形与字号", "章节牌换成 Fontsmith 的字样、数字与排版样张。", ["字体模型保存轮廓曲线、字宽、hinting 和字距关系；相同设计可在不同字号重新采样。", "图形学问题包括曲线表示、填充、抗锯齿和排版约束，而不仅是选择字体文件。"], ["letterform consistency", "numbers and weights", "vector outlines"]),
        b(14, "字形轮廓：控制点比最终像素更适合编辑", "排版成品换成带节点和手柄的单个 e 轮廓。", "图中节点/曲线是模型，屏幕黑白像素是之后 rasterization 的结果。编辑控制点能平滑改变轮廓，并在任意分辨率重绘。", ["Bezier control points", "closed contour", "model versus sampled image"]),
        b(15, "信息插画：几何、文字和层次被组织为可复用场景", "单字形换成 Glacier National Park 海报。", "海报由形状、图层、遮挡、文字和颜色关系组成；保持为结构化对象才能修改熊、徽章或版式，而不必逐像素重画。", ["layered vector shapes", "occlusion", "typography plus illustration"]),
        b(16, "2D animation 章节牌：模型开始依赖时间 t", "静态插画切换到 2D animation。", "动画可写成 state(t)：位置、形状、颜色、相机或图层在时间上变化。关键帧提供少量状态，插值/程序/模拟填充中间帧。", ["section divider", "time-varying state", "motion design"]),
        b(17, "动态图形案例：字体可以变形，而不只是平移", "章节牌换成 From Paper to Screen 的字母变形画面。", "同一轮廓模型随时间做形态过渡，要求点对应、曲线插值与节奏设计。截图只冻结一帧；原视频的时间连续性是关键数据。", ["letter morph", "shape correspondence", "embedded video link"]),
        b(18, "剪纸/灯光动画：简单形状也能靠层次和时间产生叙事", "字体变形换成 Traveling Lights 的平面几何画面。", "圆、矩形和建筑剪影通过位置、遮挡、发光与 timing 组合成场景。视觉复杂度不等于模型多边形数量；设计约束和时序同样重要。", ["flat shapes", "layered motion", "lighting-like 2D effects"]),
        b(19, "标题序列：排版、抽象图案、声音和剪辑同步", "简洁动画换成 FITC Tokyo 的高密度动态图形。", "动态图形把二维模型、程序生成、图像处理和动画混合。截图无法表达节拍，教程只能据来源说明应观察形状如何随音乐组织。", ["typographic motion", "procedural patterns", "temporal rhythm"]),
        b(20, "二维游戏 Fez：画面是 2D，但世界规则可以借用 3D", "动态图形切换到平台游戏截图。", "最终像素采用像素艺术，游戏却可通过视角切换组织空间。分类应看问题：精灵/UI 属于二维成像与渲染，关卡状态属于建模，角色移动属于动画。", ["pixel art", "interactive state", "multiple graphics topics in one system"]),
        b(21, "2D rendering 章节牌：从二维模型生成可显示图像", "游戏截图切换到 2D rendering。", "Rendering 不专属于三维。给定路径、笔刷、地图要素或精灵，系统仍需确定覆盖、颜色、层顺序、滤波和最终像素。", ["section divider", "model→pixels", "coverage and style"]),
        b(22, "数字水彩：渲染器可以模拟艺术材料而非现实相机", "章节牌换成 Adobe Eazel 的笔触与颜料实验。", "系统把触控轨迹、颜料浓度和纸张/水扩散模型转成像素。目标是可控的艺术效果，不一定是物理完全准确。", ["brush input", "pigment diffusion", "non-photorealistic rendering"]),
        b(23, "Google Maps：语义地图数据按缩放级别变成清晰画面", "艺术材料换成地图界面。", "道路、地点、标签和地形是结构化模型；渲染需选择可见要素、避免文字碰撞、按 zoom 调线宽并分块缓存。截图是复杂二维 scene graph 的结果。", ["semantic layers", "label placement", "multi-resolution tiles"]),
        b(24, "Limbo：二维轮廓、光影和层次可以构造强烈空间感", "地图界面换成黑白游戏场景。", "剪影、雾、光束、粒子和景深样式共同产生深度。非照片风格仍需严谨的 compositing、animation 和 rendering。", ["silhouettes", "layered lighting", "stylization over realism"], { textbook: book("教材第 9 章", "图形管线与光栅化", "/book/9/", "教材说明矢量/图元如何经变换、裁剪、覆盖和片元处理成为像素；二维渲染同样沿用这些概念。"), pause: "把 Google Maps 或 Limbo 任选其一，分别列出其模型数据、动画状态、渲染规则和成像后处理。" }),
      ],
      checkpoint: "制作一个可缩放二维场景：至少含 Bézier 字形、图层、动画参数和两种渲染风格。缩放时检查轮廓、文字、遮挡和抗锯齿。",
    },
    {
      id: "3d-imaging-and-modeling",
      title: "三维数据怎样被采集、显示并变成可计算模型",
      pages: "25-36",
      purpose: "用 CT/体数据、扫描、CAD、城市和细分角色区分 3D imaging 与 3D modeling。",
      beats: [
        b(25, "3D imaging 章节牌：数据在体积中，而非只在表面", "二维游戏切换到 3D imaging。", "三维成像的输入常是体素、切片、点云或随空间变化的标量场；任务是重建、分析或投影它们，而不一定先有三角网格。", ["section divider", "volumetric data", "measurement→visualization"]),
        b(26, "体数据案例 1：冻结的鱼类 CT 体绘制帧", "章节牌换成透明鱼骨的三维医学/科学图像。", "透过软组织看到骨骼说明像素整合了射线上多个体素，而不是只显示最近表面。传递函数决定不同密度的颜色与不透明度。", ["internal structure", "volume rendering", "opacity transfer function"]),
        b(27, "体数据案例 2：原 PDF 与第 26 页完全相同", "物理页前进，但导出的像素逐点一致。", "这很可能是 Keynote 中嵌入动画/旋转体数据的第二时间点，PDF 只冻结同一缩略帧。我们只能确认主题和单帧，不能声称相机或结构发生了静态可见变化。", ["exact duplicate in PDF", "likely embedded media", "evidence boundary"]),
        b(28, "同一 CT 的多种呈现：切片、平均、最大强度与体绘制", "鱼类体绘制换成脊柱 CT presentation 对照。", ["AIP 平均沿射线样本，MIP 取最大值，thin slice 只看窄层，volume rendering 以 transfer function 前后合成。", "同一体素数据因 projection operator 不同而强调不同结构；可视化不是唯一真相。"], ["average intensity projection", "maximum intensity projection", "thin slice versus volume rendering"]),
        b(29, "体数据案例 3：Velvet 纤维体数据冻结帧", "医学 CT 换成标注 Velvet 的白色纤维体图。", "这类显微体数据可显示内部纤维方向和密度。与医学 CT 相同，关键是采样、传递函数和视线积分。", ["fiber-like volume", "scientific imaging", "same rendering principles"]),
        b(30, "体数据案例 4：原 PDF 再次重复第 29 页", "物理页改变，但图像像素完全相同。", "原演示可能播放体数据旋转或参数变化；静态 PDF 没有保存。教程将其作为独立物理页展示并记录信息缺失。", ["exact duplicate", "animation not preserved", "do not invent delta"]),
        b(31, "3D modeling 章节牌：从测量场转向对象表示", "体数据切换到 3D modeling。", "模型可来自人工设计、程序生成或扫描重建；常见表示包括网格、曲线/曲面、隐式面、体和层级场景。表示决定可编辑操作。", ["section divider", "object/scene representation", "design or reconstruction"]),
        b(32, "CAD 模型：参数、约束与曲面服务制造", "章节牌换成 U. of Utah Alpha 1 机械零件。", "工程模型需要精确尺寸、圆孔、平面和装配关系；显示时可三角化，但原始参数曲面和约束比渲染网格更适合设计修改。", ["mechanical part", "precise geometry", "CAD model versus render mesh"]),
        b(33, "扫描动画 1：相机/激光器采集大卫雕像局部几何", "CAD 换成 Digital Michelangelo 扫描装置和雕像头部。", "扫描从真实表面获得距离/点云，需多视角配准、去噪、融合和补洞。此帧强调 acquisition，而不是最终模型。", ["scanner rig", "range measurements", "partial head reconstruction"]),
        b(34, "扫描动画 2：新增完整数字大卫，展示采集到成模结果", "第 33 页左侧仍保留，右侧新增完整雕像渲染。", "相邻页把 pipeline 的输出放进来：许多局部扫描融合为高分辨率表面，再由渲染器显示。扫描仍不会自动提供干净拓扑、材质或可动画骨架。", ["相邻页新增 full David", "registered scans", "geometry reconstruction"]),
        b(35, "大规模城市建模：对象复用与层级比单个网格更重要", "雕像扫描换成街区级三维线框/灰模。", "建筑、道路、轨道和重复构件需要实例化、层级与资产管理。大场景同时考验坐标精度、可见性剔除和分级细节。", ["urban scene", "many instances", "scene organization"]),
        b(36, "角色细分模型：粗控制网格定义平滑极限表面", "城市模型换成标注 subdivision level 1 的人头线框。", "控制网格经过局部细分规则产生更密、更平滑表面。它兼顾可编辑性和渲染质量，但眼口等特征还需拓扑设计和 crease 规则。", ["control mesh", "subdivision level", "smooth limit surface"], { textbook: book("教材第 12 章", "12.1 三角网格", "/book/12/", "教材从索引网格、拓扑和属性解释扫描/渲染表面；第 16 讲再深入细分规则与极限曲面。"), pause: "针对 CT 体、扫描雕像和 CAD 零件，分别写出最自然的原始表示、一个常见转换和一个可能丢失的信息。" }),
      ],
      checkpoint: "用同一 3D 标量体实现切片、MIP 和前后体合成；再对一个低模网格细分一次，明确区分采集数据、编辑模型和显示结果。",
    },
    {
      id: "3d-animation-rendering-and-xr",
      title: "三维场景随时间变化，再由渲染器变成电影、游戏与 XR",
      pages: "37-57",
      purpose: "从分子、角色和电影动画进入离线/实时渲染、云渲染与 VR/AR 的系统差异。",
      beats: [
        b(37, "3D animation 章节牌：状态从 scene 变为 scene(t)", "细分头部切换到 3D animation。", "动画可能来自关键帧、骨骼、物理模拟、运动捕捉或程序规则。除了位置，还会改变形状、材质、灯光与相机。", ["section divider", "time-dependent scene", "control versus simulation"]),
        b(38, "分子动画案例 1：蛋白质结合形变的冻结帧", "章节牌换成 citrate synthase 两部分的科学动画。", "分子动画把模拟或插值的三维构象可视化，颜色用于区分结构而非物体固有外观。可信性取决于数据/模型，视觉清晰度取决于表示。", ["scientific animation", "two molecular structures", "deformation during binding"]),
        b(39, "分子动画案例 2：PDF 与第 38 页完全相同", "物理页前进但静态图像一致。", "原 Keynote 很可能在课堂播放构象变化，PDF 只保存同一帧。自学时应寻找原模拟序列或用形状插值实验补足，不能从两张相同图推断运动路径。", ["exact duplicate", "missing temporal information", "frozen media"]),
        b(40, "角色动画工具：表情控制与 Unreal 骨骼界面", "分子动画换成 Blender 表情样张和 Unreal 角色 rig。", "上图展示脸部 shape keys/参数空间，下图展示骨骼、关节和控制器。动画师操纵低维控制，系统传播到大量顶点。", ["facial poses", "skeletal rig", "artist-facing controls"]),
        b(41, "电影动画案例 1：Toy Story 的一帧被冻结", "工具界面换成 Woody 与 Buzz 的电影镜头。", "截图说明三维角色、布景、镜头和光照共同参与动画制作；单帧只显示 pose，无法说明 timing、acting 或相机运动。", ["character pose", "staged shot", "frame from animated sequence"]),
        b(42, "电影动画案例 2：PDF 与第 41 页完全相同", "物理页变化但像素一致。", "这是又一处嵌入视频静态导出。它提醒我们动画的核心信息位于帧间；两张相同截图不是‘没有动画’，而是 PDF 载体丢失时间。", ["exact duplicate", "embedded clip likely", "need original video for motion"]),
        b(43, "Moana：角色、毛发、布料、水与海洋同时动画", "Toy Story 冻结帧换成海滩角色宣传图。", "一个镜头可能组合骨骼、肌肉/皮肤、衣物、头发、海水和程序环境。不同模拟需在时间、碰撞和艺术指导上协同。", ["characters", "cloth/hair", "ocean and environment"]),
        b(44, "Coco：群体角色、服装和复杂布景扩大制作规模", "海滩双角色换成室内群像。", "复杂度不仅来自多边形，还来自资产变体、群体动画、灯光和镜头叙事。场景图、实例化和缓存是生产系统的一部分。", ["crowd scene", "many assets", "production pipeline scale"]),
        b(45, "3D rendering 章节牌：给定某时刻场景，求相机图像", "动画案例切换到 3D rendering。", "渲染综合相机、几何、材质、光源与可见性，输出连续辐射的像素估计。离线和实时方法目标相同，但预算和近似不同。", ["section divider", "scene→image", "light transport and visibility"]),
        b(46, "离线动画渲染：雨夜材质、景深和运动效果", "章节牌换成 Pixar The Blue Umbrella 雨夜镜头。", "湿表面反射、雨滴、散景、雾和角色材质需要光传输、粒子/几何与成像模型协作。每帧可花较长时间，但仍必须控制噪声和一致性。", ["wet reflections", "depth of field", "cinematic offline budget"]),
        b(47, "电影 VFX：实拍、数字环境和角色需要无缝合成", "动画电影换成 The Hobbit/Weta 镜头。", "视觉特效渲染要匹配实拍相机、照明、镜头畸变、颗粒和颜色管理；几何真实还不够，所有成像线索必须一致。", ["live action plus CG", "camera/light matching", "compositing"]),
        b(48, "实时游戏渲染：在帧预算内近似电影级外观", "电影镜头换成 Crysis 3。", "实时系统通常只有约 16.7 ms/帧（60 fps），依靠 GPU 管线、预计算、LOD、屏幕空间近似和时间复用。性能是算法定义的一部分。", ["real-time frame budget", "GPU rasterization", "quality/performance tradeoff"]),
        b(49, "实时角色：雪、皮肤、衣物和粒子仍需稳定交互", "Crysis 角色换成 Two Souls 雪景。", "动态光照和角色材质必须在任意玩家视角稳定，不能只为一个固定镜头离线调好。temporal aliasing、阴影和动画穿插会成为系统问题。", ["interactive viewpoint", "character shading", "snow/particles"]),
        b(50, "地理可视化：全球数据到夜间城市图像", "角色镜头换成 Google Earth 风格夜景界面。", "这一无文字页展示大尺度分层数据与交互渲染：瓦片、地形、影像和城市灯光按视点流式加载。它连接 imaging、modeling 与 real-time rendering。", ["planet-scale scene", "streaming/LOD", "interactive visualization"]),
        b(51, "云渲染动画 1：把高成本渲染作为远程服务", "地理界面换成 Autodesk 360 Cloud Render 介绍拼图。", "用户上传场景或设计参数，服务器分配计算并返回图像。云端扩大算力，却仍需资产打包、版本一致、隐私和结果可复现。", ["remote render service", "architectural scenes", "compute moved off device"]),
        b(52, "云渲染动画 2：展示完整厨房结果", "服务介绍换成单张高质量室内渲染。", "这一帧建立最终输出：材质、窗外照明、间接光和相机曝光共同决定画面。下一页会补上服务界面。", ["rendered kitchen", "global illumination", "final image baseline"]),
        b(53, "云渲染动画 3：同一结果新增右下角界面缩略图", "第 52 页厨房保留，右下角增加浏览器/任务界面。", "相邻页把视觉结果放回工作流：渲染不是孤立图片，还需要提交、预览、比较和管理输出。", ["相邻页新增 UI inset", "same kitchen result", "workflow context"]),
        b(54, "IKEA：商业目录图也可能由三维场景渲染", "云服务案例换成绿色厨房目录图。", "渲染可替代搭建/拍摄大量产品组合，便于修改材质、布局和相机。但可信结果依赖精确资产、光照、色彩管理和质量审核。", ["catalog rendering", "asset variants", "photorealism used operationally"]),
        b(55, "VR/AR 章节牌：渲染结果要与头部和真实世界实时对齐", "室内目录切换到 VR/AR。", "XR 增加立体视图、低延迟头部跟踪、显示光学和现实配准。错误不只难看，还可能造成不适或错误空间判断。", ["section divider", "stereo and tracking", "latency matters"]),
        b(56, "VR、MR 与手机 AR：显示关系不同，基础图形链共享", "章节牌换成 Oculus、HoloLens 与 Pokémon Go。", "VR 用不透明显示替代视野，光学透视 AR 叠加到现实，手机 AR 通过相机视频合成。都需要相机/头姿、坐标系、遮挡与实时 rendering。", ["Oculus Rift", "HoloLens", "phone-based AR"]),
        b(57, "IKEA Place：平面检测、尺度、光照和遮挡决定家具是否‘在房间里’", "设备分类换成 AR 家具摆放实景。", "虚拟桌子必须与地面坐标对齐、尺寸可信、随相机稳定，并尽量匹配现实光照。缺少遮挡时它会永远浮在真实物体前，破坏存在感。", ["camera image background", "tracked furniture pose", "scale/occlusion/light matching"], { textbook: book("教材第 8 章", "视图与投影", "/book/8/", "XR、电影和游戏都依赖相机坐标、投影与视口；差别在于跟踪、延迟、立体和显示模型。"), pause: "把同一三维场景用于电影、60 fps 游戏和 AR，分别列出每帧预算、相机来源、允许的预计算和最严重失败模式。" }),
      ],
      checkpoint: "用场景图做一个三关节角色，加入关键帧和实时相机；分别以离线高样本、实时低预算和 AR 背景合成三种模式输出，记录每种模式的约束。",
    },
    {
      id: "graphics-research",
      title: "图形学让数学可见，也让难以描述的材料和梦想可计算",
      pages: "58-71",
      purpose: "从课程价值主张进入半透明、数字角色、头发、纤维和织物研究案例。",
      beats: [
        b(58, "Computer graphics: Mathematics made visible", "AR 案例切换到第一句领域价值主张。", "向量、矩阵、微积分、概率和优化在图形学里直接变成形状、光和运动。可见结果让数学错误更容易观察，也不会取代严格验证。", ["mathematics", "visible", "theory tied to images"]),
        b(59, "第二句价值主张：把想象变成可分享的视觉结果", "上一页保留 Computer graphics，增加 Ken Perlin 式改写。", "图形学既是分析工具，也是表达媒介。‘梦想’变成图像仍需明确表示、算法和误差；创造性与工程性在这里并不冲突。", ["show other people", "your dreams", "expression through computation"]),
        b(60, "Research 章节牌：当现有模型不能解释外观，就提出新表示和算法", "价值主张切换到 research。", "研究案例会从一个可见差异开始，提出物理/统计模型，测量或拟合参数，设计数值算法，再用真实参考验证。", ["section divider", "question→model→algorithm→validation", "examples from Cornell graphics"]),
        b(61, "半透明动画 1：只有理想化 diffuse ‘milk’", "章节牌换成第一杯乳白液体。", "基线可能把材料近似为表面漫反射，缺少真实牛奶的体内散射、吸收和浓度差异。下一两页逐项加入参照。", ["single diffuse baseline", "translucent material problem", "volume scattering missing"]),
        b(62, "半透明动画 2：新增 skim milk 对照", "第 61 页基线保留，右侧新增脱脂牛奶。", "相邻页用真实材料差异说明单一‘白色材质’不够。脂肪/颗粒改变散射，使透光、边缘和厚度响应不同。", ["相邻页新增 skim milk", "same lighting/background", "appearance depends on composition"]),
        b(63, "半透明动画 3：再新增 whole milk，形成三列参数序列", "前两杯保留，右侧新增全脂牛奶。", "三列使研究问题可比较：需要体散射系数、吸收、相函数和几何厚度，而不是只调表面 RGB。", ["相邻页新增 whole milk", "controlled comparison", "subsurface/volume transport"]),
        b(64, "数字角色：Gollum 的皮肤与毛发是两类复杂光传输", "牛奶序列换成 Gollum 特写。", "皮肤含多层散射、油脂高光和细节；头发由大量细纤维产生方向性高光、自阴影和多重散射。可信角色依赖几何、材质、动画与感知共同作用。", ["skin", "hair", "film-effects challenge"]),
        b(65, "头发参数动画 1：a=1.0 的基线", "角色特写切到背面头发渲染。", "先观察整体色调、发束分离和高光位置。a 是论文模型中的参数，单凭课件不能安全断言其精确定义；这里只追踪它对外观的控制。", ["a=1.0", "baseline hair appearance", "parameter semantics require source paper"]),
        b(66, "头发参数动画 2：a 增至 1.2，外观发生细微变化", "同一视角和模型只把 a 从 1.0 改为 1.2。", "相邻页保持几何/相机一致以隔离参数作用；高光分布、明暗或发束可见性略变。研究图应像这样控制变量。", ["a=1.2", "controlled parameter sweep", "subtle rendered difference"]),
        b(67, "头发参数动画 3：a=1.5，变化进一步累积", "a 从 1.2 增至 1.5。", "参数序列的价值是观察趋势并与照片/测量比较，而非挑一张‘最好看’。实现时还要报告模型公式和单位。", ["a=1.5", "same camera/model", "trend over three frames"]),
        b(68, "布料研究冻结帧 1：细纤维结构的近景", "头发参数换成 Kaldor et al. 2008 的浅色织物/纤维图。", "细纤维影响宏观弯曲、拉伸和外观。原演示可能展示织物模拟运动，PDF 只保留一张低对比帧。", ["cloth microstructure", "simulation research", "frozen media"]),
        b(69, "布料研究冻结帧 2：PDF 与第 68 页完全相同", "物理页前进但像素无差异。", "这是第五组完全重复页。应回到论文/视频观察时间变化；静态教程只记录研究主题，不虚构运动方向。", ["exact duplicate", "likely embedded simulation", "source video needed"]),
        b(70, "针织建模：从 stitch 到 mesh，再到渲染和照片参考", "冻结帧换成 Modeling knit cloth 四阶段对照。", "线圈/针脚是结构模型，转换后的 mesh 支持模拟和渲染；最终结果与照片比较验证几何和材质。层级表示让近景显式纱线、远景近似表面成为可能。", ["Stitch", "Mesh", "Final Result", "Photo Reference"]),
        b(71, "织物外观：几何褶皱、编织图案和材质共同生成软垫", "针织流程换成三个织物靠垫与红色布料模型插图。", "宏观形变决定轮廓与褶皱，微观编织决定高光和纹理，图案提供颜色变化。研究把不同尺度连接起来，避免用一张平面贴图承担所有效果。", ["multiscale cloth", "geometry plus reflectance", "rendered cushions"], { textbook: book("教材第 5 章", "表面着色与反射", "/book/5/", "教材提供局部反射和着色基础；牛奶、皮肤、毛发和织物研究则展示基础模型何处不足。"), pause: "选牛奶或头发序列，写一份受控实验表：固定量、变化参数、可观察指标、参考数据和不能从课件确定的内容。" }),
      ],
      checkpoint: "为一个材料参数做三帧受控 sweep，并把每帧与照片或高质量参考比较。报告参数含义、固定条件、图像差异指标和证据限制。",
    },
    {
      id: "course-overview-and-study-plan",
      title: "把全景落到学习计划：主题、先修、七份作业与诚信边界",
      pages: "72-82",
      purpose: "忠实保留 2018 课程行政页，同时把过时规定转换为今天可执行的自学路线。",
      beats: [
        b(72, "Course overview 章节牌：从‘能做什么’转向‘怎样学’", "研究案例切换到课程总览。", "前 71 页建立动机，最后 11 页说明人员、内容、先修和工作量。自学版把行政细节视为历史背景，把知识/项目结构视为可复用路线。", ["section divider", "motivation→mechanics", "2018 historical context"]),
        b(73, "2018 课程机制：官网与 TA 名单", "章节牌换成课程网站和助教名单。", "名单说明原课有较强答疑支持。自学时应主动替代：为每章保留问题清单、最小复现和公开讨论记录。旧人员与网址不代表当前服务状态。", ["course website", "head TAs and assistants", "historical roster"]),
        b(74, "课程承诺：基本思想、必要数学、关键算法与小型程序", "人员页换成 You will / You will not。", "目标不是大型软件工程，而是在可控代码中理解算法。网站的每讲检查点正沿用这个尺度：手算、小程序、边界测试和结果图。", ["fundamental ideas", "essential math", "implement key algorithms", "not very big programs"]),
        b(75, "主题清单是整门课的依赖图", "学习方式换成 Images → Modeling → Rendering → Transforms → Pipeline → Animation。", "这些主题并非严格线性：变换服务建模/相机，采样服务纹理/光追/显示，颜色贯穿光照与图像。学习时持续标注数据表示和坐标系。", ["images and color", "2D/3D modeling", "ray tracing and GPU", "animation"]),
        b(76, "先修要求：编程 + 向量/线代 + 微积分 + 概率", "主题清单换成 prerequisites。", ["编程要能读写调试小型 Java/类似程序并理解基本数据结构；数学包括点叉积、2–4D 线性变换、导数/积分和连续概率。", "不必先学完所有数学，但遇到公式时必须补齐输入、输出、单位、坐标系和极小验证。网站 Part 0 正用于补这些最小先修。"], ["small programs", "vector geometry", "calculus", "probability for Monte Carlo"], { textbook: book("教材第 6 章", "线性代数", "/book/6/", "教材的向量、基、矩阵和线性变换是课程最频繁复用的数学语言；概率与积分在后半光传输中接力。") }),
        b(77, "CS4621 扩展：更深 OpenGL/WebGL、团队架构和自选项目", "4620 先修换成配套实践课内容。", "它区分概念/小算法课程与大型交互项目训练。自学者可把独立项目作为选修，不应因没搭大型引擎而推迟基础算法验证。", ["deeper APIs", "group project", "software teams"]),
        b(78, "工作量页确认：CS4620 有 7 份书面 + 7 份编程作业", "扩展课换成 workload 数量。", "这页直接回答了早先作业数量疑问：不是六份，而是 Mesh、Ray 1、Manipulators、Shaders、Splines、Animation、Ray 2 共七个项目；除 Mesh 无书面部分外，其余包含书面任务。", ["7 written assignments", "7 programming assignments", "2 exams"], { pause: "在网站项目页核对七个作业名称、所在 Part、是否有书面部分和课件前置知识。" }),
        b(79, "Academic Integrity 标题页：技术学习也要记录来源和合作边界", "工作量换成诚信章节牌。", "原讲义此页不含细则。自学公益项目同样应保留来源链接、区分原文/翻译/推导，并在提交课程作业时遵守授课方规则。", ["section divider", "attribution", "do not confuse study aid with submitted work"]),
        b(80, "2018 迟交政策：slip days 是历史规则，不是当前网站功能", "诚信页换成 7 天额度、个人记账与扣分示例。", ["这页忠实记录当年政策：4620/4621 各 7 slip days、超额每天扣 10 分、最长 7 天等。", "自学时可借鉴为缓冲预算，但正式选课必须查当期 syllabus；不要把 2018 数字当现行规定。"], ["7 slip days", "per-individual accounting", "historical late policy"]),
        b(81, "教材页：课程以 Marschner & Shirley 第四版为主", "迟交政策换成 Fundamentals of Computer Graphics 封面。", "本站教材版采用用户整理的第五版中文材料，章节编号与 2018 第四版可能不同；每个课件链接应按主题对应，而非机械复制旧 reading number。", ["Marschner & Shirley", "fourth edition in 2018", "site uses fifth-edition Chinese structure"]),
        b(82, "最后一页只留下课程网址，作为继续学习的入口", "教材封面换成 cs4620 URL。", "原网址保存课表、作业、考试和资源。本站将它们重新组织为自学路径，但 Cornell 页面仍是课程事实和原始资源的基准来源。", ["course URL", "primary-source archive", "end of 82 physical pages"]),
      ],
      checkpoint: "写一份 12 周自学计划：七个项目各自的前置讲次、每周数学补课、一个阶段测试和缓冲时间。明确哪些行政信息来自 2018、哪些是你自己的规则。",
    },
  ],
  synthesis: [
    "定义层：图形学研究在计算机中创建、操作和使用视觉图像，不等于单一 API、照片编辑或三维写实。",
    "任务层：imaging 处理图像/体数据，modeling 设计表示，animation 令状态随时间变化，rendering 从表示生成像素。",
    "二维层：照片处理、字体、动态图形、地图和游戏说明二维同样需要几何、时间、采样与渲染。",
    "三维层：CT、扫描、CAD、网格和细分强调测量数据、编辑模型与显示图像是不同对象。",
    "生产层：电影、游戏、云渲染和 XR 共享相机—场景—像素链，但在帧预算、交互、跟踪和验证标准上不同。",
    "研究层：半透明、皮肤、头发和织物把可见差异转成受控参数、物理模型、算法和参考验证。",
    "证据层：静态 PDF 完全重复的五组页来自未保留的媒体可能性最大；教程展示并标记重复，但不虚构动画内容。",
    "学习层：向量/矩阵、微积分、概率和小程序是工具；七份项目把网格、光追、变换、着色器、样条、动画和高级光追串起来。",
    "来源层：2018 人员与政策是历史档案；课程原站是事实基准，教材第五版中文结构是本站的主要文字学习路径。",
  ],
  finalPractice: "选择一帧游戏、动画电影或 AR 画面，制作 Graphics System Map：列出所有可见要素，将每项分配到 imaging/modeling/animation/rendering，写清数据表示、坐标系、时间依赖与输出；再沿‘模型→变换→相机→可见性→光照→采样→显示→后期’画完整管线。为至少三个环节设计可失败的小测试，并把它映射到七份 CS4620 作业中最接近的一份。",
};
