import type { DetailedLectureTutorial, DetailedSlideBeat } from "./detailed-tutorial-data";

const book = (chapter: string, section: string, href: string, bridge: string) => ({ chapter, section, href, bridge });
const b = (page: number, title: string, change: string, explanation: string | string[], inspect: string[], extra: Partial<Omit<DetailedSlideBeat, "page" | "title" | "change" | "explanation" | "inspect">> = {}): DetailedSlideBeat => ({ page, title, change, explanation: Array.isArray(explanation) ? explanation : [explanation], inspect, ...extra });

export const rayAcceleration: DetailedLectureTutorial = {
  pdf: "22raytracing-accel.pdf",
  pageCount: 60,
  estimatedTime: "约 5-6 小时（含局部空间、BVH、slab、网格与 k-d tree 练习）",
  question: "怎样在不改变任何命中结果的前提下，让一条光线跳过绝大多数几何体？",
  opening: [
    "第 21 讲增加了每像素的光线数量，本讲则减少每条光线必须测试的物体数量。核心不是把三角形求交再快一点，而是用便宜、保守的测试证明一大组几何不可能被命中。",
    "课件先把变换、分组和实例统一进 Surface 接口，再从单个包围体递归到 BVH；随后用连续 31 个动画页展示 BVH 构建、遍历与 AABB slab 区间交。最后对比对象划分的 BVH、规则空间网格和自适应 k-d tree。阅读时始终检查两个不变量：加速结构不能漏掉真实命中，返回的最近 t 必须与暴力遍历一致。",
  ],
  outcomes: [
    "把世界空间射线变到对象局部空间，并正确变回命中点和法线",
    "用 SurfaceGroup、TransformedSurface 和共享子图实现层级与实例",
    "解释包围体的保守性、紧致度和测试成本之间的权衡",
    "逐帧执行 BVH 构建和最近命中遍历，并利用 tMax 剪枝",
    "推导三维 AABB 的 slab 区间交，处理负方向、零方向与射线区间",
    "比较中心、median 与 SAH 划分对树形和遍历成本的影响",
    "区分 BVH 的对象划分与 grid/k-d tree 的空间划分",
    "建立结果一致性、节点访问数和 primitive 测试数三类验证器",
  ],
  runningExample: {
    title: "贯穿例子：四个车轮实例与十个三角形",
    description: "一个车轮网格被四个变换节点共享；地面上另有十个三角形。先用局部空间避免复制网格，再为三角形构建 AABB/BVH。所有优化都与暴力遍历逐射线比较 hit/miss、primitiveId 和 t。",
    code: "world ray -> instance inverse transform -> local ray\nlocal ray -> BVH node AABB -> near child -> primitive\nhit point -> world transform\nhit normal -> inverse-transpose\nassert(acceleratedHit == bruteForceHit)",
  },
  chapters: [
    {
      id: "local-space-hierarchy",
      title: "先统一场景接口：移动射线，不改写复杂几何",
      pages: "1-13",
      purpose: "建立对象空间求交、组合节点、变换层级与实例，为加速结构准备统一 Surface 接口。",
      beats: [
        b(1, "光线追踪加速：结果不变，只减少不可能命中的工作", "标题页给出 Lecture 22 的主题。", "本讲的 acceleration 不允许近似可见性，也不允许改变最近命中。它只在昂贵 primitive.intersect 之前增加便宜的排除步骤，并组织调用顺序。", ["Ray Tracing Acceleration", "CS 4620 Lecture 22", "PDF 共 60 个物理页"]),
        b(2, "路线图分两层：场景变换与空间索引", "标题页展开为 transformations 与 acceleration structures 两组主题。", ["前半先解决对象怎样以局部坐标、层级和实例出现在光追器中；后半才讨论 bounding volume、BVH、uniform subdivision 和 adaptive subdivision。两者通过同一个 Surface.intersect 接口连接。", "顺序很重要：若场景表示和求交接口不统一，加速结构会被各种特殊对象分支淹没。"], ["transforming objects / hierarchies", "bounding volumes / BVH", "uniform / adaptive spatial subdivision"]),
        b(3, "变换球体的两个选择：推导椭球，或反向变换射线", "路线图切到 transformed sphere 的设计选择。", "把单位球直接变到世界可能得到任意椭球，需要新求交推导；把世界射线乘 T⁻¹ 后，仍可复用标准球求交。一般原则是把查询变到数据最简单的坐标系。", ["Option 1 改几何和算法", "Option 2 只改射线", "T 必须可逆"], { formula: "r_local(t)=T^{-1}o+t(T^{-1}d)" }),
        b(4, "对象空间图解：世界中的椭圆等价于局部空间的圆", "文字选择换成椭圆、圆和两条对应射线的几何图。", "世界命中点 M 与局部命中点 m 满足 M=T m；世界射线经逆变换后与标准对象在相同参数 t 处相交。这里方向不要重新单位化，否则 t 会被缩放，原来的 tMin/tMax 与最近命中比较也随之失效。", ["T 把局部圆映成世界椭圆", "T⁻¹ 把世界射线映回局部", "同一个参数 t 对应同一条仿射射线"], { textbook: book("教材第 12 章", "12.2.2 在光追渲染中", "/book/12/", "教材明确说明不归一化变换后的方向，可让交点参数 t 在两个仿射空间中保持一致。") }),
        b(5, "TransformedSurface：包装器负责坐标系边界", "几何图变成三步实现清单。", ["包装器保存 T 与子 Surface。进入时用 T⁻¹ 变换射线，子对象只看局部坐标；返回时用 T 变换点、用 T⁻ᵀ 变换法线。", "法线不是普通方向。非均匀缩放后，直接乘 T 会破坏它与切平面的垂直关系。"], ["ray 用 inverse(T)", "point 用 T", "normal 用 inverse-transpose(T)"], { formula: "p_w=T p_l；n_w=normalize(T^{-T}n_l)", textbook: book("教材第 7 章", "7.2.2 法向量的变换", "/book/7/", "教材从变换后切向量仍应与法线垂直，推导出逆转置矩阵。") }),
        b(6, "变换求交伪代码：t 原样返回，点和法线各走不同矩阵", "清单收束成 TransformedSurface.intersect 代码。", ["代码把责任边界写得很清楚：子 surface 返回局部 p,n,t，包装器只转换 p,n。若局部方向未被归一化，t 无需换算。", "工程实现还应处理 miss、奇异 T、法线归一化，以及 handedness 改变时切线框架的方向。"], ["xf⁻¹ r", "xf p", "xf⁻ᵀ n", "t 未修改"], { pause: "用非均匀缩放 diag(2,1,1) 测试一个单位球；比较直接乘 T 的错误法线和 T⁻ᵀ 的正确法线。" }),
        b(7, "SurfaceGroup：把多个对象也伪装成一个 Surface", "变换包装器扩展为对象列表与最近命中。", "组节点逐个求交并返回最小有效 t。这样 Scene 本身也可以是一棵 Surface，变换节点、叶对象和后面的 BVH 节点便可递归组合。", ["list of surfaces", "returns closest intersection", "Scene 与 group 可共享逻辑"]),
        b(8, "组求交代码：每次命中都收紧 tMax", "设计清单变成 SurfaceGroup.intersect 伪代码。", ["发现命中 t 后把 tMax 更新为 min(t,tMax)，后续对象就只接受更近命中。这不仅保证结果最近，也为 BVH 的远子树剪枝准备了统一的区间接口。", "伪代码最后返回保存的 p,n 和当前 tMax；真实实现应避免 miss 时使用未初始化的 hit data。"], ["for each surface", "命中后更新 tMax", "遍历结束才返回最近结果"], { formula: "valid hit: tMin ≤ t ≤ currentClosest" }),
        b(9, "变换层级：汽车、轮组与轮胎沿路径复合", "组代码换成 car 的树形结构。", "叶对象的世界变换是根到叶所有局部变换的有序乘积。group 负责组合，transform 负责坐标边界；课件提示常把 transform 与 group 合并以减少节点和虚调用。", ["car group 是根", "wheel assembly / wheel 是中间组", "tire、hubcap、brake disc 是叶"]),
        b(10, "实例化：多个变换节点可以共享同一几何", "单棵层级转向重复机械部件与 DAG。", "四个车轮不必复制四份顶点和 BVH；创建四个 TransformedSurface，全部引用同一个 wheel Surface。共享让树变成有向无环图，但求交仍沿每条实例路径携带不同变换。", ["机械件与教室椅是重复子组件", "two wrappers reference same Surface", "tree becomes DAG"]),
        b(11, "实例层级图：三条 Transform 边汇入同一 wheel 子图", "文字说明变成共享节点示意。", "共享的是局部几何和其内部加速结构，不是世界状态。每次调用先用当前实例的 T⁻¹ 变换射线，因此同一 wheel 子图可在不同位置独立命中。修改共享网格会影响所有实例。", ["多个 Transform 节点", "共同指向 Group: wheel", "body 仍是独立叶"]),
        b(12, "层级性能：射线变换也有成本，应在加载时压平", "实例图换成 flatten on input 的优化建议。", ["深层层级让每条射线反复乘矩阵。可预先把连续变换相乘并推向叶节点；对独立网格甚至可烘焙顶点。", "但实例共享的孩子不能同时接收两个不同父变换，所以共享边界处仍需保留实例变换节点。"], ["minimize tree depth", "push transformations toward leaves", "instancing 阻止完全压平"]),
        b(13, "压平动画：A 保留在 mesh，AB 合并到 sphere", "文字建议换成压平前、中、后三种结构。", ["左侧嵌套 TransformGroup(A)→TransformGroup(B)；中间把累计矩阵写进叶；右侧网格可选择把 A 烘焙进顶点，而 sphere 保存复合 AB 与原半径。", "烘焙 mesh 会失去共享原始顶点的机会；给 mesh 保存对象变换则能让一次 ray transform 被许多三角形求交摊销。"], ["Av₁,Av₂… 是烘焙方案", "sphere 的 xf=AB", "结构优化与数值结果必须一致"]),
      ],
      checkpoint: "实现 TransformedSurface 与 SurfaceGroup；测试非均匀缩放法线、未归一化局部射线、嵌套 AB 次序和四实例共享。",
    },
    {
      id: "bounds-to-bvh",
      title: "便宜的保守拒绝：从单个包围体递归到整棵 BVH",
      pages: "14-20",
      purpose: "解释为什么减少 primitive 调用比微调单次求交更重要，并形成透明的 BoundedSurface 层级。",
      beats: [
        b(14, "真正的瓶颈是调用了太多 ray-surface intersection", "层级优化切到 ray tracing is slow 的成本诊断。", "单个三角形求交即使优化到极致，N 个对象的暴力扫描仍是每条光线 O(N)。更大的杠杆是快速找出整批绝不相交的几何，并完全不调用它们。", ["most time in intersection methods", "faster primitive 只能获得常数改进", "fewer calls 改变搜索规模"]),
        b(15, "包围体的单向保证：没命中盒子，一定没命中物体", "成本诊断换成三个形状与外包体。", ["包围体必须完整包含对象。ray miss bound ⇒ ray miss object，因此可安全拒绝；反过来 ray hit bound 并不保证命中对象，只能进入精确阶段。", "这是保守加速结构的基本逻辑：允许 false positive，不允许 false negative。"], ["对象完全位于 volume 内", "先测 bound", "命中 bound 后仍需测 object"]),
        b(16, "包围体是否划算由三项决定：便宜、昂贵、贴合", "示意图展开为成本与紧致度权衡。", ["真正命中和 near miss 会多付一次 bound 测试；far miss 才节省昂贵 primitive 测试。", "球简单但可能松，OBB 紧但要变换射线。最优 bound 不是几何上最紧，而是 expected traversal cost 最低。"], ["bound intersection cost", "object intersection cost", "tightness of fit"]),
        b(17, "BoundedSurface：miss 快速返回，hit 委托子对象", "权衡页换成包装器接口。", "和 TransformedSurface 一样，BoundedSurface 对渲染器透明。区别是它不改变坐标，只在调用子 surface 前执行保守 gate；因此所有 Surface 还需能计算自身 bound。", ["contains BVol and Surface", "bound miss→false", "bound hit→surface.intersect"]),
        b(18, "包围包装器伪代码：区间必须原样传给两级测试", "接口清单收束为六行代码。", "bound 与 child 都使用当前 tMin,tMax。若盒子只在最近命中之后相交，应直接视为 miss；否则会进入不必要的子树。真实 AABB 测试最好返回 enter/exit 区间，便于子节点排序。", ["v.intersect(r,tMin,tMax)", "只有 true 才调用 s.intersect", "接口仍返回原 Surface hit"]),
        b(19, "既然一层有用，就把包围体贯穿整棵场景", "单包装器扩展为 whole scene→group→few objects。", "仅给每个复杂对象套一个盒子仍要测试所有盒子。给对象组也加盒子，miss 就能跳过一大片；继续递归便从线性列表得到层级搜索。", ["objects、groups、parts 都可包围", "根包围整个场景", "叶只含少量 primitives"]),
        b(20, "BVH 的定义：BoundedSurface 的孩子仍可为 BoundedSurface", "层级动机收束为递归数据结构。", "内部节点保存 bound 与子 Surface 列表，孩子可以继续是内部节点，叶孩子才做精确求交。renderer 只调用根的 intersect，并不知道下方是 BVH、普通组还是 primitive。", ["递归包含 BoundedSurface", "transparent to renderer", "对象划分而非空间唯一划分"]),
      ],
      checkpoint: "统计 10 万条随机射线的 boundTests 与 primitiveTests；分别使用紧盒和扩大两倍的松盒，验证结果完全一致而 primitiveTests 明显不同。",
    },
    {
      id: "bvh-animation",
      title: "逐帧读懂 BVH：构建分组，遍历则用区间和最近命中剪枝",
      pages: "21-34",
      purpose: "保留课件完整动画，区分树的对象归属、盒子重叠和一次最近命中查询的访问顺序。",
      beats: [
        b(21, "构建帧 1：只有十个 primitives，还没有索引", "文字定义换成散布的绿色三角形。", "这是暴力基线：每条射线需要依次测试十个三角形。后续蓝色矩形表示节点包含对象集合的 bound，而不是把矩形覆盖区域永久分配给该节点。", ["十个三角形", "无包围框", "对象集合是构建输入"]),
        b(22, "构建帧 2：根盒包住全部对象", "三角形外新增一个浅蓝根 AABB。", "根 miss 可一次排除全场景；根 hit 仍不能排除任何 primitive，所以仅一层对进入场景的主射线帮助有限。下一帧必须划分对象集合。", ["根盒包含所有 triangles", "包围盒可有空区域", "此时仍是一个大叶"]),
        b(23, "构建帧 3：按 x 分成左右孩子，左孩子更紧", "根内新增竖向划分和两个子集合的盒子。", ["每个 primitive 归入左或右对象列表；两边的 AABB 由各自对象重算。盒子可以相接或重叠，BVH 不要求空间互斥。", "左侧又画出更紧的子盒，提示 top-down recursion 已进入左集合。"], ["根仍保留", "左右孩子覆盖不同对象集合", "子盒只需包含自己的 descendants"]),
        b(24, "构建帧 4：继续递归，叶盒只含少量三角形", "左右大盒内部再出现水平或嵌套小盒。", "停止条件通常是 leaf primitive count、深度或 SAH 判断继续划分已不划算。图中盒子彼此可重叠，因为划分的是对象集合。", ["左下与左上分开", "右侧也形成两个小组", "每个叶只保留少量 primitives"]),
        b(25, "遍历帧 1：一条射线进入场景，尚未访问节点", "标题改为 BVH ray-tracing example，并加入斜向射线。", "把这条查询写成区间 [tMin,tMax]。遍历目标不是找到任意绿色三角形，而是返回区间内 t 最小的命中。", ["箭头给出 ray direction", "三角形不再逐个高亮", "当前最近距离初始为 tMax"]),
        b(26, "遍历帧 2：先测根盒；命中才展开孩子", "根 AABB 边框高亮。", "根 slab 测试返回非空 [tEnter,tExit]，说明场景中可能有候选。若这里 miss，整个遍历会用一次盒测结束。", ["只高亮根", "尚未测试 primitive", "root hit 是继续条件"]),
        b(27, "遍历帧 3：测试根的两个孩子", "左右孩子盒同时出现。", "射线可能命中两个兄弟盒，因此 BVH 不是普通二分搜索。实现应计算两个 enter t，并优先访问较近者；仍可能需要访问远者。", ["左右盒都与 ray 相交", "兄弟盒可同时命中", "near-first 由 tEnter 决定"]),
        b(28, "遍历帧 4：选择较近的左孩子", "左孩子边框高亮，右孩子暂缓。", "优先访问左侧不是因为它是 left pointer，而是它的盒入口更近。固定 left-first 仍正确，但通常少不了远子树工作。", ["左盒高亮", "右盒仍是待处理候选", "排序依据是 ray-box tEnter"]),
        b(29, "遍历帧 5：展开左孩子的两个子盒", "左区域内部新增上下两个叶盒。", "父盒命中只说明至少可能进入其 descendants；继续对子盒做便宜测试。射线穿过上盒，似乎也擦过下盒边界，遍历仍以数值区间为准。", ["左上、左下叶盒", "父盒保持可见", "层级逐层缩小候选"]),
        b(30, "遍历帧 6：完成左侧候选检查，尚无最近 primitive", "盒结构不变，访问高亮推进到左侧叶。", "动画用颜色变化表示访问状态而非新增几何。叶命中后才测试其中三角形；若没有 primitive hit，currentClosest 仍为原 tMax。", ["这一页结构与上一页相同", "变化是 traversal state", "不能把 box hit 当作 surface hit"]),
        b(31, "遍历帧 7：回溯并访问根的右孩子", "右侧大盒转为当前高亮。", "左子树未给出足以结束的最近命中，因此从栈中取出右候选。递归实现靠调用栈，迭代实现通常用显式 stack。", ["右大盒高亮", "左侧已访问", "这是 depth-first 回溯"]),
        b(32, "遍历帧 8：展开右孩子的上下子盒", "右区域新增两个水平叶盒。", "射线会进入右下/中部子盒，因此该叶仍需检查；另一个远离射线的叶可由 AABB miss 排除。", ["右侧两个 child bounds", "空间覆盖不代表对象归属", "miss child 不访问其 primitives"]),
        b(33, "遍历帧 9：命中的右侧叶进入精确求交", "结构保持，当前叶盒高亮。", "现在才对叶内少数三角形运行 ray-triangle。若得到 tHit，就把 currentClosest 收紧为 tHit；后续任何 tEnter≥tHit 的待处理盒都可丢弃。", ["leaf hit→primitive tests", "更新 tMax", "远节点可被最近距离剪枝"]),
        b(34, "遍历帧 10：圆圈标出最终最近命中", "射线与一个三角形交点被蓝圈标记，遍历结束。", ["动画最终命中位于右侧靠分割线的三角形。正确性要求返回它而不是先访问到的任意三角形。", "若待处理栈中所有盒的 tEnter 都不小于 currentClosest，即可安全结束；否则仍要继续检查可能更近的盒。"], ["蓝圈是 primitive hit", "盒子只负责候选", "最近命中由最小有效 t 决定"], { textbook: book("教材第 12 章", "12.3.2 层级边界盒", "/book/12/", "教材强调兄弟盒可重叠、两个都可能被射线命中，因此需要递归比较而非单路二分查找。") }),
      ],
      checkpoint: "手工为第 25 页射线记录 stack、node tEnter/tExit、primitiveTests 和 currentClosest；解释第 31 页为何必须回溯，以及哪一刻可以安全停止。",
    },
    {
      id: "aabb-slabs",
      title: "AABB slab 测试：把三维盒命中化成三个一维 t 区间的交集",
      pages: "35-51",
      purpose: "从包围体选择走到完整 ray-box 推导，并逐帧保留课件的二维区间动画。",
      beats: [
        b(35, "包围体选择：sphere、AABB、OBB 都在成本与紧度间取舍", "BVH 命中动画切到三种 bounding volume 对比。", ["sphere 测试便宜但对细长物体松；AABB 通常紧且无须变换射线；OBB 对任意朝向更紧，却需额外坐标变换。", "构建难度也不同：group 的 AABB 可直接合并 min/max，优质 OBB 则需要估计方向。"], ["sphere: easy/not always tight", "AABB: easy/often tighter", "OBB: transform cost/tighter"]),
        b(36, "AABB 的构建：合并 min/max，变换后包住八个角", "选择对比收束到 axis-aligned bounding boxes。", ["primitive AABB 常能解析计算；mesh/group 对所有组件取坐标 min/max。变换 AABB 时，把局部盒八角乘 T 后再取世界 min/max，可得保守世界 AABB。", "不能只变换 min 和 max 两点：旋转后极值角可能改变。"], ["groups/meshes: component min/max", "transformed surface: 8 corners", "intersection uses slabs"]),
        b(37, "盒命中的另一种视角：沿射线得到三段 t 区间", "文字页换成二维盒、射线和平行区间示意。", "盒是多个半空间的交；对每个坐标轴，射线位于 [min,max] slab 内的 t 值构成一个区间。所有轴区间有公共部分，射线才在某段 t 上位于盒内。", ["空间中的 box", "参数轴上的 intervals", "目标是 interval intersection"]),
        b(38, "不要逐测六个面：盒是三个 slabs 的交", "区间示意换成一个立方体。", "逐面求交要处理平面边界与面内判断；slab 法只做每轴两次平面 t 和全局 max/min，天然支持从盒内出发的射线。", ["6 faces 是可行但冗余", "3 slabs 对应 x/y/z", "只关心是否有公共 t"]),
        b(39, "slab 动画 1：先显出第一对平行平面", "立方体外新增一组半透明平面。", "这一组平面定义某一轴的 [min,max] 区间；射线在两次穿平面之间位于该 slab。", ["两平行平面", "box 是它们与另外两组的交", "每轴独立求 interval"]),
        b(40, "slab 动画 2：加入第二组平面", "垂直组之外再出现水平平面。", "两个轴的 slab 相交成一条无限柱体；仍未限制第三坐标。算法上已有两个 t 区间，可先求它们的交并提前拒绝。", ["第二个 slab", "部分交可提前为空", "逐轴更新全局 enter/exit"]),
        b(41, "slab 动画 3：三组平面的交就是 AABB", "加入第三组平面，完整包围立方体。", "三维算法对 x,y,z 重复同一更新：enter=max(axis enters)，exit=min(axis exits)。最后 enter≤exit 且与 [tMin,tMax] 重叠才命中。", ["三组 slabs", "AABB 是共同区域", "维数只改变循环次数"]),
        b(42, "二维推导起点：矩形只是 x-slab 与 y-slab 的交", "三维图切成二维矩形，没有射线。", "课件用 2D 降低视觉负担；3D 只需再加 z 轴。矩形由 xmin,xmax,ymin,ymax 定义。", ["(xmin,ymin)/(xmax,ymax)", "尚未计算 t", "3D is the same"]),
        b(43, "二维推导第 2 帧：把四条 slab 边界延伸出来", "矩形边缘延伸为两竖两横直线。", "现在能分别讨论射线何时进入 x 范围、何时进入 y 范围。区间端点不等于固定 enter/exit，负方向会交换先后。", ["xmin/xmax 竖线", "ymin/ymax 横线", "每轴先求两个 raw t"]),
        b(44, "二维推导第 3 帧：x 两平面给出 txmin 与 txmax", "加入射线、原点方向和两处 x 交点标注。", "对 r(t)=p+td，txmin=(xmin-px)/dx，txmax=(xmax-px)/dx。名字表示平面，不表示时间先后；dx<0 时 txmax 反而更小。", ["(px,py) 与 (dx,dy)", "txmin/txmax", "不要假设 direction 为正"], { formula: "t_{x0}=(x_min-p_x)/d_x；t_{x1}=(x_max-p_x)/d_x" }),
        b(45, "二维推导第 4 帧：y 轴也产生 tymin 与 tymax", "在 x 标注上叠加两个 y 交点。", "到此有四个 raw t。每轴都先排序成 enter=min(t0,t1)、exit=max(t0,t1)，再在轴之间求交。", ["tymin/tymax", "负 dx/dy 自动由 min/max 处理", "四个值属于两段区间"]),
        b(46, "区间交动画 1：先只看 x-slab 的进入与退出", "几何图抽象为一段 x interval。", "射线在 [txenter,txexit] 内满足 xmin≤x(t)≤xmax。若这是线而非射线，负 t 也可能存在；最终还要与调用者的 [tMin,tMax] 相交。", ["txenter", "txexit", "每个 slab 命中是一段 t"]),
        b(47, "区间交动画 2：显式排序 x 的两个平面 t", "左侧新增 txenter=min 与 txexit=max 公式。", "用 min/max 而不是 direction 分支，直接覆盖正负方向。高性能实现常预计算 invDir 并按符号索引 bounds，但数学仍是同一区间。", ["min(txmin,txmax)", "max(txmin,txmax)", "-0 与 inf 需要数值测试"]),
        b(48, "区间交动画 3：单独加入 y-slab 区间", "x 公式保留，右侧出现 tyenter/tyexit 段。", "现在问题转为两段一维区间是否重叠。区间的空间来源不同，但都使用同一个 ray parameter t，因此可以直接比较。", ["y interval", "与 x interval 在同一 t 轴", "仍未求共同部分"]),
        b(49, "区间交动画 4：也排序 y 的两个平面 t", "左侧再加入 tyenter 与 tyexit 公式。", "每个轴内部先排序是关键。若直接把 t(min plane) 当 enter，负方向会产生错误拒绝。", ["tyenter=min(tymin,tymax)", "tyexit=max(tymin,tymax)", "x/y 处理对称"]),
        b(50, "区间交动画 5：两段重叠区域就是穿过矩形的 t 段", "x 与 y 区间叠到同一图上，公共部分变深。", "共同进入发生在较晚的轴进入点，共同退出发生在较早的轴退出点。因此用 max(entries) 和 min(exits)。", ["深色公共 interval", "last entry", "first exit"]),
        b(51, "区间交动画 6：最终 tenter/texit 公式完成", "左侧加入 tenter=max 与 texit=min。", ["若 tenter≤texit，则无限直线穿盒；对射线段还要计算 max(tenter,tMin)≤min(texit,tMax)。从盒内出发时 tenter 可能小于 0，但只要退出点在有效区间仍应命中。", "方向分量为 0 时可显式判断 origin 是否在 slab；也可谨慎利用 IEEE ±∞。教材还提醒 -0 会影响符号分支，应以 invDir 符号测试并覆盖单元测试。"], ["tenter=max(txenter,tyenter)", "texit=min(txexit,tyexit)", "3D 再加入 z enter/exit"], { formula: "t_enter=max(tMin,t_xenter,t_yenter,t_zenter)\nt_exit=min(tMax,t_xexit,t_yexit,t_zexit)\nhit ⇔ t_enter≤t_exit", textbook: book("教材第 12 章", "12.3.1 边界盒", "/book/12/", "教材补足课件未展开的平行射线、IEEE infinity 和负零边界情况。"), pause: "为 dx=0 且原点在/不在 x-slab、dx=-0、从盒内出发、擦边和 tMax 在盒前各写一条测试。" }),
      ],
      checkpoint: "实现返回 [tEnter,tExit] 的 AABB.intersectInterval；用随机盒与射线同六面逐测参考实现比较，并覆盖平行、负方向、盒内起点、边界相切和有限 shadow ray。",
    },
    {
      id: "building-quality",
      title: "树的正确性很容易，树的质量决定真正速度",
      pages: "52-53",
      purpose: "给出 top-down 构建框架，并比较 center、median 与 SAH。",
      beats: [
        b(52, "Top-down 构建：包住全部对象、二分、递归、到小叶停止", "slab 推导切回 hierarchy construction 清单。", "建立根 AABB 后把对象集合划为两组，递归计算各自 bound。叶阈值太大增加 primitive tests，太小增加节点、内存和 traversal overhead；应以实际场景测量。", ["whole-scene bbox", "split into two parts", "stop at a few objects"]),
        b(53, "三种划分：center 快、median 平衡、SAH 估计期望成本", "构建框架展开为 partition 策略对比。", ["center 按空间中点分，构建便宜但对象集中时树不平衡；median 按质心排序/选择中位数，数量平衡却不保证空间好；SAH 估计射线命中子盒的概率与叶成本，通常遍历最快。", "SAH 的直觉是面积越大的子盒越可能被随机射线命中，重叠和大面积都应付出代价。"], ["center partition", "median partition", "surface area heuristic"], { formula: "C_split=C_trav+(A_L/A_P)N_L C_isect+(A_R/A_P)N_R C_isect", textbook: book("教材第 12 章", "12.3.2 层级边界盒", "/book/12/", "教材给出按轴排序、对象数量划分与空间划分的不同启发式，说明平衡不等于低遍历成本。") }),
      ],
      checkpoint: "在同一组 clustered primitives 上构建 center、median 和 binned SAH 三棵树，记录构建时间、节点数、最大深度、平均 primitiveTests 与总渲染时间。",
    },
    {
      id: "space-subdivision",
      title: "另一条路线：不分对象，而是把空间本身切成单元",
      pages: "54-60",
      purpose: "比较 uniform grid、DDA 遍历与自适应 k-d tree，并把加速结构从场景表示中解耦。",
      beats: [
        b(54, "规则空间细分：用均匀网格替代对象层级", "BVH 构建策略切到 uniform grid 与穿格射线。", "BVH 给每个对象选择一个孩子，盒子可重叠；grid 让每个空间点只属于一个 cell，跨 cell 的 primitive 则会被多个 cell 引用。", ["uniform cells", "ray 只访问穿过的 cells", "这是 space subdivision"]),
        b(55, "网格例子：grid divides space, not objects", "抽象网格换成十个三角形落入各单元。", ["细长三角形横跨多个格，会出现在多个 cell 列表中；这不是复制几何，只是重复引用。空格可以极快跳过。", "网格太粗，每格对象多；太细，内存、重复引用和 cell traversal 增加。非均匀场景尤其难选统一分辨率。"], ["一个对象可覆盖多个 cells", "一个空间点只在一个 cell", "空 cell 是主要收益"]),
        b(56, "规则网格遍历：3D DDA 每次跨过最近的下一张网格平面", "静态网格换成三幅逐步穿格示意。", ["先求射线进入总 grid 的点与起始 cell，再维护到下一 x/y/z 边界的 tNext 和每跨一格增加的 tDelta。每次选择最小 tNext，沿对应轴递增 cell index。", "测试 cell 中 primitive 时必须把有效 t 限制在该 cell 的退出位置；否则远处命中可能让遍历过早结束。重复引用还需要 mailbox 或 id 标记避免重复求交。"], ["incremental traversal", "下一平面 t 形成等差序列", "cell interval 限制 primitive hit"], { formula: "axis=argmin(tNextX,tNextY,tNextZ)；cell[axis]+=step[axis]；tNext[axis]+=tDelta[axis]", textbook: book("教材第 12 章", "12.3.3 均匀空间细分", "/book/12/", "教材从二维起始 cell 推导增量遍历，并强调命中必须落在当前 cell 的 t 区间。") }),
        b(57, "k-d tree 动画 1：保留 grid 的空间划分，准备自适应", "网格遍历切回原始三角形和 Non-regular space subdivision。", "k-d tree 每个内部节点用一个轴对齐平面二分空间。它像 grid 一样划分空间，又像 BVH 一样只在需要处递归加深。", ["subdivides space like grid", "adaptive like BVH", "初始根区域尚未切分"]),
        b(58, "k-d tree 动画 2：先做一次竖直空间切割", "原场景新增贯穿根区域的竖线。", "切割平面把空间分成互斥左右区域；跨平面的 triangle 必须被两边引用或切分。与 BVH 不同，线的位置定义严格空间边界。", ["第一条 axis-aligned split", "两个空间区域不重叠", "跨界对象可重复引用"]),
        b(59, "k-d tree 动画 3：只在右侧继续水平细分", "右子空间新增水平切割。", "自适应意味着不同区域深度不同：空或简单区域早停，复杂区域继续分。遍历根据射线与 split plane 的 t 决定 near/far child，并在需要时访问 far。", ["右侧局部二次划分", "非规则指 cell 尺寸不统一", "树仍由轴对齐二分组成"]),
        b(60, "工程收束：场景表示与加速索引应该解耦", "动画结束，最后一页给出软件结构建议。", ["把 acceleration node 直接塞进 scene graph 概念上简单，却让替换 BVH/grid/k-d tree、重建动态对象和测试变困难。更好的设计让 scene 保持语义对象列表，由独立 accelerator 构建索引并实现同一 intersect 接口。", "这样可用同一场景同时跑 brute force 与多个 accelerator，既方便性能实验，也提供最可靠的正确性 oracle。"], ["plug and play structures", "keep scene representation simple", "accelerator 是可替换查询后端"], { pause: "设计 Accelerator 接口：build(primitives)、intersect(ray,interval)、occluded(ray,interval)、stats()；说明动态变换时哪些结构 refit、哪些 rebuild。" }),
      ],
      checkpoint: "为同一 primitive 列表实现 brute-force 与至少一种 accelerator；随机生成 100 万条主射线/阴影线，逐条比较 hit、id、t，并输出节点、cell 和 primitive 测试统计。",
    },
  ],
  synthesis: [
    "表示层：TransformedSurface 把射线送入局部空间，SurfaceGroup 把多个孩子统一成最近命中接口；实例只是多个变换边共享同一子图。",
    "数值层：不归一化局部方向可保持仿射参数 t；点乘 T，法线乘 T⁻ᵀ，并始终携带 [tMin,tMax]。",
    "保守层：包围体允许命中后实际 miss，却绝不能让真实 primitive 命中被 bound miss 排除。",
    "层级层：BVH 划分对象集合，兄弟盒可重叠；near-first 与 currentClosest 收紧只减少工作，不改变最终最小 t。",
    "区间层：AABB 是三个 slab 的交，tEnter 取所有进入的 max，tExit 取所有退出的 min，再与调用区间相交。",
    "构建层：center、median 和 SAH 都可构建正确 BVH，但重叠、表面积、叶大小与树深决定遍历成本。",
    "空间层：uniform grid 与 k-d tree 划分空间，一个 primitive 可进入多个单元；DDA/k-d traversal 必须尊重当前 cell/plane 的 t 区间。",
    "验证层：任何加速器都应以暴力遍历为 oracle，同时记录 bound/node/cell/primitive tests，分开评估正确性和速度。",
  ],
  finalPractice: "实现 AccelerationLab：载入含重复车轮实例和至少十万三角形的场景。先完成 TransformedSurface、SurfaceGroup、AABB slab 与 brute force，再实现 top-down BVH（median，选做 binned SAH）。界面可切换 brute/BVH，显示访问盒、叶和最终命中，并报告 build time、nodes、depth、boxTests、primitiveTests 与 render time。测试必须覆盖非均匀缩放的逆转置法线、局部方向不归一化时 t 保持、AABB 平行/负零/盒内/擦边/有限区间、兄弟盒重叠、near-first 与固定顺序结果一致、实例共享同一子 BVH，以及至少 100 万条随机射线与 brute-force 的 hit/id/t 一致。最后比较 center、median、SAH 和不同 leaf size，解释为什么树更平衡不一定更快。",
};
